/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.59
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BrainClient);
  }
}(this, function(expect, BrainClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new BrainClient.GeboDeepSearchAdminControllerApi();
  });

  describe('(package)', function() {
    describe('GeboDeepSearchAdminControllerApi', function() {
      describe('deleteDeepSearchConfig', function() {
        it('should call deleteDeepSearchConfig successfully', function(done) {
          // TODO: uncomment, update parameter values for deleteDeepSearchConfig call
          /*

          instance.deleteDeepSearchConfig(body).then(function(data) {

            done();
          }, function(error) {
            done(error);
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getConfigurableDataSources', function() {
        it('should call getConfigurableDataSources successfully', function(done) {
          // TODO: uncomment getConfigurableDataSources call and complete the assertions
          /*

          instance.getConfigurableDataSources().then(function(data) {
            // TODO: update response assertions
            expect(data).to.be.a(Object);
            // expect(data).to.be(null);

            done();
          }, function(error) {
            done(error);
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getDeepSeachConfigs', function() {
        it('should call getDeepSeachConfigs successfully', function(done) {
          // TODO: uncomment getDeepSeachConfigs call and complete the assertions
          /*

          instance.getDeepSeachConfigs().then(function(data) {
            // TODO: update response assertions
            expect(data).to.be.a(Object);
            // expect(data).to.be(null);

            done();
          }, function(error) {
            done(error);
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getDeepSearchDefaultConfig', function() {
        it('should call getDeepSearchDefaultConfig successfully', function(done) {
          // TODO: uncomment getDeepSearchDefaultConfig call and complete the assertions
          /*

          instance.getDeepSearchDefaultConfig().then(function(data) {
            // TODO: update response assertions
            expect(data).to.be.a(BrainClient.DeepSearchConfig);

            done();
          }, function(error) {
            done(error);
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getDeepSearchDefaultOrSystemConfig', function() {
        it('should call getDeepSearchDefaultOrSystemConfig successfully', function(done) {
          // TODO: uncomment getDeepSearchDefaultOrSystemConfig call and complete the assertions
          /*

          instance.getDeepSearchDefaultOrSystemConfig().then(function(data) {
            // TODO: update response assertions
            expect(data).to.be.a(BrainClient.DeepSearchConfig);

            done();
          }, function(error) {
            done(error);
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getDeepSearchSystemConfig', function() {
        it('should call getDeepSearchSystemConfig successfully', function(done) {
          // TODO: uncomment getDeepSearchSystemConfig call and complete the assertions
          /*

          instance.getDeepSearchSystemConfig().then(function(data) {
            // TODO: update response assertions
            expect(data).to.be.a(BrainClient.DeepSearchConfig);

            done();
          }, function(error) {
            done(error);
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('insertDeepSearchConfig', function() {
        it('should call insertDeepSearchConfig successfully', function(done) {
          // TODO: uncomment, update parameter values for insertDeepSearchConfig call and complete the assertions
          /*

          instance.insertDeepSearchConfig(body).then(function(data) {
            // TODO: update response assertions
            expect(data).to.be.a(BrainClient.DeepSearchConfig);

            done();
          }, function(error) {
            done(error);
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('updateDeepSearchConfig', function() {
        it('should call updateDeepSearchConfig successfully', function(done) {
          // TODO: uncomment, update parameter values for updateDeepSearchConfig call and complete the assertions
          /*

          instance.updateDeepSearchConfig(body).then(function(data) {
            // TODO: update response assertions
            expect(data).to.be.a(BrainClient.DeepSearchConfig);

            done();
          }, function(error) {
            done(error);
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
