/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.59
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GeboAiClient);
  }
}(this, function(expect, GeboAiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new GeboAiClient.IntegrationInputControllerApi();
  });

  describe('(package)', function() {
    describe('IntegrationInputControllerApi', function() {
      describe('publishContents', function() {
        it('should call publishContents successfully', function(done) {
          // TODO: uncomment, update parameter values for publishContents call and complete the assertions
          /*

          instance.publishContents(body, endpointCode).then(function(data) {
            // TODO: update response assertions
            expect(data).to.be.a(GeboAiClient.JobTicket);

            done();
          }, function(error) {
            done(error);
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('publishSync', function() {
        it('should call publishSync successfully', function(done) {
          // TODO: uncomment, update parameter values for publishSync call and complete the assertions
          /*

          instance.publishSync(endpointCode).then(function(data) {
            // TODO: update response assertions
            expect(data).to.be.a(GeboAiClient.JobTicket);

            done();
          }, function(error) {
            done(error);
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('spoolDocument', function() {
        it('should call spoolDocument successfully', function(done) {
          // TODO: uncomment, update parameter values for spoolDocument call and complete the assertions
          /*

          instance.spoolDocument(body, endpointCode, relativePath).then(function(data) {
            // TODO: update response assertions
            expect(data).to.be.a(GeboAiClient.JobTicket);

            done();
          }, function(error) {
            done(error);
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('spoolDocument1', function() {
        it('should call spoolDocument1 successfully', function(done) {
          // TODO: uncomment, update parameter values for spoolDocument1 call and complete the assertions
          /*

          instance.spoolDocument1(file, endpointCode, relativePath).then(function(data) {
            // TODO: update response assertions
            expect(data).to.be.a(GeboAiClient.JobTicket);

            done();
          }, function(error) {
            done(error);
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
