/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ai.gebo.monolithic.api.client.api;

import ai.gebo.monolithic.api.client.model.GenericOpenAIAPIEmbeddingModelConfig;
import ai.gebo.monolithic.api.client.model.GenericOpenAIEmbeddingModelTypeConfig;
import ai.gebo.monolithic.api.client.model.OperationStatusBoolean;
import ai.gebo.monolithic.api.client.model.OperationStatusGenericOpenAIAPIEmbeddingModelConfig;
import ai.gebo.monolithic.api.client.model.OperationStatusListGenericOpenAIAPIEmbeddingModelChoice;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for GenericOpenAiapiEmbeddingModelsConfigurationControllerApi
 */
@Ignore
public class GenericOpenAiapiEmbeddingModelsConfigurationControllerApiTest {

    private final GenericOpenAiapiEmbeddingModelsConfigurationControllerApi api = new GenericOpenAiapiEmbeddingModelsConfigurationControllerApi();

    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteGenericOpenAIAPIEmbeddingModelConfigTest() {
        GenericOpenAIAPIEmbeddingModelConfig body = null;
        OperationStatusBoolean response = api.deleteGenericOpenAIAPIEmbeddingModelConfig(body);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findGenericOpenAIAPIEmbeddingModelConfigByCodeTest() {
        String code = null;
        GenericOpenAIAPIEmbeddingModelConfig response = api.findGenericOpenAIAPIEmbeddingModelConfigByCode(code);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getGenericOpenAIAPIEmbeddingModelsTest() {
        GenericOpenAIAPIEmbeddingModelConfig body = null;
        OperationStatusListGenericOpenAIAPIEmbeddingModelChoice response = api.getGenericOpenAIAPIEmbeddingModels(body);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getGenericOpenAIEmbeddingModelTypesTest() {
        List<GenericOpenAIEmbeddingModelTypeConfig> response = api.getGenericOpenAIEmbeddingModelTypes();

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void insertGenericOpenAIAPIEmbeddingModelConfigTest() {
        GenericOpenAIAPIEmbeddingModelConfig body = null;
        OperationStatusGenericOpenAIAPIEmbeddingModelConfig response = api.insertGenericOpenAIAPIEmbeddingModelConfig(body);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateGenericOpenAIAPIEmbeddingModelConfigTest() {
        GenericOpenAIAPIEmbeddingModelConfig body = null;
        OperationStatusGenericOpenAIAPIEmbeddingModelConfig response = api.updateGenericOpenAIAPIEmbeddingModelConfig(body);

        // TODO: test validations
    }
}
