/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ai.gebo.monolithic.api.client.api;

import ai.gebo.monolithic.api.client.model.GKnowledgeBase;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for KnowledgeBaseControllerApi
 */
@Ignore
public class KnowledgeBaseControllerApiTest {

    private final KnowledgeBaseControllerApi api = new KnowledgeBaseControllerApi();

    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteKnowledgeBaseTest() {
        GKnowledgeBase body = null;
        api.deleteKnowledgeBase(body);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findKnowledgeBaseByCodeTest() {
        String code = null;
        GKnowledgeBase response = api.findKnowledgeBaseByCode(code);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findKnowledgeBasesByQbeTest() {
        GKnowledgeBase body = null;
        List<GKnowledgeBase> response = api.findKnowledgeBasesByQbe(body);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getChildKnowledgeBasesTest() {
        String code = null;
        List<GKnowledgeBase> response = api.getChildKnowledgeBases(code);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getKnowledgeBasesTest() {
        List<GKnowledgeBase> response = api.getKnowledgeBases();

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void insertKnowledgeBaseTest() {
        GKnowledgeBase body = null;
        GKnowledgeBase response = api.insertKnowledgeBase(body);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateKnowledgeBaseTest() {
        GKnowledgeBase body = null;
        GKnowledgeBase response = api.updateKnowledgeBase(body);

        // TODO: test validations
    }
}
