/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ai.gebo.monolithic.api.client.api;

import java.io.File;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UserspaceUploadControllerApi
 */
@Ignore
public class UserspaceUploadControllerApiTest {

    private final UserspaceUploadControllerApi api = new UserspaceUploadControllerApi();

    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void uploadTest() {
        String userspaceFolderCode = null;
        List<File> files = null;
        api.upload(userspaceFolderCode, files);

        // TODO: test validations
    }
}
