/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface JiraAdditionalSearchFilter { 
    issueKeys?: Array<string>;
    summaryTerms?: Array<string>;
    summaryTermsMatchMode?: JiraAdditionalSearchFilter.SummaryTermsMatchModeEnum;
    descriptionTerms?: Array<string>;
    descriptionTermsMatchMode?: JiraAdditionalSearchFilter.DescriptionTermsMatchModeEnum;
}
export namespace JiraAdditionalSearchFilter {
    export type SummaryTermsMatchModeEnum = 'ANY' | 'ALL';
    export const SummaryTermsMatchModeEnum = {
        ANY: 'ANY' as SummaryTermsMatchModeEnum,
        ALL: 'ALL' as SummaryTermsMatchModeEnum
    };
    export type DescriptionTermsMatchModeEnum = 'ANY' | 'ALL';
    export const DescriptionTermsMatchModeEnum = {
        ANY: 'ANY' as DescriptionTermsMatchModeEnum,
        ALL: 'ALL' as DescriptionTermsMatchModeEnum
    };
}