/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ComputedWorkflowStatus { 
    jobId?: any;
    workflowType?: any;
    workflowId?: any;
    workflowStepId?: any;
    description?: any;
    batchDocumentsInput?: any;
    batchDocumentsProcessingErrors?: any;
    batchDocumentsProcessed?: any;
    batchSentToNextStep?: any;
    batchDiscardedInput?: any;
    chunksProcessed?: any;
    tokensProcessed?: any;
    completed?: any;
    hasErrors?: any;
    startedRunning?: any;
    levelId?: any;
    enabledStep?: any;
    startProcessingTimestamp?: any;
    lastProcessingTimestamp?: any;
    childs?: any;
}