/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.59
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BrainClient);
  }
}(this, function(expect, BrainClient) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('A2AExportedAgent', function() {
      beforeEach(function() {
        instance = new BrainClient.A2AExportedAgent();
      });

      it('should create an instance of A2AExportedAgent', function() {
        // TODO: update the code to test A2AExportedAgent
        expect(instance).to.be.a(BrainClient.A2AExportedAgent);
      });

      it('should have the property kind (base name: "kind")', function() {
        // TODO: update the code to test the property kind
        expect(instance).to.have.property('kind');
        // expect(instance.kind).to.be(expectedValueLiteral);
      });

      it('should have the property networkCode (base name: "networkCode")', function() {
        // TODO: update the code to test the property networkCode
        expect(instance).to.have.property('networkCode');
        // expect(instance.networkCode).to.be(expectedValueLiteral);
      });

      it('should have the property agentConfigCode (base name: "agentConfigCode")', function() {
        // TODO: update the code to test the property agentConfigCode
        expect(instance).to.have.property('agentConfigCode');
        // expect(instance.agentConfigCode).to.be(expectedValueLiteral);
      });

      it('should have the property skillName (base name: "skillName")', function() {
        // TODO: update the code to test the property skillName
        expect(instance).to.have.property('skillName');
        // expect(instance.skillName).to.be(expectedValueLiteral);
      });

      it('should have the property exposeMemberCapabilities (base name: "exposeMemberCapabilities")', function() {
        // TODO: update the code to test the property exposeMemberCapabilities
        expect(instance).to.have.property('exposeMemberCapabilities');
        // expect(instance.exposeMemberCapabilities).to.be(expectedValueLiteral);
      });

    });
  });

}));
