/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.59
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BrainClient);
  }
}(this, function(expect, BrainClient) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('PipelineChatMenu', function() {
      beforeEach(function() {
        instance = new BrainClient.PipelineChatMenu();
      });

      it('should create an instance of PipelineChatMenu', function() {
        // TODO: update the code to test PipelineChatMenu
        expect(instance).to.be.a(BrainClient.PipelineChatMenu);
      });

      it('should have the property menuId (base name: "menuId")', function() {
        // TODO: update the code to test the property menuId
        expect(instance).to.have.property('menuId');
        // expect(instance.menuId).to.be(expectedValueLiteral);
      });

      it('should have the property pipelineId (base name: "pipelineId")', function() {
        // TODO: update the code to test the property pipelineId
        expect(instance).to.have.property('pipelineId');
        // expect(instance.pipelineId).to.be(expectedValueLiteral);
      });

      it('should have the property description (base name: "description")', function() {
        // TODO: update the code to test the property description
        expect(instance).to.have.property('description');
        // expect(instance.description).to.be(expectedValueLiteral);
      });

      it('should have the property icon (base name: "icon")', function() {
        // TODO: update the code to test the property icon
        expect(instance).to.have.property('icon');
        // expect(instance.icon).to.be(expectedValueLiteral);
      });

      it('should have the property items (base name: "items")', function() {
        // TODO: update the code to test the property items
        expect(instance).to.have.property('items');
        // expect(instance.items).to.be(expectedValueLiteral);
      });

      it('should have the property order (base name: "order")', function() {
        // TODO: update the code to test the property order
        expect(instance).to.have.property('order');
        // expect(instance.order).to.be(expectedValueLiteral);
      });

    });
  });

}));
