<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>ai.gebo</groupId>
    <artifactId>ai.gebo.parent</artifactId>
    <version>1.0.2.2</version>
  </parent>
  <groupId>ai.gebo.clients</groupId>
  <artifactId>gebo.api.clients</artifactId>
  <packaging>pom</packaging>
  <modules>
  	<module>gebo.monolithic.api.resttemplate.client</module>
  	<!-- 
		Following module will be regenerated/compiled on specific pipelines no reason to 
		take always part on an "cascade" build. -->
		<!--  
  		<module>gebo.microservices.clients.parent</module>
  	-->
  </modules>
</project>
