/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GBaseTranscriptModelChoice } from './gBaseTranscriptModelChoice';

export interface GBaseTranscriptModelConfig { 
    code?: string;
    description?: string;
    userModified?: string;
    userCreated?: string;
    dateModified?: Date;
    dateCreated?: Date;
    modelTypeCode?: string;
    defaultModel?: boolean;
    apiSecretCode?: string;
    choosedModel?: GBaseTranscriptModelChoice;
    baseUrl?: string;
    contextLength?: number;
}