/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface DocumentReferenceView { 
    name?: string;
    extension?: string;
    code?: string;
    messagingModuleId?: string;
    relativePath?: string;
    parentVirtualFolderCode?: string;
    modificationDate?: Date;
    parentProjectCode?: string;
    rootKnowledgebaseCode?: string;
    contentType?: string;
    creationDate?: Date;
    description?: string;
    deleted?: boolean;
}