/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CalledFunction } from './calledFunction';
import { ChatModelRequestContextWindowStats } from './chatModelRequestContextWindowStats';
import { GResponseDocumentRef } from './gResponseDocumentRef';
import { GUserMessage } from './gUserMessage';
import { GeboWorkingMemoryWindowOccupation } from './geboWorkingMemoryWindowOccupation';
import { LLMGeneratedResource } from './lLMGeneratedResource';

export interface GeboTemplatedChatResponse { 
    id?: string;
    userChatContextCode?: string;
    usedChatModelCode?: string;
    usedChatModelProvider?: string;
    queryResponse?: any;
    windowOccupation?: GeboWorkingMemoryWindowOccupation;
    query?: string;
    backendMessages?: Array<GUserMessage>;
    forcedDocumentsRef?: Array<GResponseDocumentRef>;
    documentsRef?: Array<GResponseDocumentRef>;
    calledFunctions?: Array<CalledFunction>;
    contextWindowStats?: ChatModelRequestContextWindowStats;
    generatedResources?: Array<LLMGeneratedResource>;
}