/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GObjectRefGProjectEndpoint } from './gObjectRefGProjectEndpoint';

export interface GJobStatus { 
    code?: string;
    description?: string;
    userModified?: string;
    userCreated?: string;
    dateModified?: Date;
    dateCreated?: Date;
    jobType?: GJobStatus.JobTypeEnum;
    processing?: boolean;
    vectorizationEnded?: boolean;
    contentBatchEnded?: boolean;
    finished?: boolean;
    error?: boolean;
    lastBatchMessage?: boolean;
    howManyBatchDocuments?: number;
    howManyBatchSentToVectorization?: number;
    howManyBatchContentsReadingErrors?: number;
    howManyBatchPersistendDocuments?: number;
    currentBatchDocumentVectorizedCounter?: number;
    currentBatchDocumentReceviedCounter?: number;
    vectorizationErrors?: number;
    vectorizedSegments?: number;
    vectorizedTokens?: number;
    startDateTime?: Date;
    endDateTime?: Date;
    projectEndpointReference?: GObjectRefGProjectEndpoint;
    parentJobCode?: string;
}
export namespace GJobStatus {
    export type JobTypeEnum = 'CONTENTS_READING' | 'VECTORIZING_CONTENTS' | 'CONTENTS_READING_VECTORIZING';
    export const JobTypeEnum = {
        CONTENTSREADING: 'CONTENTS_READING' as JobTypeEnum,
        VECTORIZINGCONTENTS: 'VECTORIZING_CONTENTS' as JobTypeEnum,
        CONTENTSREADINGVECTORIZING: 'CONTENTS_READING_VECTORIZING' as JobTypeEnum
    };
}