/**
 * This Source Code is subject to the terms of the 
 * Gebo.ai community version Mozilla Public License Version 2.0 (MPL-2.0) — With Data Protection Clauses
 * If a copy of the LICENCE was not distributed with this file, You can obtain one at 
 * https://gebo.ai/gebo-ai-community-version-mozilla-public-license-version-2-0-mpl-2-0-with-data-protection-clauses/  
 * and https://mozilla.org/MPL/2.0/.
 * Copyright (c) 2025+ Gebo.ai 
 */
 
 
 

/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface GSharepointContentManagementSystem { 
    code?: string;
    description?: string;
    userModified?: string;
    userCreated?: string;
    dateModified?: Date;
    dateCreated?: Date;
    creationDate?: Date;
    modificationDate?: Date;
    version?: string;
    contentManagementSystemType?: string;
    readonly?: boolean;
    baseUri?: string;
    usedCapabilities?: Array<GSharepointContentManagementSystem.UsedCapabilitiesEnum>;
    secretCode: string;
    sharepointVersion: GSharepointContentManagementSystem.SharepointVersionEnum;
}
export namespace GSharepointContentManagementSystem {
    export type UsedCapabilitiesEnum = 'TICKETS_MANAGEMENT' | 'DOCUMENTS_MANAGEMENT' | 'SOURCE_MANAGEMENT' | 'ARTIFACTS_REPOSITORY_MANAGEMENT';
    export const UsedCapabilitiesEnum = {
        TICKETSMANAGEMENT: 'TICKETS_MANAGEMENT' as UsedCapabilitiesEnum,
        DOCUMENTSMANAGEMENT: 'DOCUMENTS_MANAGEMENT' as UsedCapabilitiesEnum,
        SOURCEMANAGEMENT: 'SOURCE_MANAGEMENT' as UsedCapabilitiesEnum,
        ARTIFACTSREPOSITORYMANAGEMENT: 'ARTIFACTS_REPOSITORY_MANAGEMENT' as UsedCapabilitiesEnum
    };
    export type SharepointVersionEnum = 'CLOUD_VERSION' | 'ONPREMISE2019';
    export const SharepointVersionEnum = {
        CLOUDVERSION: 'CLOUD_VERSION' as SharepointVersionEnum,
        ONPREMISE2019: 'ONPREMISE2019' as SharepointVersionEnum
    };
}