/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { LLMModelPresetChoice } from './lLMModelPresetChoice';

export interface LLMSModelsPresets { 
    doModelsLookup?: boolean;
    type: LLMSModelsPresets.TypeEnum;
    serviceHandler: string;
    choices?: Array<LLMModelPresetChoice>;
}
export namespace LLMSModelsPresets {
    export type TypeEnum = 'CHAT' | 'EMBEDDING';
    export const TypeEnum = {
        CHAT: 'CHAT' as TypeEnum,
        EMBEDDING: 'EMBEDDING' as TypeEnum
    };
}