/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Oauth2ProviderModifiableData { 
    registrationId: string;
    authClientMethod?: Oauth2ProviderModifiableData.AuthClientMethodEnum;
    authGrantType?: Oauth2ProviderModifiableData.AuthGrantTypeEnum;
    description?: string;
    configurationTypes: Array<Oauth2ProviderModifiableData.ConfigurationTypesEnum>;
    scopes?: Array<string>;
}
export namespace Oauth2ProviderModifiableData {
    export type AuthClientMethodEnum = 'CLIENT_SECRET_BASIC' | 'CLIENT_SECRET_POST' | 'CLIENT_SECRET_JWT' | 'PRIVATE_KEY_JWT' | 'NONE' | 'TLS_CLIENT_AUTH' | 'SELF_SIGNED_TLS_CLIENT_AUTH';
    export const AuthClientMethodEnum = {
        CLIENTSECRETBASIC: 'CLIENT_SECRET_BASIC' as AuthClientMethodEnum,
        CLIENTSECRETPOST: 'CLIENT_SECRET_POST' as AuthClientMethodEnum,
        CLIENTSECRETJWT: 'CLIENT_SECRET_JWT' as AuthClientMethodEnum,
        PRIVATEKEYJWT: 'PRIVATE_KEY_JWT' as AuthClientMethodEnum,
        NONE: 'NONE' as AuthClientMethodEnum,
        TLSCLIENTAUTH: 'TLS_CLIENT_AUTH' as AuthClientMethodEnum,
        SELFSIGNEDTLSCLIENTAUTH: 'SELF_SIGNED_TLS_CLIENT_AUTH' as AuthClientMethodEnum
    };
    export type AuthGrantTypeEnum = 'AUTHORIZATION_CODE' | 'REFRESH_TOKEN' | 'CLIENT_CREDENTIALS' | 'PASSWORD' | 'JWT_BEARER' | 'DEVICE_CODE' | 'TOKEN_EXCHANGE';
    export const AuthGrantTypeEnum = {
        AUTHORIZATIONCODE: 'AUTHORIZATION_CODE' as AuthGrantTypeEnum,
        REFRESHTOKEN: 'REFRESH_TOKEN' as AuthGrantTypeEnum,
        CLIENTCREDENTIALS: 'CLIENT_CREDENTIALS' as AuthGrantTypeEnum,
        PASSWORD: 'PASSWORD' as AuthGrantTypeEnum,
        JWTBEARER: 'JWT_BEARER' as AuthGrantTypeEnum,
        DEVICECODE: 'DEVICE_CODE' as AuthGrantTypeEnum,
        TOKENEXCHANGE: 'TOKEN_EXCHANGE' as AuthGrantTypeEnum
    };
    export type ConfigurationTypesEnum = 'AUTHENTICATION' | 'INTEGRATION';
    export const ConfigurationTypesEnum = {
        AUTHENTICATION: 'AUTHENTICATION' as ConfigurationTypesEnum,
        INTEGRATION: 'INTEGRATION' as ConfigurationTypesEnum
    };
}