/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface UploadedFileNode { 
    name?: string;
    relativePath?: string;
    extension?: string;
    folder?: boolean;
    size?: number;
    modificationTime?: Date;
    published?: boolean;
    documentCode?: string;
    filesCount?: number;
    publishedFilesCount?: number;
    children?: Array<UploadedFileNode>;
}