<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>ai.gebo</groupId>
		<artifactId>ai.gebo.parent</artifactId>
		<version>1.0.3.0-SNAPSHOT</version>
	</parent>
	<groupId>ai.gebo.microservices.architecture</groupId>
	<artifactId>gebo.microservices.architecture.parent</artifactId>
	<packaging>pom</packaging>
	<modules>
		<module>gebo.microservices.topology</module>
		<module>gebo.architecture.messages.rabbitmq</module>
		<module>gebo.architecture.environment.microservices</module>
		<module>gebo.microservices.models.replication.cluster</module>
		<module>gebo.microservices.llms.starter</module>
		<module>
			gebo.architecture.documents.cache.microservice.controller
		</module>
		<module>
			gebo.architecture.documents.cache.microservice.client
		</module>
		<module>gebo.microservices.starter</module>
		<module>
			gebo.architecture.microservices.documents.access
		</module>
		<module>gebo.microservices.content-handler.starter</module>
		<module>gebo.microservices.cluster.commons</module>
		<module>gebo.microservices.secrets.controller</module>
		<module>gebo.microservices.secrets.client</module>
		<module>gebo.microservices.security.controller</module>
		<module>gebo.microservices.security.client</module>
		<module>gebo.microservices.acl.controller</module>
		<module>gebo.microservices.acl.client</module>
		<module>gebo.microservices.knowledgebase.client</module>
		<module>gebo.microservices.internal-topology.controllers</module>
		<module>gebo.microservices.global-internal-topology</module>
		<module>gebo.microservices.global-internal-topology.client</module>
		<module>gebo.microservices.searchservices.clients</module>
		<module>gebo.microservices.workflow.steps.topology</module>
	</modules>
</project>
