/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.59
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import ThreasholdAutotuneProcessResult from './ThreasholdAutotuneProcessResult';

/**
 * The AutotuneVectorStoreInfo model module.
 * @module model/AutotuneVectorStoreInfo
 * @version v0
 */
export default class AutotuneVectorStoreInfo {
  /**
   * Constructs a new <code>AutotuneVectorStoreInfo</code>.
   * @alias module:model/AutotuneVectorStoreInfo
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>AutotuneVectorStoreInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AutotuneVectorStoreInfo} obj Optional instance to populate.
   * @return {module:model/AutotuneVectorStoreInfo} The populated <code>AutotuneVectorStoreInfo</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AutotuneVectorStoreInfo();
      if (data.hasOwnProperty('code'))
        obj.code = ApiClient.convertToType(data['code'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('userModified'))
        obj.userModified = ApiClient.convertToType(data['userModified'], 'String');
      if (data.hasOwnProperty('userCreated'))
        obj.userCreated = ApiClient.convertToType(data['userCreated'], 'String');
      if (data.hasOwnProperty('dateModified'))
        obj.dateModified = ApiClient.convertToType(data['dateModified'], 'Date');
      if (data.hasOwnProperty('dateCreated'))
        obj.dateCreated = ApiClient.convertToType(data['dateCreated'], 'Date');
      if (data.hasOwnProperty('autotuneResult'))
        obj.autotuneResult = ThreasholdAutotuneProcessResult.constructFromObject(data['autotuneResult']);
    }
    return obj;
  }
}

/**
 * @member {String} code
 */
AutotuneVectorStoreInfo.prototype.code = undefined;

/**
 * @member {String} description
 */
AutotuneVectorStoreInfo.prototype.description = undefined;

/**
 * @member {String} userModified
 */
AutotuneVectorStoreInfo.prototype.userModified = undefined;

/**
 * @member {String} userCreated
 */
AutotuneVectorStoreInfo.prototype.userCreated = undefined;

/**
 * @member {Date} dateModified
 */
AutotuneVectorStoreInfo.prototype.dateModified = undefined;

/**
 * @member {Date} dateCreated
 */
AutotuneVectorStoreInfo.prototype.dateCreated = undefined;

/**
 * @member {module:model/ThreasholdAutotuneProcessResult} autotuneResult
 */
AutotuneVectorStoreInfo.prototype.autotuneResult = undefined;

