/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.59
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The ComputedWorkflowStatus model module.
 * @module model/ComputedWorkflowStatus
 * @version v0
 */
export default class ComputedWorkflowStatus {
  /**
   * Constructs a new <code>ComputedWorkflowStatus</code>.
   * @alias module:model/ComputedWorkflowStatus
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ComputedWorkflowStatus</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ComputedWorkflowStatus} obj Optional instance to populate.
   * @return {module:model/ComputedWorkflowStatus} The populated <code>ComputedWorkflowStatus</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ComputedWorkflowStatus();
      if (data.hasOwnProperty('jobId'))
        obj.jobId = ApiClient.convertToType(data['jobId'], 'String');
      if (data.hasOwnProperty('workflowType'))
        obj.workflowType = ApiClient.convertToType(data['workflowType'], 'String');
      if (data.hasOwnProperty('workflowId'))
        obj.workflowId = ApiClient.convertToType(data['workflowId'], 'String');
      if (data.hasOwnProperty('workflowStepId'))
        obj.workflowStepId = ApiClient.convertToType(data['workflowStepId'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('batchDocumentsInput'))
        obj.batchDocumentsInput = ApiClient.convertToType(data['batchDocumentsInput'], 'Number');
      if (data.hasOwnProperty('batchDocumentsProcessingErrors'))
        obj.batchDocumentsProcessingErrors = ApiClient.convertToType(data['batchDocumentsProcessingErrors'], 'Number');
      if (data.hasOwnProperty('batchDocumentsProcessed'))
        obj.batchDocumentsProcessed = ApiClient.convertToType(data['batchDocumentsProcessed'], 'Number');
      if (data.hasOwnProperty('batchSentToNextStep'))
        obj.batchSentToNextStep = ApiClient.convertToType(data['batchSentToNextStep'], 'Number');
      if (data.hasOwnProperty('batchDiscardedInput'))
        obj.batchDiscardedInput = ApiClient.convertToType(data['batchDiscardedInput'], 'Number');
      if (data.hasOwnProperty('chunksProcessed'))
        obj.chunksProcessed = ApiClient.convertToType(data['chunksProcessed'], 'Number');
      if (data.hasOwnProperty('tokensProcessed'))
        obj.tokensProcessed = ApiClient.convertToType(data['tokensProcessed'], 'Number');
      if (data.hasOwnProperty('completed'))
        obj.completed = ApiClient.convertToType(data['completed'], 'Boolean');
      if (data.hasOwnProperty('hasErrors'))
        obj.hasErrors = ApiClient.convertToType(data['hasErrors'], 'Boolean');
      if (data.hasOwnProperty('startedRunning'))
        obj.startedRunning = ApiClient.convertToType(data['startedRunning'], 'Boolean');
      if (data.hasOwnProperty('levelId'))
        obj.levelId = ApiClient.convertToType(data['levelId'], 'Number');
      if (data.hasOwnProperty('enabledStep'))
        obj.enabledStep = ApiClient.convertToType(data['enabledStep'], 'Boolean');
      if (data.hasOwnProperty('startProcessingTimestamp'))
        obj.startProcessingTimestamp = ApiClient.convertToType(data['startProcessingTimestamp'], 'Date');
      if (data.hasOwnProperty('lastProcessingTimestamp'))
        obj.lastProcessingTimestamp = ApiClient.convertToType(data['lastProcessingTimestamp'], 'Date');
      if (data.hasOwnProperty('childs'))
        obj.childs = ApiClient.convertToType(data['childs'], [ComputedWorkflowStatus]);
    }
    return obj;
  }
}

/**
 * @member {String} jobId
 */
ComputedWorkflowStatus.prototype.jobId = undefined;

/**
 * @member {String} workflowType
 */
ComputedWorkflowStatus.prototype.workflowType = undefined;

/**
 * @member {String} workflowId
 */
ComputedWorkflowStatus.prototype.workflowId = undefined;

/**
 * @member {String} workflowStepId
 */
ComputedWorkflowStatus.prototype.workflowStepId = undefined;

/**
 * @member {String} description
 */
ComputedWorkflowStatus.prototype.description = undefined;

/**
 * @member {Number} batchDocumentsInput
 */
ComputedWorkflowStatus.prototype.batchDocumentsInput = undefined;

/**
 * @member {Number} batchDocumentsProcessingErrors
 */
ComputedWorkflowStatus.prototype.batchDocumentsProcessingErrors = undefined;

/**
 * @member {Number} batchDocumentsProcessed
 */
ComputedWorkflowStatus.prototype.batchDocumentsProcessed = undefined;

/**
 * @member {Number} batchSentToNextStep
 */
ComputedWorkflowStatus.prototype.batchSentToNextStep = undefined;

/**
 * @member {Number} batchDiscardedInput
 */
ComputedWorkflowStatus.prototype.batchDiscardedInput = undefined;

/**
 * @member {Number} chunksProcessed
 */
ComputedWorkflowStatus.prototype.chunksProcessed = undefined;

/**
 * @member {Number} tokensProcessed
 */
ComputedWorkflowStatus.prototype.tokensProcessed = undefined;

/**
 * @member {Boolean} completed
 */
ComputedWorkflowStatus.prototype.completed = undefined;

/**
 * @member {Boolean} hasErrors
 */
ComputedWorkflowStatus.prototype.hasErrors = undefined;

/**
 * @member {Boolean} startedRunning
 */
ComputedWorkflowStatus.prototype.startedRunning = undefined;

/**
 * @member {Number} levelId
 */
ComputedWorkflowStatus.prototype.levelId = undefined;

/**
 * @member {Boolean} enabledStep
 */
ComputedWorkflowStatus.prototype.enabledStep = undefined;

/**
 * @member {Date} startProcessingTimestamp
 */
ComputedWorkflowStatus.prototype.startProcessingTimestamp = undefined;

/**
 * @member {Date} lastProcessingTimestamp
 */
ComputedWorkflowStatus.prototype.lastProcessingTimestamp = undefined;

/**
 * @member {Array.<module:model/ComputedWorkflowStatus>} childs
 */
ComputedWorkflowStatus.prototype.childs = undefined;

