/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.59
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import GenericOpenAIAPIImageModelChoice from './GenericOpenAIAPIImageModelChoice';

/**
 * The GenericOpenAIAPIImageModelConfig model module.
 * @module model/GenericOpenAIAPIImageModelConfig
 * @version v0
 */
export default class GenericOpenAIAPIImageModelConfig {
  /**
   * Constructs a new <code>GenericOpenAIAPIImageModelConfig</code>.
   * @alias module:model/GenericOpenAIAPIImageModelConfig
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GenericOpenAIAPIImageModelConfig</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GenericOpenAIAPIImageModelConfig} obj Optional instance to populate.
   * @return {module:model/GenericOpenAIAPIImageModelConfig} The populated <code>GenericOpenAIAPIImageModelConfig</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GenericOpenAIAPIImageModelConfig();
      if (data.hasOwnProperty('code'))
        obj.code = ApiClient.convertToType(data['code'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('userModified'))
        obj.userModified = ApiClient.convertToType(data['userModified'], 'String');
      if (data.hasOwnProperty('userCreated'))
        obj.userCreated = ApiClient.convertToType(data['userCreated'], 'String');
      if (data.hasOwnProperty('dateModified'))
        obj.dateModified = ApiClient.convertToType(data['dateModified'], 'Date');
      if (data.hasOwnProperty('dateCreated'))
        obj.dateCreated = ApiClient.convertToType(data['dateCreated'], 'Date');
      if (data.hasOwnProperty('modelTypeCode'))
        obj.modelTypeCode = ApiClient.convertToType(data['modelTypeCode'], 'String');
      if (data.hasOwnProperty('defaultModel'))
        obj.defaultModel = ApiClient.convertToType(data['defaultModel'], 'Boolean');
      if (data.hasOwnProperty('apiSecretCode'))
        obj.apiSecretCode = ApiClient.convertToType(data['apiSecretCode'], 'String');
      if (data.hasOwnProperty('choosedModel'))
        obj.choosedModel = GenericOpenAIAPIImageModelChoice.constructFromObject(data['choosedModel']);
      if (data.hasOwnProperty('baseUrl'))
        obj.baseUrl = ApiClient.convertToType(data['baseUrl'], 'String');
      if (data.hasOwnProperty('contextLength'))
        obj.contextLength = ApiClient.convertToType(data['contextLength'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {String} code
 */
GenericOpenAIAPIImageModelConfig.prototype.code = undefined;

/**
 * @member {String} description
 */
GenericOpenAIAPIImageModelConfig.prototype.description = undefined;

/**
 * @member {String} userModified
 */
GenericOpenAIAPIImageModelConfig.prototype.userModified = undefined;

/**
 * @member {String} userCreated
 */
GenericOpenAIAPIImageModelConfig.prototype.userCreated = undefined;

/**
 * @member {Date} dateModified
 */
GenericOpenAIAPIImageModelConfig.prototype.dateModified = undefined;

/**
 * @member {Date} dateCreated
 */
GenericOpenAIAPIImageModelConfig.prototype.dateCreated = undefined;

/**
 * @member {String} modelTypeCode
 */
GenericOpenAIAPIImageModelConfig.prototype.modelTypeCode = undefined;

/**
 * @member {Boolean} defaultModel
 */
GenericOpenAIAPIImageModelConfig.prototype.defaultModel = undefined;

/**
 * @member {String} apiSecretCode
 */
GenericOpenAIAPIImageModelConfig.prototype.apiSecretCode = undefined;

/**
 * @member {module:model/GenericOpenAIAPIImageModelChoice} choosedModel
 */
GenericOpenAIAPIImageModelConfig.prototype.choosedModel = undefined;

/**
 * @member {String} baseUrl
 */
GenericOpenAIAPIImageModelConfig.prototype.baseUrl = undefined;

/**
 * @member {Number} contextLength
 */
GenericOpenAIAPIImageModelConfig.prototype.contextLength = undefined;

