/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.59
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The GeneratedApiKey model module.
 * @module model/GeneratedApiKey
 * @version v0
 */
export default class GeneratedApiKey {
  /**
   * Constructs a new <code>GeneratedApiKey</code>.
   * @alias module:model/GeneratedApiKey
   * @class
   * @param apiKey {String} 
   * @param expiration {Date} 
   * @param impersonatedUser {String} 
   */
  constructor(apiKey, expiration, impersonatedUser) {
    this.apiKey = apiKey;
    this.expiration = expiration;
    this.impersonatedUser = impersonatedUser;
  }

  /**
   * Constructs a <code>GeneratedApiKey</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GeneratedApiKey} obj Optional instance to populate.
   * @return {module:model/GeneratedApiKey} The populated <code>GeneratedApiKey</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GeneratedApiKey();
      if (data.hasOwnProperty('code'))
        obj.code = ApiClient.convertToType(data['code'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('userModified'))
        obj.userModified = ApiClient.convertToType(data['userModified'], 'String');
      if (data.hasOwnProperty('userCreated'))
        obj.userCreated = ApiClient.convertToType(data['userCreated'], 'String');
      if (data.hasOwnProperty('dateModified'))
        obj.dateModified = ApiClient.convertToType(data['dateModified'], 'Date');
      if (data.hasOwnProperty('dateCreated'))
        obj.dateCreated = ApiClient.convertToType(data['dateCreated'], 'Date');
      if (data.hasOwnProperty('apiKey'))
        obj.apiKey = ApiClient.convertToType(data['apiKey'], 'String');
      if (data.hasOwnProperty('expiration'))
        obj.expiration = ApiClient.convertToType(data['expiration'], 'Date');
      if (data.hasOwnProperty('impersonatedUser'))
        obj.impersonatedUser = ApiClient.convertToType(data['impersonatedUser'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} code
 */
GeneratedApiKey.prototype.code = undefined;

/**
 * @member {String} description
 */
GeneratedApiKey.prototype.description = undefined;

/**
 * @member {String} userModified
 */
GeneratedApiKey.prototype.userModified = undefined;

/**
 * @member {String} userCreated
 */
GeneratedApiKey.prototype.userCreated = undefined;

/**
 * @member {Date} dateModified
 */
GeneratedApiKey.prototype.dateModified = undefined;

/**
 * @member {Date} dateCreated
 */
GeneratedApiKey.prototype.dateCreated = undefined;

/**
 * @member {String} apiKey
 */
GeneratedApiKey.prototype.apiKey = undefined;

/**
 * @member {Date} expiration
 */
GeneratedApiKey.prototype.expiration = undefined;

/**
 * @member {String} impersonatedUser
 */
GeneratedApiKey.prototype.impersonatedUser = undefined;

