/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.59
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The GObjectRefGUserspaceProjectEndpoint model module.
 * @module model/GObjectRefGUserspaceProjectEndpoint
 * @version v0
 */
export default class GObjectRefGUserspaceProjectEndpoint {
  /**
   * Constructs a new <code>GObjectRefGUserspaceProjectEndpoint</code>.
   * @alias module:model/GObjectRefGUserspaceProjectEndpoint
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GObjectRefGUserspaceProjectEndpoint</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GObjectRefGUserspaceProjectEndpoint} obj Optional instance to populate.
   * @return {module:model/GObjectRefGUserspaceProjectEndpoint} The populated <code>GObjectRefGUserspaceProjectEndpoint</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GObjectRefGUserspaceProjectEndpoint();
      if (data.hasOwnProperty('className'))
        obj.className = ApiClient.convertToType(data['className'], 'String');
      if (data.hasOwnProperty('code'))
        obj.code = ApiClient.convertToType(data['code'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} className
 */
GObjectRefGUserspaceProjectEndpoint.prototype.className = undefined;

/**
 * @member {String} code
 */
GObjectRefGUserspaceProjectEndpoint.prototype.code = undefined;

/**
 * @member {String} description
 */
GObjectRefGUserspaceProjectEndpoint.prototype.description = undefined;

