/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.59
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import GBedrockTranscriptModelConfig from './GBedrockTranscriptModelConfig';
import GUserMessage from './GUserMessage';

/**
 * The OperationStatusGBedrockTranscriptModelConfig model module.
 * @module model/OperationStatusGBedrockTranscriptModelConfig
 * @version v0
 */
export default class OperationStatusGBedrockTranscriptModelConfig {
  /**
   * Constructs a new <code>OperationStatusGBedrockTranscriptModelConfig</code>.
   * @alias module:model/OperationStatusGBedrockTranscriptModelConfig
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>OperationStatusGBedrockTranscriptModelConfig</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OperationStatusGBedrockTranscriptModelConfig} obj Optional instance to populate.
   * @return {module:model/OperationStatusGBedrockTranscriptModelConfig} The populated <code>OperationStatusGBedrockTranscriptModelConfig</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new OperationStatusGBedrockTranscriptModelConfig();
      if (data.hasOwnProperty('result'))
        obj.result = GBedrockTranscriptModelConfig.constructFromObject(data['result']);
      if (data.hasOwnProperty('messages'))
        obj.messages = ApiClient.convertToType(data['messages'], [GUserMessage]);
      if (data.hasOwnProperty('hasWarnMessages'))
        obj.hasWarnMessages = ApiClient.convertToType(data['hasWarnMessages'], 'Boolean');
      if (data.hasOwnProperty('hasErrorMessages'))
        obj.hasErrorMessages = ApiClient.convertToType(data['hasErrorMessages'], 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {module:model/GBedrockTranscriptModelConfig} result
 */
OperationStatusGBedrockTranscriptModelConfig.prototype.result = undefined;

/**
 * @member {Array.<module:model/GUserMessage>} messages
 */
OperationStatusGBedrockTranscriptModelConfig.prototype.messages = undefined;

/**
 * @member {Boolean} hasWarnMessages
 */
OperationStatusGBedrockTranscriptModelConfig.prototype.hasWarnMessages = undefined;

/**
 * @member {Boolean} hasErrorMessages
 */
OperationStatusGBedrockTranscriptModelConfig.prototype.hasErrorMessages = undefined;

