/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.59
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import GeboTokenContent from './GeboTokenContent';

/**
 * The SecretWrapperGeboTokenContent model module.
 * @module model/SecretWrapperGeboTokenContent
 * @version v0
 */
export default class SecretWrapperGeboTokenContent {
  /**
   * Constructs a new <code>SecretWrapperGeboTokenContent</code>.
   * @alias module:model/SecretWrapperGeboTokenContent
   * @class
   * @param contextCode {String} 
   * @param description {String} 
   * @param secretContent {module:model/GeboTokenContent} 
   */
  constructor(contextCode, description, secretContent) {
    this.contextCode = contextCode;
    this.description = description;
    this.secretContent = secretContent;
  }

  /**
   * Constructs a <code>SecretWrapperGeboTokenContent</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SecretWrapperGeboTokenContent} obj Optional instance to populate.
   * @return {module:model/SecretWrapperGeboTokenContent} The populated <code>SecretWrapperGeboTokenContent</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SecretWrapperGeboTokenContent();
      if (data.hasOwnProperty('contextCode'))
        obj.contextCode = ApiClient.convertToType(data['contextCode'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('secretContent'))
        obj.secretContent = GeboTokenContent.constructFromObject(data['secretContent']);
    }
    return obj;
  }
}

/**
 * @member {String} contextCode
 */
SecretWrapperGeboTokenContent.prototype.contextCode = undefined;

/**
 * @member {String} description
 */
SecretWrapperGeboTokenContent.prototype.description = undefined;

/**
 * @member {module:model/GeboTokenContent} secretContent
 */
SecretWrapperGeboTokenContent.prototype.secretContent = undefined;

