/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.59
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The ComponentSetupStatus model module.
 * @module model/ComponentSetupStatus
 * @version v0
 */
export default class ComponentSetupStatus {
  /**
   * Constructs a new <code>ComponentSetupStatus</code>.
   * @alias module:model/ComponentSetupStatus
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ComponentSetupStatus</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ComponentSetupStatus} obj Optional instance to populate.
   * @return {module:model/ComponentSetupStatus} The populated <code>ComponentSetupStatus</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ComponentSetupStatus();
      if (data.hasOwnProperty('isSetup'))
        obj.isSetup = ApiClient.convertToType(data['isSetup'], Object);
    }
    return obj;
  }
}

/**
 * @member {Object} isSetup
 */
ComponentSetupStatus.prototype.isSetup = undefined;

