/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.59
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The ComponentLLMSStatus model module.
 * @module model/ComponentLLMSStatus
 * @version v0
 */
export default class ComponentLLMSStatus {
  /**
   * Constructs a new <code>ComponentLLMSStatus</code>.
   * @alias module:model/ComponentLLMSStatus
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ComponentLLMSStatus</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ComponentLLMSStatus} obj Optional instance to populate.
   * @return {module:model/ComponentLLMSStatus} The populated <code>ComponentLLMSStatus</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ComponentLLMSStatus();
      if (data.hasOwnProperty('isSetup'))
        obj.isSetup = ApiClient.convertToType(data['isSetup'], Object);
      if (data.hasOwnProperty('chatModelSetup'))
        obj.chatModelSetup = ApiClient.convertToType(data['chatModelSetup'], Object);
      if (data.hasOwnProperty('internalServicesChatModelSetup'))
        obj.internalServicesChatModelSetup = ApiClient.convertToType(data['internalServicesChatModelSetup'], Object);
      if (data.hasOwnProperty('embeddedModelSetup'))
        obj.embeddedModelSetup = ApiClient.convertToType(data['embeddedModelSetup'], Object);
      if (data.hasOwnProperty('rankingModelSetup'))
        obj.rankingModelSetup = ApiClient.convertToType(data['rankingModelSetup'], Object);
      if (data.hasOwnProperty('imagesModelSetup'))
        obj.imagesModelSetup = ApiClient.convertToType(data['imagesModelSetup'], Object);
      if (data.hasOwnProperty('ttsModelSetup'))
        obj.ttsModelSetup = ApiClient.convertToType(data['ttsModelSetup'], Object);
      if (data.hasOwnProperty('transcriptModelSetup'))
        obj.transcriptModelSetup = ApiClient.convertToType(data['transcriptModelSetup'], Object);
      if (data.hasOwnProperty('chatModelCode'))
        obj.chatModelCode = ApiClient.convertToType(data['chatModelCode'], Object);
      if (data.hasOwnProperty('internalServicesChatModelCode'))
        obj.internalServicesChatModelCode = ApiClient.convertToType(data['internalServicesChatModelCode'], Object);
      if (data.hasOwnProperty('embeddedModelCode'))
        obj.embeddedModelCode = ApiClient.convertToType(data['embeddedModelCode'], Object);
      if (data.hasOwnProperty('rankingModelCode'))
        obj.rankingModelCode = ApiClient.convertToType(data['rankingModelCode'], Object);
      if (data.hasOwnProperty('imagesModelCode'))
        obj.imagesModelCode = ApiClient.convertToType(data['imagesModelCode'], Object);
      if (data.hasOwnProperty('ttsModelCode'))
        obj.ttsModelCode = ApiClient.convertToType(data['ttsModelCode'], Object);
      if (data.hasOwnProperty('transcriptModelCode'))
        obj.transcriptModelCode = ApiClient.convertToType(data['transcriptModelCode'], Object);
      if (data.hasOwnProperty('chatModelProviderId'))
        obj.chatModelProviderId = ApiClient.convertToType(data['chatModelProviderId'], Object);
      if (data.hasOwnProperty('internalServicesChatModelProviderId'))
        obj.internalServicesChatModelProviderId = ApiClient.convertToType(data['internalServicesChatModelProviderId'], Object);
      if (data.hasOwnProperty('embeddedModelProviderId'))
        obj.embeddedModelProviderId = ApiClient.convertToType(data['embeddedModelProviderId'], Object);
      if (data.hasOwnProperty('rankingModelProviderId'))
        obj.rankingModelProviderId = ApiClient.convertToType(data['rankingModelProviderId'], Object);
      if (data.hasOwnProperty('imagesModelProviderId'))
        obj.imagesModelProviderId = ApiClient.convertToType(data['imagesModelProviderId'], Object);
      if (data.hasOwnProperty('ttsModelProviderId'))
        obj.ttsModelProviderId = ApiClient.convertToType(data['ttsModelProviderId'], Object);
      if (data.hasOwnProperty('transcriptModelProviderId'))
        obj.transcriptModelProviderId = ApiClient.convertToType(data['transcriptModelProviderId'], Object);
    }
    return obj;
  }
}

/**
 * @member {Object} isSetup
 */
ComponentLLMSStatus.prototype.isSetup = undefined;

/**
 * @member {Object} chatModelSetup
 */
ComponentLLMSStatus.prototype.chatModelSetup = undefined;

/**
 * @member {Object} internalServicesChatModelSetup
 */
ComponentLLMSStatus.prototype.internalServicesChatModelSetup = undefined;

/**
 * @member {Object} embeddedModelSetup
 */
ComponentLLMSStatus.prototype.embeddedModelSetup = undefined;

/**
 * @member {Object} rankingModelSetup
 */
ComponentLLMSStatus.prototype.rankingModelSetup = undefined;

/**
 * @member {Object} imagesModelSetup
 */
ComponentLLMSStatus.prototype.imagesModelSetup = undefined;

/**
 * @member {Object} ttsModelSetup
 */
ComponentLLMSStatus.prototype.ttsModelSetup = undefined;

/**
 * @member {Object} transcriptModelSetup
 */
ComponentLLMSStatus.prototype.transcriptModelSetup = undefined;

/**
 * @member {Object} chatModelCode
 */
ComponentLLMSStatus.prototype.chatModelCode = undefined;

/**
 * @member {Object} internalServicesChatModelCode
 */
ComponentLLMSStatus.prototype.internalServicesChatModelCode = undefined;

/**
 * @member {Object} embeddedModelCode
 */
ComponentLLMSStatus.prototype.embeddedModelCode = undefined;

/**
 * @member {Object} rankingModelCode
 */
ComponentLLMSStatus.prototype.rankingModelCode = undefined;

/**
 * @member {Object} imagesModelCode
 */
ComponentLLMSStatus.prototype.imagesModelCode = undefined;

/**
 * @member {Object} ttsModelCode
 */
ComponentLLMSStatus.prototype.ttsModelCode = undefined;

/**
 * @member {Object} transcriptModelCode
 */
ComponentLLMSStatus.prototype.transcriptModelCode = undefined;

/**
 * @member {Object} chatModelProviderId
 */
ComponentLLMSStatus.prototype.chatModelProviderId = undefined;

/**
 * @member {Object} internalServicesChatModelProviderId
 */
ComponentLLMSStatus.prototype.internalServicesChatModelProviderId = undefined;

/**
 * @member {Object} embeddedModelProviderId
 */
ComponentLLMSStatus.prototype.embeddedModelProviderId = undefined;

/**
 * @member {Object} rankingModelProviderId
 */
ComponentLLMSStatus.prototype.rankingModelProviderId = undefined;

/**
 * @member {Object} imagesModelProviderId
 */
ComponentLLMSStatus.prototype.imagesModelProviderId = undefined;

/**
 * @member {Object} ttsModelProviderId
 */
ComponentLLMSStatus.prototype.ttsModelProviderId = undefined;

/**
 * @member {Object} transcriptModelProviderId
 */
ComponentLLMSStatus.prototype.transcriptModelProviderId = undefined;

