/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.59
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import GBaseRankerModelChoice from './GBaseRankerModelChoice';

/**
 * The GBaseRankerModelConfig model module.
 * @module model/GBaseRankerModelConfig
 * @version v0
 */
export default class GBaseRankerModelConfig {
  /**
   * Constructs a new <code>GBaseRankerModelConfig</code>.
   * @alias module:model/GBaseRankerModelConfig
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GBaseRankerModelConfig</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GBaseRankerModelConfig} obj Optional instance to populate.
   * @return {module:model/GBaseRankerModelConfig} The populated <code>GBaseRankerModelConfig</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GBaseRankerModelConfig();
      if (data.hasOwnProperty('code'))
        obj.code = ApiClient.convertToType(data['code'], Object);
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], Object);
      if (data.hasOwnProperty('userModified'))
        obj.userModified = ApiClient.convertToType(data['userModified'], Object);
      if (data.hasOwnProperty('userCreated'))
        obj.userCreated = ApiClient.convertToType(data['userCreated'], Object);
      if (data.hasOwnProperty('dateModified'))
        obj.dateModified = ApiClient.convertToType(data['dateModified'], Object);
      if (data.hasOwnProperty('dateCreated'))
        obj.dateCreated = ApiClient.convertToType(data['dateCreated'], Object);
      if (data.hasOwnProperty('modelTypeCode'))
        obj.modelTypeCode = ApiClient.convertToType(data['modelTypeCode'], Object);
      if (data.hasOwnProperty('defaultModel'))
        obj.defaultModel = ApiClient.convertToType(data['defaultModel'], Object);
      if (data.hasOwnProperty('apiSecretCode'))
        obj.apiSecretCode = ApiClient.convertToType(data['apiSecretCode'], Object);
      if (data.hasOwnProperty('choosedModel'))
        obj.choosedModel = GBaseRankerModelChoice.constructFromObject(data['choosedModel']);
      if (data.hasOwnProperty('baseUrl'))
        obj.baseUrl = ApiClient.convertToType(data['baseUrl'], Object);
      if (data.hasOwnProperty('contextLength'))
        obj.contextLength = ApiClient.convertToType(data['contextLength'], Object);
      if (data.hasOwnProperty('maxDocumentsPerRequest'))
        obj.maxDocumentsPerRequest = ApiClient.convertToType(data['maxDocumentsPerRequest'], Object);
      if (data.hasOwnProperty('maxDocumentTokens'))
        obj.maxDocumentTokens = ApiClient.convertToType(data['maxDocumentTokens'], Object);
      if (data.hasOwnProperty('responseReserveTokens'))
        obj.responseReserveTokens = ApiClient.convertToType(data['responseReserveTokens'], Object);
      if (data.hasOwnProperty('fullServiceUrl'))
        obj.fullServiceUrl = ApiClient.convertToType(data['fullServiceUrl'], Object);
      if (data.hasOwnProperty('relativeServiceUrl'))
        obj.relativeServiceUrl = ApiClient.convertToType(data['relativeServiceUrl'], Object);
    }
    return obj;
  }
}

/**
 * @member {Object} code
 */
GBaseRankerModelConfig.prototype.code = undefined;

/**
 * @member {Object} description
 */
GBaseRankerModelConfig.prototype.description = undefined;

/**
 * @member {Object} userModified
 */
GBaseRankerModelConfig.prototype.userModified = undefined;

/**
 * @member {Object} userCreated
 */
GBaseRankerModelConfig.prototype.userCreated = undefined;

/**
 * @member {Object} dateModified
 */
GBaseRankerModelConfig.prototype.dateModified = undefined;

/**
 * @member {Object} dateCreated
 */
GBaseRankerModelConfig.prototype.dateCreated = undefined;

/**
 * @member {Object} modelTypeCode
 */
GBaseRankerModelConfig.prototype.modelTypeCode = undefined;

/**
 * @member {Object} defaultModel
 */
GBaseRankerModelConfig.prototype.defaultModel = undefined;

/**
 * @member {Object} apiSecretCode
 */
GBaseRankerModelConfig.prototype.apiSecretCode = undefined;

/**
 * @member {module:model/GBaseRankerModelChoice} choosedModel
 */
GBaseRankerModelConfig.prototype.choosedModel = undefined;

/**
 * @member {Object} baseUrl
 */
GBaseRankerModelConfig.prototype.baseUrl = undefined;

/**
 * @member {Object} contextLength
 */
GBaseRankerModelConfig.prototype.contextLength = undefined;

/**
 * @member {Object} maxDocumentsPerRequest
 */
GBaseRankerModelConfig.prototype.maxDocumentsPerRequest = undefined;

/**
 * @member {Object} maxDocumentTokens
 */
GBaseRankerModelConfig.prototype.maxDocumentTokens = undefined;

/**
 * @member {Object} responseReserveTokens
 */
GBaseRankerModelConfig.prototype.responseReserveTokens = undefined;

/**
 * @member {Object} fullServiceUrl
 */
GBaseRankerModelConfig.prototype.fullServiceUrl = undefined;

/**
 * @member {Object} relativeServiceUrl
 */
GBaseRankerModelConfig.prototype.relativeServiceUrl = undefined;

