/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.59
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import ModelMetaInfo from './ModelMetaInfo';

/**
 * The GOpenAIChatModelChoice model module.
 * @module model/GOpenAIChatModelChoice
 * @version v0
 */
export default class GOpenAIChatModelChoice {
  /**
   * Constructs a new <code>GOpenAIChatModelChoice</code>.
   * @alias module:model/GOpenAIChatModelChoice
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GOpenAIChatModelChoice</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GOpenAIChatModelChoice} obj Optional instance to populate.
   * @return {module:model/GOpenAIChatModelChoice} The populated <code>GOpenAIChatModelChoice</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GOpenAIChatModelChoice();
      if (data.hasOwnProperty('code'))
        obj.code = ApiClient.convertToType(data['code'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('userModified'))
        obj.userModified = ApiClient.convertToType(data['userModified'], 'String');
      if (data.hasOwnProperty('userCreated'))
        obj.userCreated = ApiClient.convertToType(data['userCreated'], 'String');
      if (data.hasOwnProperty('dateModified'))
        obj.dateModified = ApiClient.convertToType(data['dateModified'], 'Date');
      if (data.hasOwnProperty('dateCreated'))
        obj.dateCreated = ApiClient.convertToType(data['dateCreated'], 'Date');
      if (data.hasOwnProperty('creationDate'))
        obj.creationDate = ApiClient.convertToType(data['creationDate'], 'Date');
      if (data.hasOwnProperty('modificationDate'))
        obj.modificationDate = ApiClient.convertToType(data['modificationDate'], 'Date');
      if (data.hasOwnProperty('version'))
        obj.version = ApiClient.convertToType(data['version'], 'String');
      if (data.hasOwnProperty('metaInfos'))
        obj.metaInfos = ModelMetaInfo.constructFromObject(data['metaInfos']);
      if (data.hasOwnProperty('informativeUrl'))
        obj.informativeUrl = ApiClient.convertToType(data['informativeUrl'], 'String');
      if (data.hasOwnProperty('contextLength'))
        obj.contextLength = ApiClient.convertToType(data['contextLength'], 'Number');
      if (data.hasOwnProperty('nativeModelMetaInfos'))
        obj.nativeModelMetaInfos = ApiClient.convertToType(data['nativeModelMetaInfos'], Object);
      if (data.hasOwnProperty('supportsStructuredOutput'))
        obj.supportsStructuredOutput = ApiClient.convertToType(data['supportsStructuredOutput'], 'Boolean');
      if (data.hasOwnProperty('supportsFunctionCalls'))
        obj.supportsFunctionCalls = ApiClient.convertToType(data['supportsFunctionCalls'], 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {String} code
 */
GOpenAIChatModelChoice.prototype.code = undefined;

/**
 * @member {String} description
 */
GOpenAIChatModelChoice.prototype.description = undefined;

/**
 * @member {String} userModified
 */
GOpenAIChatModelChoice.prototype.userModified = undefined;

/**
 * @member {String} userCreated
 */
GOpenAIChatModelChoice.prototype.userCreated = undefined;

/**
 * @member {Date} dateModified
 */
GOpenAIChatModelChoice.prototype.dateModified = undefined;

/**
 * @member {Date} dateCreated
 */
GOpenAIChatModelChoice.prototype.dateCreated = undefined;

/**
 * @member {Date} creationDate
 */
GOpenAIChatModelChoice.prototype.creationDate = undefined;

/**
 * @member {Date} modificationDate
 */
GOpenAIChatModelChoice.prototype.modificationDate = undefined;

/**
 * @member {String} version
 */
GOpenAIChatModelChoice.prototype.version = undefined;

/**
 * @member {module:model/ModelMetaInfo} metaInfos
 */
GOpenAIChatModelChoice.prototype.metaInfos = undefined;

/**
 * @member {String} informativeUrl
 */
GOpenAIChatModelChoice.prototype.informativeUrl = undefined;

/**
 * @member {Number} contextLength
 */
GOpenAIChatModelChoice.prototype.contextLength = undefined;

/**
 * @member {Object} nativeModelMetaInfos
 */
GOpenAIChatModelChoice.prototype.nativeModelMetaInfos = undefined;

/**
 * @member {Boolean} supportsStructuredOutput
 */
GOpenAIChatModelChoice.prototype.supportsStructuredOutput = undefined;

/**
 * @member {Boolean} supportsFunctionCalls
 */
GOpenAIChatModelChoice.prototype.supportsFunctionCalls = undefined;

