/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.59
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import MistralModelCapabilities from './MistralModelCapabilities';

/**
 * The MistralBaseModelCard model module.
 * @module model/MistralBaseModelCard
 * @version v0
 */
export default class MistralBaseModelCard {
  /**
   * Constructs a new <code>MistralBaseModelCard</code>.
   * @alias module:model/MistralBaseModelCard
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>MistralBaseModelCard</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MistralBaseModelCard} obj Optional instance to populate.
   * @return {module:model/MistralBaseModelCard} The populated <code>MistralBaseModelCard</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new MistralBaseModelCard();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('capabilities'))
        obj.capabilities = MistralModelCapabilities.constructFromObject(data['capabilities']);
      if (data.hasOwnProperty('job'))
        obj.job = ApiClient.convertToType(data['job'], 'String');
      if (data.hasOwnProperty('root'))
        obj.root = ApiClient.convertToType(data['root'], 'String');
      if (data.hasOwnProperty('object'))
        obj._object = ApiClient.convertToType(data['object'], 'String');
      if (data.hasOwnProperty('created'))
        obj.created = ApiClient.convertToType(data['created'], 'Number');
      if (data.hasOwnProperty('owned_by'))
        obj.ownedBy = ApiClient.convertToType(data['owned_by'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('max_context_length'))
        obj.maxContextLength = ApiClient.convertToType(data['max_context_length'], 'Number');
      if (data.hasOwnProperty('aliases'))
        obj.aliases = ApiClient.convertToType(data['aliases'], ['String']);
      if (data.hasOwnProperty('deprecation'))
        obj.deprecation = ApiClient.convertToType(data['deprecation'], 'String');
      if (data.hasOwnProperty('deprecation_replacement_model'))
        obj.deprecationReplacementModel = ApiClient.convertToType(data['deprecation_replacement_model'], 'String');
      if (data.hasOwnProperty('default_model_temperature'))
        obj.defaultModelTemperature = ApiClient.convertToType(data['default_model_temperature'], 'Number');
      if (data.hasOwnProperty('archived'))
        obj.archived = ApiClient.convertToType(data['archived'], 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
MistralBaseModelCard.prototype.id = undefined;

/**
 * @member {module:model/MistralModelCapabilities} capabilities
 */
MistralBaseModelCard.prototype.capabilities = undefined;

/**
 * @member {String} job
 */
MistralBaseModelCard.prototype.job = undefined;

/**
 * @member {String} root
 */
MistralBaseModelCard.prototype.root = undefined;

/**
 * @member {String} _object
 */
MistralBaseModelCard.prototype._object = undefined;

/**
 * @member {Number} created
 */
MistralBaseModelCard.prototype.created = undefined;

/**
 * @member {String} ownedBy
 */
MistralBaseModelCard.prototype.ownedBy = undefined;

/**
 * @member {String} name
 */
MistralBaseModelCard.prototype.name = undefined;

/**
 * @member {String} description
 */
MistralBaseModelCard.prototype.description = undefined;

/**
 * @member {Number} maxContextLength
 */
MistralBaseModelCard.prototype.maxContextLength = undefined;

/**
 * @member {Array.<String>} aliases
 */
MistralBaseModelCard.prototype.aliases = undefined;

/**
 * @member {String} deprecation
 */
MistralBaseModelCard.prototype.deprecation = undefined;

/**
 * @member {String} deprecationReplacementModel
 */
MistralBaseModelCard.prototype.deprecationReplacementModel = undefined;

/**
 * @member {Number} defaultModelTemperature
 */
MistralBaseModelCard.prototype.defaultModelTemperature = undefined;

/**
 * @member {Boolean} archived
 */
MistralBaseModelCard.prototype.archived = undefined;

