/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.59
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from "../ApiClient";
import GenericOpenAIAPIRankerModelConfig from '../model/GenericOpenAIAPIRankerModelConfig';
import GenericOpenAIRankerModelTypeConfig from '../model/GenericOpenAIRankerModelTypeConfig';
import OperationStatusBoolean from '../model/OperationStatusBoolean';
import OperationStatusGenericOpenAIAPIRankerModelConfig from '../model/OperationStatusGenericOpenAIAPIRankerModelConfig';
import OperationStatusListGenericOpenAIAPIRankerModelChoice from '../model/OperationStatusListGenericOpenAIAPIRankerModelChoice';

/**
* GenericOpenAiRankerModelsConfigurationController service.
* @module api/GenericOpenAiRankerModelsConfigurationControllerApi
* @version v0
*/
export default class GenericOpenAiRankerModelsConfigurationControllerApi {

    /**
    * Constructs a new GenericOpenAiRankerModelsConfigurationControllerApi. 
    * @alias module:api/GenericOpenAiRankerModelsConfigurationControllerApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * @param {module:model/GenericOpenAIAPIRankerModelConfig} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/OperationStatusBoolean} and HTTP response
     */
    deleteGenericOpenAIAPIRankerModelConfigWithHttpInfo(body) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling deleteGenericOpenAIAPIRankerModelConfig");
      }

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = OperationStatusBoolean;

      return this.apiClient.callApi(
        '/api/admin/GenerigOpenAIRankerModelsConfigurationController/deleteGenericOpenAIAPIRankerModelConfig', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * @param {<&vendorExtensions.x-jsdoc-type>} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/OperationStatusBoolean}
     */
    deleteGenericOpenAIAPIRankerModelConfig(body) {
      return this.deleteGenericOpenAIAPIRankerModelConfigWithHttpInfo(body)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * @param {String} code 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/GenericOpenAIAPIRankerModelConfig} and HTTP response
     */
    findGenericOpenAIAPIRankerModelConfigByCodeWithHttpInfo(code) {
      
      let postBody = null;
      // verify the required parameter 'code' is set
      if (code === undefined || code === null) {
        throw new Error("Missing the required parameter 'code' when calling findGenericOpenAIAPIRankerModelConfigByCode");
      }

      let pathParams = {
        
      };
      let queryParams = {
        'code': code
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GenericOpenAIAPIRankerModelConfig;

      return this.apiClient.callApi(
        '/api/admin/GenerigOpenAIRankerModelsConfigurationController/findGenericOpenAIAPIRankerModelConfigByCode', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * @param {<&vendorExtensions.x-jsdoc-type>} code 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/GenericOpenAIAPIRankerModelConfig}
     */
    findGenericOpenAIAPIRankerModelConfigByCode(code) {
      return this.findGenericOpenAIAPIRankerModelConfigByCodeWithHttpInfo(code)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * @param {module:model/GenericOpenAIAPIRankerModelConfig} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/OperationStatusListGenericOpenAIAPIRankerModelChoice} and HTTP response
     */
    getGenericOpenAIAPIRankerModelsWithHttpInfo(body) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling getGenericOpenAIAPIRankerModels");
      }

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = OperationStatusListGenericOpenAIAPIRankerModelChoice;

      return this.apiClient.callApi(
        '/api/admin/GenerigOpenAIRankerModelsConfigurationController/getGenericOpenAIAPIRankerModels', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * @param {<&vendorExtensions.x-jsdoc-type>} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/OperationStatusListGenericOpenAIAPIRankerModelChoice}
     */
    getGenericOpenAIAPIRankerModels(body) {
      return this.getGenericOpenAIAPIRankerModelsWithHttpInfo(body)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/GenericOpenAIAPIRankerModelConfig>} and HTTP response
     */
    getGenericOpenAIRankerModelConfigsWithHttpInfo() {
      
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [GenericOpenAIAPIRankerModelConfig];

      return this.apiClient.callApi(
        '/api/admin/GenerigOpenAIRankerModelsConfigurationController/getGenericOpenAIRankerModelConfigs', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/GenericOpenAIAPIRankerModelConfig>}
     */
    getGenericOpenAIRankerModelConfigs() {
      return this.getGenericOpenAIRankerModelConfigsWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/GenericOpenAIRankerModelTypeConfig>} and HTTP response
     */
    getGenericOpenAIRankerModelTypesWithHttpInfo() {
      
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [GenericOpenAIRankerModelTypeConfig];

      return this.apiClient.callApi(
        '/api/admin/GenerigOpenAIRankerModelsConfigurationController/getGenericOpenAIRankerModelTypes', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/GenericOpenAIRankerModelTypeConfig>}
     */
    getGenericOpenAIRankerModelTypes() {
      return this.getGenericOpenAIRankerModelTypesWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * @param {module:model/GenericOpenAIAPIRankerModelConfig} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/OperationStatusGenericOpenAIAPIRankerModelConfig} and HTTP response
     */
    insertGenericOpenAIAPIRankerModelConfigWithHttpInfo(body) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling insertGenericOpenAIAPIRankerModelConfig");
      }

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = OperationStatusGenericOpenAIAPIRankerModelConfig;

      return this.apiClient.callApi(
        '/api/admin/GenerigOpenAIRankerModelsConfigurationController/insertGenericOpenAIAPIRankerModelConfig', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * @param {<&vendorExtensions.x-jsdoc-type>} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/OperationStatusGenericOpenAIAPIRankerModelConfig}
     */
    insertGenericOpenAIAPIRankerModelConfig(body) {
      return this.insertGenericOpenAIAPIRankerModelConfigWithHttpInfo(body)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * @param {module:model/GenericOpenAIAPIRankerModelConfig} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/OperationStatusGenericOpenAIAPIRankerModelConfig} and HTTP response
     */
    updateGenericOpenAIAPIRankerModelConfigWithHttpInfo(body) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling updateGenericOpenAIAPIRankerModelConfig");
      }

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = OperationStatusGenericOpenAIAPIRankerModelConfig;

      return this.apiClient.callApi(
        '/api/admin/GenerigOpenAIRankerModelsConfigurationController/updateGenericOpenAIAPIRankerModelConfig', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * @param {<&vendorExtensions.x-jsdoc-type>} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/OperationStatusGenericOpenAIAPIRankerModelConfig}
     */
    updateGenericOpenAIAPIRankerModelConfig(body) {
      return this.updateGenericOpenAIAPIRankerModelConfigWithHttpInfo(body)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }

}