/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.59
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GeboAiClient);
  }
}(this, function(expect, GeboAiClient) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('GKnowledgeBase', function() {
      beforeEach(function() {
        instance = new GeboAiClient.GKnowledgeBase();
      });

      it('should create an instance of GKnowledgeBase', function() {
        // TODO: update the code to test GKnowledgeBase
        expect(instance).to.be.a(GeboAiClient.GKnowledgeBase);
      });

      it('should have the property code (base name: "code")', function() {
        // TODO: update the code to test the property code
        expect(instance).to.have.property('code');
        // expect(instance.code).to.be(expectedValueLiteral);
      });

      it('should have the property description (base name: "description")', function() {
        // TODO: update the code to test the property description
        expect(instance).to.have.property('description');
        // expect(instance.description).to.be(expectedValueLiteral);
      });

      it('should have the property userModified (base name: "userModified")', function() {
        // TODO: update the code to test the property userModified
        expect(instance).to.have.property('userModified');
        // expect(instance.userModified).to.be(expectedValueLiteral);
      });

      it('should have the property userCreated (base name: "userCreated")', function() {
        // TODO: update the code to test the property userCreated
        expect(instance).to.have.property('userCreated');
        // expect(instance.userCreated).to.be(expectedValueLiteral);
      });

      it('should have the property dateModified (base name: "dateModified")', function() {
        // TODO: update the code to test the property dateModified
        expect(instance).to.have.property('dateModified');
        // expect(instance.dateModified).to.be(expectedValueLiteral);
      });

      it('should have the property dateCreated (base name: "dateCreated")', function() {
        // TODO: update the code to test the property dateCreated
        expect(instance).to.have.property('dateCreated');
        // expect(instance.dateCreated).to.be(expectedValueLiteral);
      });

      it('should have the property accessibleGroups (base name: "accessibleGroups")', function() {
        // TODO: update the code to test the property accessibleGroups
        expect(instance).to.have.property('accessibleGroups');
        // expect(instance.accessibleGroups).to.be(expectedValueLiteral);
      });

      it('should have the property accessibleUsers (base name: "accessibleUsers")', function() {
        // TODO: update the code to test the property accessibleUsers
        expect(instance).to.have.property('accessibleUsers');
        // expect(instance.accessibleUsers).to.be(expectedValueLiteral);
      });

      it('should have the property accessibleToAll (base name: "accessibleToAll")', function() {
        // TODO: update the code to test the property accessibleToAll
        expect(instance).to.have.property('accessibleToAll');
        // expect(instance.accessibleToAll).to.be(expectedValueLiteral);
      });

      it('should have the property knowledgeBaseReferences (base name: "knowledgeBaseReferences")', function() {
        // TODO: update the code to test the property knowledgeBaseReferences
        expect(instance).to.have.property('knowledgeBaseReferences');
        // expect(instance.knowledgeBaseReferences).to.be(expectedValueLiteral);
      });

      it('should have the property projectsReferences (base name: "projectsReferences")', function() {
        // TODO: update the code to test the property projectsReferences
        expect(instance).to.have.property('projectsReferences');
        // expect(instance.projectsReferences).to.be(expectedValueLiteral);
      });

      it('should have the property embeddingModelReferences (base name: "embeddingModelReferences")', function() {
        // TODO: update the code to test the property embeddingModelReferences
        expect(instance).to.have.property('embeddingModelReferences');
        // expect(instance.embeddingModelReferences).to.be(expectedValueLiteral);
      });

      it('should have the property username (base name: "username")', function() {
        // TODO: update the code to test the property username
        expect(instance).to.have.property('username');
        // expect(instance.username).to.be(expectedValueLiteral);
      });

      it('should have the property parentKnowledgebaseCode (base name: "parentKnowledgebaseCode")', function() {
        // TODO: update the code to test the property parentKnowledgebaseCode
        expect(instance).to.have.property('parentKnowledgebaseCode');
        // expect(instance.parentKnowledgebaseCode).to.be(expectedValueLiteral);
      });

      it('should have the property objectSpaceType (base name: "objectSpaceType")', function() {
        // TODO: update the code to test the property objectSpaceType
        expect(instance).to.have.property('objectSpaceType');
        // expect(instance.objectSpaceType).to.be(expectedValueLiteral);
      });

      it('should have the property acl (base name: "acl")', function() {
        // TODO: update the code to test the property acl
        expect(instance).to.have.property('acl');
        // expect(instance.acl).to.be(expectedValueLiteral);
      });

      it('should have the property aclAliases (base name: "aclAliases")', function() {
        // TODO: update the code to test the property aclAliases
        expect(instance).to.have.property('aclAliases');
        // expect(instance.aclAliases).to.be(expectedValueLiteral);
      });

    });
  });

}));
