/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.59
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GeboAiClient);
  }
}(this, function(expect, GeboAiClient) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('PagedModelDocumentReferenceView', function() {
      beforeEach(function() {
        instance = new GeboAiClient.PagedModelDocumentReferenceView();
      });

      it('should create an instance of PagedModelDocumentReferenceView', function() {
        // TODO: update the code to test PagedModelDocumentReferenceView
        expect(instance).to.be.a(GeboAiClient.PagedModelDocumentReferenceView);
      });

      it('should have the property content (base name: "content")', function() {
        // TODO: update the code to test the property content
        expect(instance).to.have.property('content');
        // expect(instance.content).to.be(expectedValueLiteral);
      });

      it('should have the property page (base name: "page")', function() {
        // TODO: update the code to test the property page
        expect(instance).to.have.property('page');
        // expect(instance.page).to.be(expectedValueLiteral);
      });

    });
  });

}));
