/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.59
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GeboAiClient);
  }
}(this, function(expect, GeboAiClient) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('ReindexTimeStructureMetaInfo', function() {
      beforeEach(function() {
        instance = new GeboAiClient.ReindexTimeStructureMetaInfo();
      });

      it('should create an instance of ReindexTimeStructureMetaInfo', function() {
        // TODO: update the code to test ReindexTimeStructureMetaInfo
        expect(instance).to.be.a(GeboAiClient.ReindexTimeStructureMetaInfo);
      });

      it('should have the property frequency (base name: "frequency")', function() {
        // TODO: update the code to test the property frequency
        expect(instance).to.have.property('frequency');
        // expect(instance.frequency).to.be(expectedValueLiteral);
      });

      it('should have the property periodComponents (base name: "periodComponents")', function() {
        // TODO: update the code to test the property periodComponents
        expect(instance).to.have.property('periodComponents');
        // expect(instance.periodComponents).to.be(expectedValueLiteral);
      });

    });
  });

}));
