/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.59
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GeboAiClient);
  }
}(this, function(expect, GeboAiClient) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('SecretWrapperGeboOauth2SecretContent', function() {
      beforeEach(function() {
        instance = new GeboAiClient.SecretWrapperGeboOauth2SecretContent();
      });

      it('should create an instance of SecretWrapperGeboOauth2SecretContent', function() {
        // TODO: update the code to test SecretWrapperGeboOauth2SecretContent
        expect(instance).to.be.a(GeboAiClient.SecretWrapperGeboOauth2SecretContent);
      });

      it('should have the property contextCode (base name: "contextCode")', function() {
        // TODO: update the code to test the property contextCode
        expect(instance).to.have.property('contextCode');
        // expect(instance.contextCode).to.be(expectedValueLiteral);
      });

      it('should have the property description (base name: "description")', function() {
        // TODO: update the code to test the property description
        expect(instance).to.have.property('description');
        // expect(instance.description).to.be(expectedValueLiteral);
      });

      it('should have the property secretContent (base name: "secretContent")', function() {
        // TODO: update the code to test the property secretContent
        expect(instance).to.have.property('secretContent');
        // expect(instance.secretContent).to.be(expectedValueLiteral);
      });

    });
  });

}));
