/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.59
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from "../ApiClient";
import BrowseParam from '../model/BrowseParam';
import OperationStatusListGVirtualFilesystemRoot from '../model/OperationStatusListGVirtualFilesystemRoot';
import OperationStatusListPathInfo from '../model/OperationStatusListPathInfo';
import OperationStatusListVirtualFilesystemNavigationTreeStatus from '../model/OperationStatusListVirtualFilesystemNavigationTreeStatus';
import VFilesystemReference from '../model/VFilesystemReference';

/**
* JiraBrowsingController service.
* @module api/JiraBrowsingControllerApi
* @version v0
*/
export default class JiraBrowsingControllerApi {

    /**
    * Constructs a new JiraBrowsingControllerApi. 
    * @alias module:api/JiraBrowsingControllerApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * @param {module:model/BrowseParam} body 
     * @param {String} systemCode 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/OperationStatusListPathInfo} and HTTP response
     */
    browseJiraPathWithHttpInfo(body, systemCode) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling browseJiraPath");
      }
      // verify the required parameter 'systemCode' is set
      if (systemCode === undefined || systemCode === null) {
        throw new Error("Missing the required parameter 'systemCode' when calling browseJiraPath");
      }

      let pathParams = {
        
      };
      let queryParams = {
        'systemCode': systemCode
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = OperationStatusListPathInfo;

      return this.apiClient.callApi(
        '/api/admin/JiraBrowsingController/browseJiraPath', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * @param {<&vendorExtensions.x-jsdoc-type>} body 
     * @param {<&vendorExtensions.x-jsdoc-type>} systemCode 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/OperationStatusListPathInfo}
     */
    browseJiraPath(body, systemCode) {
      return this.browseJiraPathWithHttpInfo(body, systemCode)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * @param {Array.<module:model/VFilesystemReference>} body 
     * @param {String} systemCode 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/OperationStatusListVirtualFilesystemNavigationTreeStatus} and HTTP response
     */
    getJiraNavigationStatusWithHttpInfo(body, systemCode) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling getJiraNavigationStatus");
      }
      // verify the required parameter 'systemCode' is set
      if (systemCode === undefined || systemCode === null) {
        throw new Error("Missing the required parameter 'systemCode' when calling getJiraNavigationStatus");
      }

      let pathParams = {
        
      };
      let queryParams = {
        'systemCode': systemCode
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = OperationStatusListVirtualFilesystemNavigationTreeStatus;

      return this.apiClient.callApi(
        '/api/admin/JiraBrowsingController/getJiraNavigationStatus', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * @param {<&vendorExtensions.x-jsdoc-type>} body 
     * @param {<&vendorExtensions.x-jsdoc-type>} systemCode 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/OperationStatusListVirtualFilesystemNavigationTreeStatus}
     */
    getJiraNavigationStatus(body, systemCode) {
      return this.getJiraNavigationStatusWithHttpInfo(body, systemCode)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * @param {String} systemCode 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/OperationStatusListGVirtualFilesystemRoot} and HTTP response
     */
    getJiraRootsWithHttpInfo(systemCode) {
      
      let postBody = null;
      // verify the required parameter 'systemCode' is set
      if (systemCode === undefined || systemCode === null) {
        throw new Error("Missing the required parameter 'systemCode' when calling getJiraRoots");
      }

      let pathParams = {
        
      };
      let queryParams = {
        'systemCode': systemCode
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = OperationStatusListGVirtualFilesystemRoot;

      return this.apiClient.callApi(
        '/api/admin/JiraBrowsingController/getJiraRoots', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * @param {<&vendorExtensions.x-jsdoc-type>} systemCode 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/OperationStatusListGVirtualFilesystemRoot}
     */
    getJiraRoots(systemCode) {
      return this.getJiraRootsWithHttpInfo(systemCode)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }

}