/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.59
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from "../ApiClient";
import FastWebdavSystemInsertRequest from '../model/FastWebdavSystemInsertRequest';
import GContentManagementSystemType from '../model/GContentManagementSystemType';
import GWebdavContentManagementSystem from '../model/GWebdavContentManagementSystem';
import GWebdavProjectEndpoint from '../model/GWebdavProjectEndpoint';
import OperationStatusGJobStatus from '../model/OperationStatusGJobStatus';
import OperationStatusGWebdavContentManagementSystem from '../model/OperationStatusGWebdavContentManagementSystem';

/**
* WebdavSystemsController service.
* @module api/WebdavSystemsControllerApi
* @version v0
*/
export default class WebdavSystemsControllerApi {

    /**
    * Constructs a new WebdavSystemsControllerApi. 
    * @alias module:api/WebdavSystemsControllerApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * @param {module:model/GWebdavProjectEndpoint} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    deleteWebdavEndpointWithHttpInfo(body) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling deleteWebdavEndpoint");
      }

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = [];
      let returnType = null;

      return this.apiClient.callApi(
        '/api/admin/WebdavSystemsController/deleteWebdavEndpoint', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * @param {<&vendorExtensions.x-jsdoc-type>} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    deleteWebdavEndpoint(body) {
      return this.deleteWebdavEndpointWithHttpInfo(body)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * @param {module:model/GWebdavContentManagementSystem} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    deleteWebdavSystemWithHttpInfo(body) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling deleteWebdavSystem");
      }

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = [];
      let returnType = null;

      return this.apiClient.callApi(
        '/api/admin/WebdavSystemsController/deleteWebdavSystem', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * @param {<&vendorExtensions.x-jsdoc-type>} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    deleteWebdavSystem(body) {
      return this.deleteWebdavSystemWithHttpInfo(body)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * @param {module:model/FastWebdavSystemInsertRequest} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/OperationStatusGWebdavContentManagementSystem} and HTTP response
     */
    fastWebdavConfigWithHttpInfo(body) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling fastWebdavConfig");
      }

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = OperationStatusGWebdavContentManagementSystem;

      return this.apiClient.callApi(
        '/api/admin/WebdavSystemsController/fastWebdavConfig', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * @param {<&vendorExtensions.x-jsdoc-type>} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/OperationStatusGWebdavContentManagementSystem}
     */
    fastWebdavConfig(body) {
      return this.fastWebdavConfigWithHttpInfo(body)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * @param {String} code 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/GWebdavProjectEndpoint} and HTTP response
     */
    findWebdavEndpointsByCodeWithHttpInfo(code) {
      
      let postBody = null;
      // verify the required parameter 'code' is set
      if (code === undefined || code === null) {
        throw new Error("Missing the required parameter 'code' when calling findWebdavEndpointsByCode");
      }

      let pathParams = {
        
      };
      let queryParams = {
        'code': code
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = GWebdavProjectEndpoint;

      return this.apiClient.callApi(
        '/api/admin/WebdavSystemsController/findWebdavEndpointsByCode', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * @param {<&vendorExtensions.x-jsdoc-type>} code 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/GWebdavProjectEndpoint}
     */
    findWebdavEndpointsByCode(code) {
      return this.findWebdavEndpointsByCodeWithHttpInfo(code)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * @param {String} parentProjectCode 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/GWebdavProjectEndpoint>} and HTTP response
     */
    findWebdavEndpointsByProjectWithHttpInfo(parentProjectCode) {
      
      let postBody = null;
      // verify the required parameter 'parentProjectCode' is set
      if (parentProjectCode === undefined || parentProjectCode === null) {
        throw new Error("Missing the required parameter 'parentProjectCode' when calling findWebdavEndpointsByProject");
      }

      let pathParams = {
        
      };
      let queryParams = {
        'parentProjectCode': parentProjectCode
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = [GWebdavProjectEndpoint];

      return this.apiClient.callApi(
        '/api/admin/WebdavSystemsController/findWebdavEndpointsByProject', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * @param {<&vendorExtensions.x-jsdoc-type>} parentProjectCode 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/GWebdavProjectEndpoint>}
     */
    findWebdavEndpointsByProject(parentProjectCode) {
      return this.findWebdavEndpointsByProjectWithHttpInfo(parentProjectCode)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * @param {module:model/GWebdavProjectEndpoint} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/GWebdavProjectEndpoint>} and HTTP response
     */
    findWebdavEndpointsByQbeWithHttpInfo(body) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling findWebdavEndpointsByQbe");
      }

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = [GWebdavProjectEndpoint];

      return this.apiClient.callApi(
        '/api/admin/WebdavSystemsController/findWebdavEndpointsByQbe', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * @param {<&vendorExtensions.x-jsdoc-type>} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/GWebdavProjectEndpoint>}
     */
    findWebdavEndpointsByQbe(body) {
      return this.findWebdavEndpointsByQbeWithHttpInfo(body)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * @param {String} code 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/GWebdavContentManagementSystem} and HTTP response
     */
    findWebdavSystemByCodeWithHttpInfo(code) {
      
      let postBody = null;
      // verify the required parameter 'code' is set
      if (code === undefined || code === null) {
        throw new Error("Missing the required parameter 'code' when calling findWebdavSystemByCode");
      }

      let pathParams = {
        
      };
      let queryParams = {
        'code': code
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = GWebdavContentManagementSystem;

      return this.apiClient.callApi(
        '/api/admin/WebdavSystemsController/findWebdavSystemByCode', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * @param {<&vendorExtensions.x-jsdoc-type>} code 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/GWebdavContentManagementSystem}
     */
    findWebdavSystemByCode(code) {
      return this.findWebdavSystemByCodeWithHttpInfo(code)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/GContentManagementSystemType} and HTTP response
     */
    getWebdavSystemTypesWithHttpInfo() {
      
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GContentManagementSystemType;

      return this.apiClient.callApi(
        '/api/admin/WebdavSystemsController/getWebdavSystemType', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/GContentManagementSystemType}
     */
    getWebdavSystemTypes() {
      return this.getWebdavSystemTypesWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/GWebdavContentManagementSystem>} and HTTP response
     */
    getWebdavSystemsWithHttpInfo() {
      
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = [GWebdavContentManagementSystem];

      return this.apiClient.callApi(
        '/api/admin/WebdavSystemsController/getWebdavSystems', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/GWebdavContentManagementSystem>}
     */
    getWebdavSystems() {
      return this.getWebdavSystemsWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * @param {module:model/GWebdavProjectEndpoint} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/GWebdavProjectEndpoint} and HTTP response
     */
    insertWebdavEndpointWithHttpInfo(body) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling insertWebdavEndpoint");
      }

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = GWebdavProjectEndpoint;

      return this.apiClient.callApi(
        '/api/admin/WebdavSystemsController/insertWebdavEndpoint', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * @param {<&vendorExtensions.x-jsdoc-type>} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/GWebdavProjectEndpoint}
     */
    insertWebdavEndpoint(body) {
      return this.insertWebdavEndpointWithHttpInfo(body)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * @param {module:model/GWebdavContentManagementSystem} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/OperationStatusGWebdavContentManagementSystem} and HTTP response
     */
    insertWebdavSystemWithHttpInfo(body) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling insertWebdavSystem");
      }

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = OperationStatusGWebdavContentManagementSystem;

      return this.apiClient.callApi(
        '/api/admin/WebdavSystemsController/insertWebdavSystem', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * @param {<&vendorExtensions.x-jsdoc-type>} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/OperationStatusGWebdavContentManagementSystem}
     */
    insertWebdavSystem(body) {
      return this.insertWebdavSystemWithHttpInfo(body)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * @param {module:model/GWebdavProjectEndpoint} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/OperationStatusGJobStatus} and HTTP response
     */
    publishWebdavEndpointWithHttpInfo(body) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling publishWebdavEndpoint");
      }

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = OperationStatusGJobStatus;

      return this.apiClient.callApi(
        '/api/admin/WebdavSystemsController/publishWebdavEndpoint', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * @param {<&vendorExtensions.x-jsdoc-type>} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/OperationStatusGJobStatus}
     */
    publishWebdavEndpoint(body) {
      return this.publishWebdavEndpointWithHttpInfo(body)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * @param {module:model/GWebdavContentManagementSystem} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/OperationStatusGWebdavContentManagementSystem} and HTTP response
     */
    testWebdavSystemWithHttpInfo(body) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling testWebdavSystem");
      }

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = OperationStatusGWebdavContentManagementSystem;

      return this.apiClient.callApi(
        '/api/admin/WebdavSystemsController/testWebdavSystem', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * @param {<&vendorExtensions.x-jsdoc-type>} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/OperationStatusGWebdavContentManagementSystem}
     */
    testWebdavSystem(body) {
      return this.testWebdavSystemWithHttpInfo(body)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * @param {module:model/GWebdavProjectEndpoint} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/GWebdavProjectEndpoint} and HTTP response
     */
    updateWebdavEndpointWithHttpInfo(body) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling updateWebdavEndpoint");
      }

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = GWebdavProjectEndpoint;

      return this.apiClient.callApi(
        '/api/admin/WebdavSystemsController/updateWebdavEndpoint', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * @param {<&vendorExtensions.x-jsdoc-type>} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/GWebdavProjectEndpoint}
     */
    updateWebdavEndpoint(body) {
      return this.updateWebdavEndpointWithHttpInfo(body)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * @param {module:model/GWebdavContentManagementSystem} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/OperationStatusGWebdavContentManagementSystem} and HTTP response
     */
    updateWebdavSystemWithHttpInfo(body) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling updateWebdavSystem");
      }

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = OperationStatusGWebdavContentManagementSystem;

      return this.apiClient.callApi(
        '/api/admin/WebdavSystemsController/updateWebdavSystem', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * @param {<&vendorExtensions.x-jsdoc-type>} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/OperationStatusGWebdavContentManagementSystem}
     */
    updateWebdavSystem(body) {
      return this.updateWebdavSystemWithHttpInfo(body)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }

}