/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package gebo.microservices.api.client.userspace.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import gebo.microservices.api.client.userspace.model.GObjectRefGProjectEndpoint;
import gebo.microservices.api.client.userspace.model.WorkflowStatus;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * GJobStatus
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-07-29T09:44:00.182052971+02:00[Europe/Rome]")

public class GJobStatus {
  @JsonProperty("code")
  private Object code = null;

  @JsonProperty("description")
  private Object description = null;

  @JsonProperty("userModified")
  private Object userModified = null;

  @JsonProperty("userCreated")
  private Object userCreated = null;

  @JsonProperty("dateModified")
  private Object dateModified = null;

  @JsonProperty("dateCreated")
  private Object dateCreated = null;

  @JsonProperty("jobType")
  private Object jobType = null;

  @JsonProperty("workflowType")
  private Object workflowType = null;

  @JsonProperty("workflowId")
  private Object workflowId = null;

  @JsonProperty("processing")
  private Object processing = null;

  @JsonProperty("finished")
  private Object finished = null;

  @JsonProperty("error")
  private Object error = null;

  @JsonProperty("startDateTime")
  private Object startDateTime = null;

  @JsonProperty("endDateTime")
  private Object endDateTime = null;

  @JsonProperty("projectEndpointReference")
  private GObjectRefGProjectEndpoint projectEndpointReference = null;

  @JsonProperty("knowledgeBaseCode")
  private Object knowledgeBaseCode = null;

  @JsonProperty("projectCode")
  private Object projectCode = null;

  @JsonProperty("parentJobCode")
  private Object parentJobCode = null;

  @JsonProperty("workflowStatus")
  private WorkflowStatus workflowStatus = null;

  public GJobStatus code(Object code) {
    this.code = code;
    return this;
  }

   /**
   * Get code
   * @return code
  **/
  @Schema(description = "")
  public Object getCode() {
    return code;
  }

  public void setCode(Object code) {
    this.code = code;
  }

  public GJobStatus description(Object description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @Schema(description = "")
  public Object getDescription() {
    return description;
  }

  public void setDescription(Object description) {
    this.description = description;
  }

  public GJobStatus userModified(Object userModified) {
    this.userModified = userModified;
    return this;
  }

   /**
   * Get userModified
   * @return userModified
  **/
  @Schema(description = "")
  public Object getUserModified() {
    return userModified;
  }

  public void setUserModified(Object userModified) {
    this.userModified = userModified;
  }

  public GJobStatus userCreated(Object userCreated) {
    this.userCreated = userCreated;
    return this;
  }

   /**
   * Get userCreated
   * @return userCreated
  **/
  @Schema(description = "")
  public Object getUserCreated() {
    return userCreated;
  }

  public void setUserCreated(Object userCreated) {
    this.userCreated = userCreated;
  }

  public GJobStatus dateModified(Object dateModified) {
    this.dateModified = dateModified;
    return this;
  }

   /**
   * Get dateModified
   * @return dateModified
  **/
  @Schema(description = "")
  public Object getDateModified() {
    return dateModified;
  }

  public void setDateModified(Object dateModified) {
    this.dateModified = dateModified;
  }

  public GJobStatus dateCreated(Object dateCreated) {
    this.dateCreated = dateCreated;
    return this;
  }

   /**
   * Get dateCreated
   * @return dateCreated
  **/
  @Schema(description = "")
  public Object getDateCreated() {
    return dateCreated;
  }

  public void setDateCreated(Object dateCreated) {
    this.dateCreated = dateCreated;
  }

  public GJobStatus jobType(Object jobType) {
    this.jobType = jobType;
    return this;
  }

   /**
   * Get jobType
   * @return jobType
  **/
  @Schema(required = true, description = "")
  public Object getJobType() {
    return jobType;
  }

  public void setJobType(Object jobType) {
    this.jobType = jobType;
  }

  public GJobStatus workflowType(Object workflowType) {
    this.workflowType = workflowType;
    return this;
  }

   /**
   * Get workflowType
   * @return workflowType
  **/
  @Schema(required = true, description = "")
  public Object getWorkflowType() {
    return workflowType;
  }

  public void setWorkflowType(Object workflowType) {
    this.workflowType = workflowType;
  }

  public GJobStatus workflowId(Object workflowId) {
    this.workflowId = workflowId;
    return this;
  }

   /**
   * Get workflowId
   * @return workflowId
  **/
  @Schema(required = true, description = "")
  public Object getWorkflowId() {
    return workflowId;
  }

  public void setWorkflowId(Object workflowId) {
    this.workflowId = workflowId;
  }

  public GJobStatus processing(Object processing) {
    this.processing = processing;
    return this;
  }

   /**
   * Get processing
   * @return processing
  **/
  @Schema(description = "")
  public Object getProcessing() {
    return processing;
  }

  public void setProcessing(Object processing) {
    this.processing = processing;
  }

  public GJobStatus finished(Object finished) {
    this.finished = finished;
    return this;
  }

   /**
   * Get finished
   * @return finished
  **/
  @Schema(description = "")
  public Object getFinished() {
    return finished;
  }

  public void setFinished(Object finished) {
    this.finished = finished;
  }

  public GJobStatus error(Object error) {
    this.error = error;
    return this;
  }

   /**
   * Get error
   * @return error
  **/
  @Schema(description = "")
  public Object getError() {
    return error;
  }

  public void setError(Object error) {
    this.error = error;
  }

  public GJobStatus startDateTime(Object startDateTime) {
    this.startDateTime = startDateTime;
    return this;
  }

   /**
   * Get startDateTime
   * @return startDateTime
  **/
  @Schema(description = "")
  public Object getStartDateTime() {
    return startDateTime;
  }

  public void setStartDateTime(Object startDateTime) {
    this.startDateTime = startDateTime;
  }

  public GJobStatus endDateTime(Object endDateTime) {
    this.endDateTime = endDateTime;
    return this;
  }

   /**
   * Get endDateTime
   * @return endDateTime
  **/
  @Schema(description = "")
  public Object getEndDateTime() {
    return endDateTime;
  }

  public void setEndDateTime(Object endDateTime) {
    this.endDateTime = endDateTime;
  }

  public GJobStatus projectEndpointReference(GObjectRefGProjectEndpoint projectEndpointReference) {
    this.projectEndpointReference = projectEndpointReference;
    return this;
  }

   /**
   * Get projectEndpointReference
   * @return projectEndpointReference
  **/
  @Schema(required = true, description = "")
  public GObjectRefGProjectEndpoint getProjectEndpointReference() {
    return projectEndpointReference;
  }

  public void setProjectEndpointReference(GObjectRefGProjectEndpoint projectEndpointReference) {
    this.projectEndpointReference = projectEndpointReference;
  }

  public GJobStatus knowledgeBaseCode(Object knowledgeBaseCode) {
    this.knowledgeBaseCode = knowledgeBaseCode;
    return this;
  }

   /**
   * Get knowledgeBaseCode
   * @return knowledgeBaseCode
  **/
  @Schema(required = true, description = "")
  public Object getKnowledgeBaseCode() {
    return knowledgeBaseCode;
  }

  public void setKnowledgeBaseCode(Object knowledgeBaseCode) {
    this.knowledgeBaseCode = knowledgeBaseCode;
  }

  public GJobStatus projectCode(Object projectCode) {
    this.projectCode = projectCode;
    return this;
  }

   /**
   * Get projectCode
   * @return projectCode
  **/
  @Schema(required = true, description = "")
  public Object getProjectCode() {
    return projectCode;
  }

  public void setProjectCode(Object projectCode) {
    this.projectCode = projectCode;
  }

  public GJobStatus parentJobCode(Object parentJobCode) {
    this.parentJobCode = parentJobCode;
    return this;
  }

   /**
   * Get parentJobCode
   * @return parentJobCode
  **/
  @Schema(description = "")
  public Object getParentJobCode() {
    return parentJobCode;
  }

  public void setParentJobCode(Object parentJobCode) {
    this.parentJobCode = parentJobCode;
  }

  public GJobStatus workflowStatus(WorkflowStatus workflowStatus) {
    this.workflowStatus = workflowStatus;
    return this;
  }

   /**
   * Get workflowStatus
   * @return workflowStatus
  **/
  @Schema(description = "")
  public WorkflowStatus getWorkflowStatus() {
    return workflowStatus;
  }

  public void setWorkflowStatus(WorkflowStatus workflowStatus) {
    this.workflowStatus = workflowStatus;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GJobStatus gjobStatus = (GJobStatus) o;
    return Objects.equals(this.code, gjobStatus.code) &&
        Objects.equals(this.description, gjobStatus.description) &&
        Objects.equals(this.userModified, gjobStatus.userModified) &&
        Objects.equals(this.userCreated, gjobStatus.userCreated) &&
        Objects.equals(this.dateModified, gjobStatus.dateModified) &&
        Objects.equals(this.dateCreated, gjobStatus.dateCreated) &&
        Objects.equals(this.jobType, gjobStatus.jobType) &&
        Objects.equals(this.workflowType, gjobStatus.workflowType) &&
        Objects.equals(this.workflowId, gjobStatus.workflowId) &&
        Objects.equals(this.processing, gjobStatus.processing) &&
        Objects.equals(this.finished, gjobStatus.finished) &&
        Objects.equals(this.error, gjobStatus.error) &&
        Objects.equals(this.startDateTime, gjobStatus.startDateTime) &&
        Objects.equals(this.endDateTime, gjobStatus.endDateTime) &&
        Objects.equals(this.projectEndpointReference, gjobStatus.projectEndpointReference) &&
        Objects.equals(this.knowledgeBaseCode, gjobStatus.knowledgeBaseCode) &&
        Objects.equals(this.projectCode, gjobStatus.projectCode) &&
        Objects.equals(this.parentJobCode, gjobStatus.parentJobCode) &&
        Objects.equals(this.workflowStatus, gjobStatus.workflowStatus);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, description, userModified, userCreated, dateModified, dateCreated, jobType, workflowType, workflowId, processing, finished, error, startDateTime, endDateTime, projectEndpointReference, knowledgeBaseCode, projectCode, parentJobCode, workflowStatus);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GJobStatus {\n");
    
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    userModified: ").append(toIndentedString(userModified)).append("\n");
    sb.append("    userCreated: ").append(toIndentedString(userCreated)).append("\n");
    sb.append("    dateModified: ").append(toIndentedString(dateModified)).append("\n");
    sb.append("    dateCreated: ").append(toIndentedString(dateCreated)).append("\n");
    sb.append("    jobType: ").append(toIndentedString(jobType)).append("\n");
    sb.append("    workflowType: ").append(toIndentedString(workflowType)).append("\n");
    sb.append("    workflowId: ").append(toIndentedString(workflowId)).append("\n");
    sb.append("    processing: ").append(toIndentedString(processing)).append("\n");
    sb.append("    finished: ").append(toIndentedString(finished)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    startDateTime: ").append(toIndentedString(startDateTime)).append("\n");
    sb.append("    endDateTime: ").append(toIndentedString(endDateTime)).append("\n");
    sb.append("    projectEndpointReference: ").append(toIndentedString(projectEndpointReference)).append("\n");
    sb.append("    knowledgeBaseCode: ").append(toIndentedString(knowledgeBaseCode)).append("\n");
    sb.append("    projectCode: ").append(toIndentedString(projectCode)).append("\n");
    sb.append("    parentJobCode: ").append(toIndentedString(parentJobCode)).append("\n");
    sb.append("    workflowStatus: ").append(toIndentedString(workflowStatus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
