/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package gebo.microservices.api.client.vectorizator.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * GStatsLine
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-07-20T23:48:47.570095160+02:00[Europe/Rome]")

public class GStatsLine {
  @JsonProperty("statsKey")
  private Object statsKey = null;

  @JsonProperty("data")
  private Object data = null;

  public GStatsLine statsKey(Object statsKey) {
    this.statsKey = statsKey;
    return this;
  }

   /**
   * Get statsKey
   * @return statsKey
  **/
  @Schema(description = "")
  public Object getStatsKey() {
    return statsKey;
  }

  public void setStatsKey(Object statsKey) {
    this.statsKey = statsKey;
  }

  public GStatsLine data(Object data) {
    this.data = data;
    return this;
  }

   /**
   * Get data
   * @return data
  **/
  @Schema(description = "")
  public Object getData() {
    return data;
  }

  public void setData(Object data) {
    this.data = data;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GStatsLine gstatsLine = (GStatsLine) o;
    return Objects.equals(this.statsKey, gstatsLine.statsKey) &&
        Objects.equals(this.data, gstatsLine.data);
  }

  @Override
  public int hashCode() {
    return Objects.hash(statsKey, data);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GStatsLine {\n");
    
    sb.append("    statsKey: ").append(toIndentedString(statsKey)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
