/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package gebo.microservices.api.client.heimdall.api;

import gebo.microservices.api.client.heimdall.model.CheckPasswordRequest;
import gebo.microservices.api.client.heimdall.model.CreateUserIfNotExistsRequest;
import gebo.microservices.api.client.heimdall.model.UserInfosImpl;
import gebo.microservices.api.client.heimdall.model.UsersGroup;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SecurityDirectoryClusterControllerApi
 */
@Ignore
public class SecurityDirectoryClusterControllerApiTest {

    private final SecurityDirectoryClusterControllerApi api = new SecurityDirectoryClusterControllerApi();

    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void infrastructureCheckPasswordTest() {
        CheckPasswordRequest body = null;
        Boolean response = api.infrastructureCheckPassword(body);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void infrastructureCreateUserIfNotExistsTest() {
        CreateUserIfNotExistsRequest body = null;
        UserInfosImpl response = api.infrastructureCreateUserIfNotExists(body);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void infrastructureFindAllGroupsTest() {
        List<UsersGroup> response = api.infrastructureFindAllGroups();

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void infrastructureFindGroupsOfUserTest() {
        String username = null;
        List<UsersGroup> response = api.infrastructureFindGroupsOfUser(username);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void infrastructureFindUserByUsernameTest() {
        String username = null;
        UserInfosImpl response = api.infrastructureFindUserByUsername(username);

        // TODO: test validations
    }
}
