/**
 * This Source Code is subject to the terms of the 
 * Gebo.ai community version Mozilla Public License Version 2.0 (MPL-2.0) — With Data Protection Clauses
 * If a copy of the LICENCE was not distributed with this file, You can obtain one at 
 * https://gebo.ai/gebo-ai-community-version-mozilla-public-license-version-2-0-mpl-2-0-with-data-protection-clauses/  
 * and https://mozilla.org/MPL/2.0/.
 * Copyright (c) 2025+ Gebo.ai 
 */
 
 
 

/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * OpenAPI spec version: 1001.0.0-SNAPSHOT-1880ad5e096033bb3b3098e5db8fe1cdb2d8fc0f
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ai.gebo.jira.cloud.client.model;

import java.util.Date;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.v3.oas.annotations.media.Schema;
/**
 * A log of changes made to issue fields. Changelogs related to workflow associations are currently being deprecated.
 */
@Schema(description = "A log of changes made to issue fields. Changelogs related to workflow associations are currently being deprecated.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-05-05T08:43:30.568333200+02:00[Europe/Rome]")

public class Changelog {
  @JsonProperty("author")
  private AllOfChangelogAuthor author = null;

  @JsonProperty("created")
  private Date created = null;

  @JsonProperty("historyMetadata")
  private AllOfChangelogHistoryMetadata historyMetadata = null;

  @JsonProperty("id")
  private String id = null;

  @JsonProperty("items")
  private List<ChangeDetails> items = null;

   /**
   * The user who made the change.
   * @return author
  **/
  @Schema(description = "The user who made the change.")
  public AllOfChangelogAuthor getAuthor() {
    return author;
  }

   /**
   * The date on which the change took place.
   * @return created
  **/
  @Schema(description = "The date on which the change took place.")
  public Date getCreated() {
    return created;
  }

   /**
   * The history metadata associated with the changed.
   * @return historyMetadata
  **/
  @Schema(description = "The history metadata associated with the changed.")
  public AllOfChangelogHistoryMetadata getHistoryMetadata() {
    return historyMetadata;
  }

   /**
   * The ID of the changelog.
   * @return id
  **/
  @Schema(description = "The ID of the changelog.")
  public String getId() {
    return id;
  }

   /**
   * The list of items changed.
   * @return items
  **/
  @Schema(description = "The list of items changed.")
  public List<ChangeDetails> getItems() {
    return items;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Changelog changelog = (Changelog) o;
    return Objects.equals(this.author, changelog.author) &&
        Objects.equals(this.created, changelog.created) &&
        Objects.equals(this.historyMetadata, changelog.historyMetadata) &&
        Objects.equals(this.id, changelog.id) &&
        Objects.equals(this.items, changelog.items);
  }

  @Override
  public int hashCode() {
    return Objects.hash(author, created, historyMetadata, id, items);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Changelog {\n");
    
    sb.append("    author: ").append(toIndentedString(author)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    historyMetadata: ").append(toIndentedString(historyMetadata)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    items: ").append(toIndentedString(items)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
