/**
 * This Source Code is subject to the terms of the 
 * Gebo.ai community version Mozilla Public License Version 2.0 (MPL-2.0) — With Data Protection Clauses
 * If a copy of the LICENCE was not distributed with this file, You can obtain one at 
 * https://gebo.ai/gebo-ai-community-version-mozilla-public-license-version-2-0-mpl-2-0-with-data-protection-clauses/  
 * and https://mozilla.org/MPL/2.0/.
 * Copyright (c) 2025+ Gebo.ai 
 */
 
 
 

/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * OpenAPI spec version: 1001.0.0-SNAPSHOT-1880ad5e096033bb3b3098e5db8fe1cdb2d8fc0f
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ai.gebo.jira.cloud.client.model;

import java.util.Objects;
import java.util.Arrays;
import ai.gebo.jira.cloud.client.model.JiraLabelsInput;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
/**
 * JiraLabelsField
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-05-05T08:43:30.568333200+02:00[Europe/Rome]")

public class JiraLabelsField {
  /**
   * Gets or Sets bulkEditMultiSelectFieldOption
   */
  public enum BulkEditMultiSelectFieldOptionEnum {
    ADD("ADD"),
    REMOVE("REMOVE"),
    REPLACE("REPLACE"),
    REMOVE_ALL("REMOVE_ALL");

    private String value;

    BulkEditMultiSelectFieldOptionEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static BulkEditMultiSelectFieldOptionEnum fromValue(String input) {
      for (BulkEditMultiSelectFieldOptionEnum b : BulkEditMultiSelectFieldOptionEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("bulkEditMultiSelectFieldOption")
  private BulkEditMultiSelectFieldOptionEnum bulkEditMultiSelectFieldOption = null;

  @JsonProperty("fieldId")
  private String fieldId = null;

  @JsonProperty("labels")
  private List<JiraLabelsInput> labels = new ArrayList<>();

  public JiraLabelsField bulkEditMultiSelectFieldOption(BulkEditMultiSelectFieldOptionEnum bulkEditMultiSelectFieldOption) {
    this.bulkEditMultiSelectFieldOption = bulkEditMultiSelectFieldOption;
    return this;
  }

   /**
   * Get bulkEditMultiSelectFieldOption
   * @return bulkEditMultiSelectFieldOption
  **/
  @Schema(required = true, description = "")
  public BulkEditMultiSelectFieldOptionEnum getBulkEditMultiSelectFieldOption() {
    return bulkEditMultiSelectFieldOption;
  }

  public void setBulkEditMultiSelectFieldOption(BulkEditMultiSelectFieldOptionEnum bulkEditMultiSelectFieldOption) {
    this.bulkEditMultiSelectFieldOption = bulkEditMultiSelectFieldOption;
  }

  public JiraLabelsField fieldId(String fieldId) {
    this.fieldId = fieldId;
    return this;
  }

   /**
   * Get fieldId
   * @return fieldId
  **/
  @Schema(required = true, description = "")
  public String getFieldId() {
    return fieldId;
  }

  public void setFieldId(String fieldId) {
    this.fieldId = fieldId;
  }

  public JiraLabelsField labels(List<JiraLabelsInput> labels) {
    this.labels = labels;
    return this;
  }

  public JiraLabelsField addLabelsItem(JiraLabelsInput labelsItem) {
    this.labels.add(labelsItem);
    return this;
  }

   /**
   * Get labels
   * @return labels
  **/
  @Schema(required = true, description = "")
  public List<JiraLabelsInput> getLabels() {
    return labels;
  }

  public void setLabels(List<JiraLabelsInput> labels) {
    this.labels = labels;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JiraLabelsField jiraLabelsField = (JiraLabelsField) o;
    return Objects.equals(this.bulkEditMultiSelectFieldOption, jiraLabelsField.bulkEditMultiSelectFieldOption) &&
        Objects.equals(this.fieldId, jiraLabelsField.fieldId) &&
        Objects.equals(this.labels, jiraLabelsField.labels);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bulkEditMultiSelectFieldOption, fieldId, labels);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JiraLabelsField {\n");
    
    sb.append("    bulkEditMultiSelectFieldOption: ").append(toIndentedString(bulkEditMultiSelectFieldOption)).append("\n");
    sb.append("    fieldId: ").append(toIndentedString(fieldId)).append("\n");
    sb.append("    labels: ").append(toIndentedString(labels)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
