/**
 * This Source Code is subject to the terms of the 
 * Gebo.ai community version Mozilla Public License Version 2.0 (MPL-2.0) — With Data Protection Clauses
 * If a copy of the LICENCE was not distributed with this file, You can obtain one at 
 * https://gebo.ai/gebo-ai-community-version-mozilla-public-license-version-2-0-mpl-2-0-with-data-protection-clauses/  
 * and https://mozilla.org/MPL/2.0/.
 * Copyright (c) 2025+ Gebo.ai 
 */
 
 
 

/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * OpenAPI spec version: 1001.0.0-SNAPSHOT-1880ad5e096033bb3b3098e5db8fe1cdb2d8fc0f
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ai.gebo.jira.cloud.client.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.v3.oas.annotations.media.Schema;
/**
 * SoftwareNavigationInfo
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-05-05T08:43:30.568333200+02:00[Europe/Rome]")

public class SoftwareNavigationInfo {
  @JsonProperty("boardId")
  private Long boardId = null;

  @JsonProperty("boardName")
  private String boardName = null;

  @JsonProperty("simpleBoard")
  private Boolean simpleBoard = null;

  @JsonProperty("totalBoardsInProject")
  private Long totalBoardsInProject = null;

  public SoftwareNavigationInfo boardId(Long boardId) {
    this.boardId = boardId;
    return this;
  }

   /**
   * Get boardId
   * @return boardId
  **/
  @Schema(description = "")
  public Long getBoardId() {
    return boardId;
  }

  public void setBoardId(Long boardId) {
    this.boardId = boardId;
  }

  public SoftwareNavigationInfo boardName(String boardName) {
    this.boardName = boardName;
    return this;
  }

   /**
   * Get boardName
   * @return boardName
  **/
  @Schema(description = "")
  public String getBoardName() {
    return boardName;
  }

  public void setBoardName(String boardName) {
    this.boardName = boardName;
  }

  public SoftwareNavigationInfo simpleBoard(Boolean simpleBoard) {
    this.simpleBoard = simpleBoard;
    return this;
  }

   /**
   * Get simpleBoard
   * @return simpleBoard
  **/
  @Schema(description = "")
  public Boolean isSimpleBoard() {
    return simpleBoard;
  }

  public void setSimpleBoard(Boolean simpleBoard) {
    this.simpleBoard = simpleBoard;
  }

  public SoftwareNavigationInfo totalBoardsInProject(Long totalBoardsInProject) {
    this.totalBoardsInProject = totalBoardsInProject;
    return this;
  }

   /**
   * Get totalBoardsInProject
   * @return totalBoardsInProject
  **/
  @Schema(description = "")
  public Long getTotalBoardsInProject() {
    return totalBoardsInProject;
  }

  public void setTotalBoardsInProject(Long totalBoardsInProject) {
    this.totalBoardsInProject = totalBoardsInProject;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SoftwareNavigationInfo softwareNavigationInfo = (SoftwareNavigationInfo) o;
    return Objects.equals(this.boardId, softwareNavigationInfo.boardId) &&
        Objects.equals(this.boardName, softwareNavigationInfo.boardName) &&
        Objects.equals(this.simpleBoard, softwareNavigationInfo.simpleBoard) &&
        Objects.equals(this.totalBoardsInProject, softwareNavigationInfo.totalBoardsInProject);
  }

  @Override
  public int hashCode() {
    return Objects.hash(boardId, boardName, simpleBoard, totalBoardsInProject);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SoftwareNavigationInfo {\n");
    
    sb.append("    boardId: ").append(toIndentedString(boardId)).append("\n");
    sb.append("    boardName: ").append(toIndentedString(boardName)).append("\n");
    sb.append("    simpleBoard: ").append(toIndentedString(simpleBoard)).append("\n");
    sb.append("    totalBoardsInProject: ").append(toIndentedString(totalBoardsInProject)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
