/**
 * This Source Code is subject to the terms of the 
 * Gebo.ai community version Mozilla Public License Version 2.0 (MPL-2.0) — With Data Protection Clauses
 * If a copy of the LICENCE was not distributed with this file, You can obtain one at 
 * https://gebo.ai/gebo-ai-community-version-mozilla-public-license-version-2-0-mpl-2-0-with-data-protection-clauses/  
 * and https://mozilla.org/MPL/2.0/.
 * Copyright (c) 2025+ Gebo.ai 
 */
 
 
 

/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * OpenAPI spec version: 1001.0.0-SNAPSHOT-1880ad5e096033bb3b3098e5db8fe1cdb2d8fc0f
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ai.gebo.jira.cloud.client.model;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.v3.oas.annotations.media.Schema;
/**
 * The details of the workflows to update.
 */
@Schema(description = "The details of the workflows to update.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-05-05T08:43:30.568333200+02:00[Europe/Rome]")

public class WorkflowUpdate extends HashMap<String, Object> {
  @JsonProperty("defaultStatusMappings")
  private List<StatusMigration> defaultStatusMappings = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("id")
  private String id = null;

  @JsonProperty("loopedTransitionContainerLayout")
  private WorkflowLayout loopedTransitionContainerLayout = null;

  @JsonProperty("startPointLayout")
  private WorkflowLayout startPointLayout = null;

  @JsonProperty("statusMappings")
  private List<StatusMappingDTO> statusMappings = null;

  @JsonProperty("statuses")
  private List<StatusLayoutUpdate> statuses = new ArrayList<>();

  @JsonProperty("transitions")
  private List<TransitionUpdateDTO> transitions = new ArrayList<>();

  @JsonProperty("version")
  private DocumentVersion version = null;

  public WorkflowUpdate defaultStatusMappings(List<StatusMigration> defaultStatusMappings) {
    this.defaultStatusMappings = defaultStatusMappings;
    return this;
  }

  public WorkflowUpdate addDefaultStatusMappingsItem(StatusMigration defaultStatusMappingsItem) {
    if (this.defaultStatusMappings == null) {
      this.defaultStatusMappings = new ArrayList<>();
    }
    this.defaultStatusMappings.add(defaultStatusMappingsItem);
    return this;
  }

   /**
   * The mapping of old to new status ID.
   * @return defaultStatusMappings
  **/
  @Schema(description = "The mapping of old to new status ID.")
  public List<StatusMigration> getDefaultStatusMappings() {
    return defaultStatusMappings;
  }

  public void setDefaultStatusMappings(List<StatusMigration> defaultStatusMappings) {
    this.defaultStatusMappings = defaultStatusMappings;
  }

  public WorkflowUpdate description(String description) {
    this.description = description;
    return this;
  }

   /**
   * The new description for this workflow.
   * @return description
  **/
  @Schema(description = "The new description for this workflow.")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public WorkflowUpdate id(String id) {
    this.id = id;
    return this;
  }

   /**
   * The ID of this workflow.
   * @return id
  **/
  @Schema(required = true, description = "The ID of this workflow.")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public WorkflowUpdate loopedTransitionContainerLayout(WorkflowLayout loopedTransitionContainerLayout) {
    this.loopedTransitionContainerLayout = loopedTransitionContainerLayout;
    return this;
  }

   /**
   * Get loopedTransitionContainerLayout
   * @return loopedTransitionContainerLayout
  **/
  @Schema(description = "")
  public WorkflowLayout getLoopedTransitionContainerLayout() {
    return loopedTransitionContainerLayout;
  }

  public void setLoopedTransitionContainerLayout(WorkflowLayout loopedTransitionContainerLayout) {
    this.loopedTransitionContainerLayout = loopedTransitionContainerLayout;
  }

  public WorkflowUpdate startPointLayout(WorkflowLayout startPointLayout) {
    this.startPointLayout = startPointLayout;
    return this;
  }

   /**
   * Get startPointLayout
   * @return startPointLayout
  **/
  @Schema(description = "")
  public WorkflowLayout getStartPointLayout() {
    return startPointLayout;
  }

  public void setStartPointLayout(WorkflowLayout startPointLayout) {
    this.startPointLayout = startPointLayout;
  }

  public WorkflowUpdate statusMappings(List<StatusMappingDTO> statusMappings) {
    this.statusMappings = statusMappings;
    return this;
  }

  public WorkflowUpdate addStatusMappingsItem(StatusMappingDTO statusMappingsItem) {
    if (this.statusMappings == null) {
      this.statusMappings = new ArrayList<>();
    }
    this.statusMappings.add(statusMappingsItem);
    return this;
  }

   /**
   * The mapping of old to new status ID for a specific project and issue type.
   * @return statusMappings
  **/
  @Schema(description = "The mapping of old to new status ID for a specific project and issue type.")
  public List<StatusMappingDTO> getStatusMappings() {
    return statusMappings;
  }

  public void setStatusMappings(List<StatusMappingDTO> statusMappings) {
    this.statusMappings = statusMappings;
  }

  public WorkflowUpdate statuses(List<StatusLayoutUpdate> statuses) {
    this.statuses = statuses;
    return this;
  }

  public WorkflowUpdate addStatusesItem(StatusLayoutUpdate statusesItem) {
    this.statuses.add(statusesItem);
    return this;
  }

   /**
   * The statuses associated with this workflow.
   * @return statuses
  **/
  @Schema(required = true, description = "The statuses associated with this workflow.")
  public List<StatusLayoutUpdate> getStatuses() {
    return statuses;
  }

  public void setStatuses(List<StatusLayoutUpdate> statuses) {
    this.statuses = statuses;
  }

  public WorkflowUpdate transitions(List<TransitionUpdateDTO> transitions) {
    this.transitions = transitions;
    return this;
  }

  public WorkflowUpdate addTransitionsItem(TransitionUpdateDTO transitionsItem) {
    this.transitions.add(transitionsItem);
    return this;
  }

   /**
   * The transitions of this workflow.
   * @return transitions
  **/
  @Schema(required = true, description = "The transitions of this workflow.")
  public List<TransitionUpdateDTO> getTransitions() {
    return transitions;
  }

  public void setTransitions(List<TransitionUpdateDTO> transitions) {
    this.transitions = transitions;
  }

  public WorkflowUpdate version(DocumentVersion version) {
    this.version = version;
    return this;
  }

   /**
   * Get version
   * @return version
  **/
  @Schema(required = true, description = "")
  public DocumentVersion getVersion() {
    return version;
  }

  public void setVersion(DocumentVersion version) {
    this.version = version;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WorkflowUpdate workflowUpdate = (WorkflowUpdate) o;
    return Objects.equals(this.defaultStatusMappings, workflowUpdate.defaultStatusMappings) &&
        Objects.equals(this.description, workflowUpdate.description) &&
        Objects.equals(this.id, workflowUpdate.id) &&
        Objects.equals(this.loopedTransitionContainerLayout, workflowUpdate.loopedTransitionContainerLayout) &&
        Objects.equals(this.startPointLayout, workflowUpdate.startPointLayout) &&
        Objects.equals(this.statusMappings, workflowUpdate.statusMappings) &&
        Objects.equals(this.statuses, workflowUpdate.statuses) &&
        Objects.equals(this.transitions, workflowUpdate.transitions) &&
        Objects.equals(this.version, workflowUpdate.version) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(defaultStatusMappings, description, id, loopedTransitionContainerLayout, startPointLayout, statusMappings, statuses, transitions, version, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WorkflowUpdate {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    defaultStatusMappings: ").append(toIndentedString(defaultStatusMappings)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    loopedTransitionContainerLayout: ").append(toIndentedString(loopedTransitionContainerLayout)).append("\n");
    sb.append("    startPointLayout: ").append(toIndentedString(startPointLayout)).append("\n");
    sb.append("    statusMappings: ").append(toIndentedString(statusMappings)).append("\n");
    sb.append("    statuses: ").append(toIndentedString(statuses)).append("\n");
    sb.append("    transitions: ").append(toIndentedString(transitions)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
