/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ai.gebo.monolithic.api.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * GeboAwsConnectionCredentials
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-08-28T21:59:13.835580477+02:00[Europe/Rome]")

public class GeboAwsConnectionCredentials {
  @JsonProperty("accessKeyId")
  private String accessKeyId = null;

  @JsonProperty("secretAccessKey")
  private String secretAccessKey = null;

  /**
   * Gets or Sets region
   */
  public enum RegionEnum {
    ME_CENTRAL_1("me-central-1"),
    AWS_CN_GLOBAL("aws-cn-global"),
    US_ISOF_SOUTH_1("us-isof-south-1"),
    AP_EAST_2("ap-east-2"),
    US_WEST_1("us-west-1"),
    US_WEST_2("us-west-2"),
    AF_SOUTH_1("af-south-1"),
    AP_NORTHEAST_3("ap-northeast-3"),
    AP_NORTHEAST_2("ap-northeast-2"),
    AP_NORTHEAST_1("ap-northeast-1"),
    ME_SOUTH_1("me-south-1"),
    SA_EAST_1("sa-east-1"),
    CN_NORTH_1("cn-north-1"),
    AP_SOUTHEAST_1("ap-southeast-1"),
    AP_SOUTHEAST_2("ap-southeast-2"),
    AP_SOUTHEAST_3("ap-southeast-3"),
    AP_SOUTHEAST_4("ap-southeast-4"),
    AP_SOUTHEAST_5("ap-southeast-5"),
    US_EAST_1("us-east-1"),
    AP_SOUTHEAST_6("ap-southeast-6"),
    US_EAST_2("us-east-2"),
    AP_SOUTHEAST_7("ap-southeast-7"),
    CN_NORTHWEST_1("cn-northwest-1"),
    AWS_ISO_E_GLOBAL("aws-iso-e-global"),
    AP_SOUTH_2("ap-south-2"),
    AP_SOUTH_1("ap-south-1"),
    EU_SOUTH_1("eu-south-1"),
    EU_SOUTH_2("eu-south-2"),
    US_GOV_EAST_1("us-gov-east-1"),
    IL_CENTRAL_1("il-central-1"),
    CA_CENTRAL_1("ca-central-1"),
    MX_CENTRAL_1("mx-central-1"),
    EU_CENTRAL_1("eu-central-1"),
    EUSC_DE_EAST_1("eusc-de-east-1"),
    US_ISO_WEST_1("us-iso-west-1"),
    EU_CENTRAL_2("eu-central-2"),
    EU_ISOE_WEST_1("eu-isoe-west-1"),
    AWS_GLOBAL("aws-global"),
    US_ISOB_WEST_1("us-isob-west-1"),
    EU_NORTH_1("eu-north-1"),
    EU_WEST_3("eu-west-3"),
    EU_WEST_2("eu-west-2"),
    EU_WEST_1("eu-west-1"),
    AWS_ISO_GLOBAL("aws-iso-global"),
    AP_EAST_1("ap-east-1"),
    CA_WEST_1("ca-west-1"),
    US_GOV_WEST_1("us-gov-west-1"),
    US_ISO_EAST_1("us-iso-east-1"),
    AWS_ISO_B_GLOBAL("aws-iso-b-global"),
    AWS_ISO_F_GLOBAL("aws-iso-f-global"),
    US_ISOB_EAST_1("us-isob-east-1"),
    AWS_US_GOV_GLOBAL("aws-us-gov-global"),
    US_ISOF_EAST_1("us-isof-east-1");

    private String value;

    RegionEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static RegionEnum fromValue(String input) {
      for (RegionEnum b : RegionEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("region")
  private RegionEnum region = null;

  public GeboAwsConnectionCredentials accessKeyId(String accessKeyId) {
    this.accessKeyId = accessKeyId;
    return this;
  }

   /**
   * Get accessKeyId
   * @return accessKeyId
  **/
  @Schema(required = true, description = "")
  public String getAccessKeyId() {
    return accessKeyId;
  }

  public void setAccessKeyId(String accessKeyId) {
    this.accessKeyId = accessKeyId;
  }

  public GeboAwsConnectionCredentials secretAccessKey(String secretAccessKey) {
    this.secretAccessKey = secretAccessKey;
    return this;
  }

   /**
   * Get secretAccessKey
   * @return secretAccessKey
  **/
  @Schema(required = true, description = "")
  public String getSecretAccessKey() {
    return secretAccessKey;
  }

  public void setSecretAccessKey(String secretAccessKey) {
    this.secretAccessKey = secretAccessKey;
  }

  public GeboAwsConnectionCredentials region(RegionEnum region) {
    this.region = region;
    return this;
  }

   /**
   * Get region
   * @return region
  **/
  @Schema(required = true, description = "")
  public RegionEnum getRegion() {
    return region;
  }

  public void setRegion(RegionEnum region) {
    this.region = region;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GeboAwsConnectionCredentials geboAwsConnectionCredentials = (GeboAwsConnectionCredentials) o;
    return Objects.equals(this.accessKeyId, geboAwsConnectionCredentials.accessKeyId) &&
        Objects.equals(this.secretAccessKey, geboAwsConnectionCredentials.secretAccessKey) &&
        Objects.equals(this.region, geboAwsConnectionCredentials.region);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accessKeyId, secretAccessKey, region);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GeboAwsConnectionCredentials {\n");
    
    sb.append("    accessKeyId: ").append(toIndentedString(accessKeyId)).append("\n");
    sb.append("    secretAccessKey: ").append(toIndentedString(secretAccessKey)).append("\n");
    sb.append("    region: ").append(toIndentedString(region)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
