/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ai.gebo.monolithic.api.client.model;

import java.util.Objects;
import java.util.Arrays;
import ai.gebo.monolithic.api.client.model.ComponentMetaInfo;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
/**
 * GModuleMetaInfo
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-08-28T21:59:13.835580477+02:00[Europe/Rome]")

public class GModuleMetaInfo {
  @JsonProperty("messagingModuleId")
  private String messagingModuleId = null;

  @JsonProperty("components")
  private List<ComponentMetaInfo> components = null;

  public GModuleMetaInfo messagingModuleId(String messagingModuleId) {
    this.messagingModuleId = messagingModuleId;
    return this;
  }

   /**
   * Get messagingModuleId
   * @return messagingModuleId
  **/
  @Schema(description = "")
  public String getMessagingModuleId() {
    return messagingModuleId;
  }

  public void setMessagingModuleId(String messagingModuleId) {
    this.messagingModuleId = messagingModuleId;
  }

  public GModuleMetaInfo components(List<ComponentMetaInfo> components) {
    this.components = components;
    return this;
  }

  public GModuleMetaInfo addComponentsItem(ComponentMetaInfo componentsItem) {
    if (this.components == null) {
      this.components = new ArrayList<>();
    }
    this.components.add(componentsItem);
    return this;
  }

   /**
   * Get components
   * @return components
  **/
  @Schema(description = "")
  public List<ComponentMetaInfo> getComponents() {
    return components;
  }

  public void setComponents(List<ComponentMetaInfo> components) {
    this.components = components;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GModuleMetaInfo gmoduleMetaInfo = (GModuleMetaInfo) o;
    return Objects.equals(this.messagingModuleId, gmoduleMetaInfo.messagingModuleId) &&
        Objects.equals(this.components, gmoduleMetaInfo.components);
  }

  @Override
  public int hashCode() {
    return Objects.hash(messagingModuleId, components);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GModuleMetaInfo {\n");
    
    sb.append("    messagingModuleId: ").append(toIndentedString(messagingModuleId)).append("\n");
    sb.append("    components: ").append(toIndentedString(components)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
