/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ai.gebo.monolithic.api.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * LLMUsageAggregationBucket
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-07-04T10:49:15.119457200+02:00[Europe/Rome]")

public class LLMUsageAggregationBucket {
  @JsonProperty("providerId")
  private String providerId = null;

  @JsonProperty("username")
  private String username = null;

  @JsonProperty("model")
  private String model = null;

  @JsonProperty("callerStack")
  private String callerStack = null;

  /**
   * Gets or Sets modelType
   */
  public enum ModelTypeEnum {
    CHAT("CHAT"),
    EMBEDDING("EMBEDDING"),
    IMAGE("IMAGE"),
    RANKER("RANKER"),
    TTS("TTS"),
    TRANSCRIPT("TRANSCRIPT");

    private String value;

    ModelTypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static ModelTypeEnum fromValue(String input) {
      for (ModelTypeEnum b : ModelTypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("modelType")
  private ModelTypeEnum modelType = null;

  @JsonProperty("year")
  private Integer year = null;

  @JsonProperty("month")
  private Integer month = null;

  @JsonProperty("day")
  private Integer day = null;

  @JsonProperty("inputToken")
  private Long inputToken = null;

  @JsonProperty("outputToken")
  private Long outputToken = null;

  @JsonProperty("totalToken")
  private Long totalToken = null;

  @JsonProperty("nrRequests")
  private Long nrRequests = null;

  @JsonProperty("latencyMin")
  private Long latencyMin = null;

  @JsonProperty("latencyMax")
  private Long latencyMax = null;

  @JsonProperty("latencyAvg")
  private Long latencyAvg = null;

  public LLMUsageAggregationBucket providerId(String providerId) {
    this.providerId = providerId;
    return this;
  }

   /**
   * Get providerId
   * @return providerId
  **/
  @Schema(description = "")
  public String getProviderId() {
    return providerId;
  }

  public void setProviderId(String providerId) {
    this.providerId = providerId;
  }

  public LLMUsageAggregationBucket username(String username) {
    this.username = username;
    return this;
  }

   /**
   * Get username
   * @return username
  **/
  @Schema(description = "")
  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }

  public LLMUsageAggregationBucket model(String model) {
    this.model = model;
    return this;
  }

   /**
   * Get model
   * @return model
  **/
  @Schema(description = "")
  public String getModel() {
    return model;
  }

  public void setModel(String model) {
    this.model = model;
  }

  public LLMUsageAggregationBucket callerStack(String callerStack) {
    this.callerStack = callerStack;
    return this;
  }

   /**
   * Get callerStack
   * @return callerStack
  **/
  @Schema(description = "")
  public String getCallerStack() {
    return callerStack;
  }

  public void setCallerStack(String callerStack) {
    this.callerStack = callerStack;
  }

  public LLMUsageAggregationBucket modelType(ModelTypeEnum modelType) {
    this.modelType = modelType;
    return this;
  }

   /**
   * Get modelType
   * @return modelType
  **/
  @Schema(description = "")
  public ModelTypeEnum getModelType() {
    return modelType;
  }

  public void setModelType(ModelTypeEnum modelType) {
    this.modelType = modelType;
  }

  public LLMUsageAggregationBucket year(Integer year) {
    this.year = year;
    return this;
  }

   /**
   * Get year
   * @return year
  **/
  @Schema(description = "")
  public Integer getYear() {
    return year;
  }

  public void setYear(Integer year) {
    this.year = year;
  }

  public LLMUsageAggregationBucket month(Integer month) {
    this.month = month;
    return this;
  }

   /**
   * Get month
   * @return month
  **/
  @Schema(description = "")
  public Integer getMonth() {
    return month;
  }

  public void setMonth(Integer month) {
    this.month = month;
  }

  public LLMUsageAggregationBucket day(Integer day) {
    this.day = day;
    return this;
  }

   /**
   * Get day
   * @return day
  **/
  @Schema(description = "")
  public Integer getDay() {
    return day;
  }

  public void setDay(Integer day) {
    this.day = day;
  }

  public LLMUsageAggregationBucket inputToken(Long inputToken) {
    this.inputToken = inputToken;
    return this;
  }

   /**
   * Get inputToken
   * @return inputToken
  **/
  @Schema(description = "")
  public Long getInputToken() {
    return inputToken;
  }

  public void setInputToken(Long inputToken) {
    this.inputToken = inputToken;
  }

  public LLMUsageAggregationBucket outputToken(Long outputToken) {
    this.outputToken = outputToken;
    return this;
  }

   /**
   * Get outputToken
   * @return outputToken
  **/
  @Schema(description = "")
  public Long getOutputToken() {
    return outputToken;
  }

  public void setOutputToken(Long outputToken) {
    this.outputToken = outputToken;
  }

  public LLMUsageAggregationBucket totalToken(Long totalToken) {
    this.totalToken = totalToken;
    return this;
  }

   /**
   * Get totalToken
   * @return totalToken
  **/
  @Schema(description = "")
  public Long getTotalToken() {
    return totalToken;
  }

  public void setTotalToken(Long totalToken) {
    this.totalToken = totalToken;
  }

  public LLMUsageAggregationBucket nrRequests(Long nrRequests) {
    this.nrRequests = nrRequests;
    return this;
  }

   /**
   * Get nrRequests
   * @return nrRequests
  **/
  @Schema(description = "")
  public Long getNrRequests() {
    return nrRequests;
  }

  public void setNrRequests(Long nrRequests) {
    this.nrRequests = nrRequests;
  }

  public LLMUsageAggregationBucket latencyMin(Long latencyMin) {
    this.latencyMin = latencyMin;
    return this;
  }

   /**
   * Get latencyMin
   * @return latencyMin
  **/
  @Schema(description = "")
  public Long getLatencyMin() {
    return latencyMin;
  }

  public void setLatencyMin(Long latencyMin) {
    this.latencyMin = latencyMin;
  }

  public LLMUsageAggregationBucket latencyMax(Long latencyMax) {
    this.latencyMax = latencyMax;
    return this;
  }

   /**
   * Get latencyMax
   * @return latencyMax
  **/
  @Schema(description = "")
  public Long getLatencyMax() {
    return latencyMax;
  }

  public void setLatencyMax(Long latencyMax) {
    this.latencyMax = latencyMax;
  }

  public LLMUsageAggregationBucket latencyAvg(Long latencyAvg) {
    this.latencyAvg = latencyAvg;
    return this;
  }

   /**
   * Get latencyAvg
   * @return latencyAvg
  **/
  @Schema(description = "")
  public Long getLatencyAvg() {
    return latencyAvg;
  }

  public void setLatencyAvg(Long latencyAvg) {
    this.latencyAvg = latencyAvg;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LLMUsageAggregationBucket llMUsageAggregationBucket = (LLMUsageAggregationBucket) o;
    return Objects.equals(this.providerId, llMUsageAggregationBucket.providerId) &&
        Objects.equals(this.username, llMUsageAggregationBucket.username) &&
        Objects.equals(this.model, llMUsageAggregationBucket.model) &&
        Objects.equals(this.callerStack, llMUsageAggregationBucket.callerStack) &&
        Objects.equals(this.modelType, llMUsageAggregationBucket.modelType) &&
        Objects.equals(this.year, llMUsageAggregationBucket.year) &&
        Objects.equals(this.month, llMUsageAggregationBucket.month) &&
        Objects.equals(this.day, llMUsageAggregationBucket.day) &&
        Objects.equals(this.inputToken, llMUsageAggregationBucket.inputToken) &&
        Objects.equals(this.outputToken, llMUsageAggregationBucket.outputToken) &&
        Objects.equals(this.totalToken, llMUsageAggregationBucket.totalToken) &&
        Objects.equals(this.nrRequests, llMUsageAggregationBucket.nrRequests) &&
        Objects.equals(this.latencyMin, llMUsageAggregationBucket.latencyMin) &&
        Objects.equals(this.latencyMax, llMUsageAggregationBucket.latencyMax) &&
        Objects.equals(this.latencyAvg, llMUsageAggregationBucket.latencyAvg);
  }

  @Override
  public int hashCode() {
    return Objects.hash(providerId, username, model, callerStack, modelType, year, month, day, inputToken, outputToken, totalToken, nrRequests, latencyMin, latencyMax, latencyAvg);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LLMUsageAggregationBucket {\n");
    
    sb.append("    providerId: ").append(toIndentedString(providerId)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("    model: ").append(toIndentedString(model)).append("\n");
    sb.append("    callerStack: ").append(toIndentedString(callerStack)).append("\n");
    sb.append("    modelType: ").append(toIndentedString(modelType)).append("\n");
    sb.append("    year: ").append(toIndentedString(year)).append("\n");
    sb.append("    month: ").append(toIndentedString(month)).append("\n");
    sb.append("    day: ").append(toIndentedString(day)).append("\n");
    sb.append("    inputToken: ").append(toIndentedString(inputToken)).append("\n");
    sb.append("    outputToken: ").append(toIndentedString(outputToken)).append("\n");
    sb.append("    totalToken: ").append(toIndentedString(totalToken)).append("\n");
    sb.append("    nrRequests: ").append(toIndentedString(nrRequests)).append("\n");
    sb.append("    latencyMin: ").append(toIndentedString(latencyMin)).append("\n");
    sb.append("    latencyMax: ").append(toIndentedString(latencyMax)).append("\n");
    sb.append("    latencyAvg: ").append(toIndentedString(latencyAvg)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
