/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ai.gebo.monolithic.api.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
/**
 * MCPTool
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-07-11T10:08:29.678188200+02:00[Europe/Rome]")

public class MCPTool {
  @JsonProperty("accessibleGroups")
  private List<String> accessibleGroups = null;

  @JsonProperty("accessibleUsers")
  private List<String> accessibleUsers = null;

  @JsonProperty("accessibleToAll")
  private Boolean accessibleToAll = null;

  @JsonProperty("aclAliases")
  private List<Integer> aclAliases = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("deletedOnMCPServer")
  private Boolean deletedOnMCPServer = null;

  @JsonProperty("addedOnMCPServer")
  private Boolean addedOnMCPServer = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("inputSchema")
  private String inputSchema = null;

  public MCPTool accessibleGroups(List<String> accessibleGroups) {
    this.accessibleGroups = accessibleGroups;
    return this;
  }

  public MCPTool addAccessibleGroupsItem(String accessibleGroupsItem) {
    if (this.accessibleGroups == null) {
      this.accessibleGroups = new ArrayList<>();
    }
    this.accessibleGroups.add(accessibleGroupsItem);
    return this;
  }

   /**
   * Get accessibleGroups
   * @return accessibleGroups
  **/
  @Schema(description = "")
  public List<String> getAccessibleGroups() {
    return accessibleGroups;
  }

  public void setAccessibleGroups(List<String> accessibleGroups) {
    this.accessibleGroups = accessibleGroups;
  }

  public MCPTool accessibleUsers(List<String> accessibleUsers) {
    this.accessibleUsers = accessibleUsers;
    return this;
  }

  public MCPTool addAccessibleUsersItem(String accessibleUsersItem) {
    if (this.accessibleUsers == null) {
      this.accessibleUsers = new ArrayList<>();
    }
    this.accessibleUsers.add(accessibleUsersItem);
    return this;
  }

   /**
   * Get accessibleUsers
   * @return accessibleUsers
  **/
  @Schema(description = "")
  public List<String> getAccessibleUsers() {
    return accessibleUsers;
  }

  public void setAccessibleUsers(List<String> accessibleUsers) {
    this.accessibleUsers = accessibleUsers;
  }

  public MCPTool accessibleToAll(Boolean accessibleToAll) {
    this.accessibleToAll = accessibleToAll;
    return this;
  }

   /**
   * Get accessibleToAll
   * @return accessibleToAll
  **/
  @Schema(description = "")
  public Boolean isAccessibleToAll() {
    return accessibleToAll;
  }

  public void setAccessibleToAll(Boolean accessibleToAll) {
    this.accessibleToAll = accessibleToAll;
  }

  public MCPTool aclAliases(List<Integer> aclAliases) {
    this.aclAliases = aclAliases;
    return this;
  }

  public MCPTool addAclAliasesItem(Integer aclAliasesItem) {
    if (this.aclAliases == null) {
      this.aclAliases = new ArrayList<>();
    }
    this.aclAliases.add(aclAliasesItem);
    return this;
  }

   /**
   * Get aclAliases
   * @return aclAliases
  **/
  @Schema(description = "")
  public List<Integer> getAclAliases() {
    return aclAliases;
  }

  public void setAclAliases(List<Integer> aclAliases) {
    this.aclAliases = aclAliases;
  }

  public MCPTool name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public MCPTool deletedOnMCPServer(Boolean deletedOnMCPServer) {
    this.deletedOnMCPServer = deletedOnMCPServer;
    return this;
  }

   /**
   * Get deletedOnMCPServer
   * @return deletedOnMCPServer
  **/
  @Schema(description = "")
  public Boolean isDeletedOnMCPServer() {
    return deletedOnMCPServer;
  }

  public void setDeletedOnMCPServer(Boolean deletedOnMCPServer) {
    this.deletedOnMCPServer = deletedOnMCPServer;
  }

  public MCPTool addedOnMCPServer(Boolean addedOnMCPServer) {
    this.addedOnMCPServer = addedOnMCPServer;
    return this;
  }

   /**
   * Get addedOnMCPServer
   * @return addedOnMCPServer
  **/
  @Schema(description = "")
  public Boolean isAddedOnMCPServer() {
    return addedOnMCPServer;
  }

  public void setAddedOnMCPServer(Boolean addedOnMCPServer) {
    this.addedOnMCPServer = addedOnMCPServer;
  }

  public MCPTool description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @Schema(description = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public MCPTool inputSchema(String inputSchema) {
    this.inputSchema = inputSchema;
    return this;
  }

   /**
   * Get inputSchema
   * @return inputSchema
  **/
  @Schema(description = "")
  public String getInputSchema() {
    return inputSchema;
  }

  public void setInputSchema(String inputSchema) {
    this.inputSchema = inputSchema;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MCPTool mcPTool = (MCPTool) o;
    return Objects.equals(this.accessibleGroups, mcPTool.accessibleGroups) &&
        Objects.equals(this.accessibleUsers, mcPTool.accessibleUsers) &&
        Objects.equals(this.accessibleToAll, mcPTool.accessibleToAll) &&
        Objects.equals(this.aclAliases, mcPTool.aclAliases) &&
        Objects.equals(this.name, mcPTool.name) &&
        Objects.equals(this.deletedOnMCPServer, mcPTool.deletedOnMCPServer) &&
        Objects.equals(this.addedOnMCPServer, mcPTool.addedOnMCPServer) &&
        Objects.equals(this.description, mcPTool.description) &&
        Objects.equals(this.inputSchema, mcPTool.inputSchema);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accessibleGroups, accessibleUsers, accessibleToAll, aclAliases, name, deletedOnMCPServer, addedOnMCPServer, description, inputSchema);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MCPTool {\n");
    
    sb.append("    accessibleGroups: ").append(toIndentedString(accessibleGroups)).append("\n");
    sb.append("    accessibleUsers: ").append(toIndentedString(accessibleUsers)).append("\n");
    sb.append("    accessibleToAll: ").append(toIndentedString(accessibleToAll)).append("\n");
    sb.append("    aclAliases: ").append(toIndentedString(aclAliases)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    deletedOnMCPServer: ").append(toIndentedString(deletedOnMCPServer)).append("\n");
    sb.append("    addedOnMCPServer: ").append(toIndentedString(addedOnMCPServer)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    inputSchema: ").append(toIndentedString(inputSchema)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
