/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ai.gebo.monolithic.api.client.model;

import java.util.Objects;
import java.util.Arrays;
import ai.gebo.monolithic.api.client.model.DeepSearchDocumentAnalisysResultStep;
import ai.gebo.monolithic.api.client.model.PageableObject;
import ai.gebo.monolithic.api.client.model.SortObject;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
/**
 * PageDeepSearchDocumentAnalisysResultStep
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-01-29T10:56:30.042559800+01:00[Europe/Rome]")

public class PageDeepSearchDocumentAnalisysResultStep {
  @JsonProperty("totalPages")
  private Integer totalPages = null;

  @JsonProperty("totalElements")
  private Long totalElements = null;

  @JsonProperty("first")
  private Boolean first = null;

  @JsonProperty("last")
  private Boolean last = null;

  @JsonProperty("size")
  private Integer size = null;

  @JsonProperty("content")
  private List<DeepSearchDocumentAnalisysResultStep> content = null;

  @JsonProperty("number")
  private Integer number = null;

  @JsonProperty("sort")
  private SortObject sort = null;

  @JsonProperty("numberOfElements")
  private Integer numberOfElements = null;

  @JsonProperty("pageable")
  private PageableObject pageable = null;

  @JsonProperty("empty")
  private Boolean empty = null;

  public PageDeepSearchDocumentAnalisysResultStep totalPages(Integer totalPages) {
    this.totalPages = totalPages;
    return this;
  }

   /**
   * Get totalPages
   * @return totalPages
  **/
  @Schema(description = "")
  public Integer getTotalPages() {
    return totalPages;
  }

  public void setTotalPages(Integer totalPages) {
    this.totalPages = totalPages;
  }

  public PageDeepSearchDocumentAnalisysResultStep totalElements(Long totalElements) {
    this.totalElements = totalElements;
    return this;
  }

   /**
   * Get totalElements
   * @return totalElements
  **/
  @Schema(description = "")
  public Long getTotalElements() {
    return totalElements;
  }

  public void setTotalElements(Long totalElements) {
    this.totalElements = totalElements;
  }

  public PageDeepSearchDocumentAnalisysResultStep first(Boolean first) {
    this.first = first;
    return this;
  }

   /**
   * Get first
   * @return first
  **/
  @Schema(description = "")
  public Boolean isFirst() {
    return first;
  }

  public void setFirst(Boolean first) {
    this.first = first;
  }

  public PageDeepSearchDocumentAnalisysResultStep last(Boolean last) {
    this.last = last;
    return this;
  }

   /**
   * Get last
   * @return last
  **/
  @Schema(description = "")
  public Boolean isLast() {
    return last;
  }

  public void setLast(Boolean last) {
    this.last = last;
  }

  public PageDeepSearchDocumentAnalisysResultStep size(Integer size) {
    this.size = size;
    return this;
  }

   /**
   * Get size
   * @return size
  **/
  @Schema(description = "")
  public Integer getSize() {
    return size;
  }

  public void setSize(Integer size) {
    this.size = size;
  }

  public PageDeepSearchDocumentAnalisysResultStep content(List<DeepSearchDocumentAnalisysResultStep> content) {
    this.content = content;
    return this;
  }

  public PageDeepSearchDocumentAnalisysResultStep addContentItem(DeepSearchDocumentAnalisysResultStep contentItem) {
    if (this.content == null) {
      this.content = new ArrayList<>();
    }
    this.content.add(contentItem);
    return this;
  }

   /**
   * Get content
   * @return content
  **/
  @Schema(description = "")
  public List<DeepSearchDocumentAnalisysResultStep> getContent() {
    return content;
  }

  public void setContent(List<DeepSearchDocumentAnalisysResultStep> content) {
    this.content = content;
  }

  public PageDeepSearchDocumentAnalisysResultStep number(Integer number) {
    this.number = number;
    return this;
  }

   /**
   * Get number
   * @return number
  **/
  @Schema(description = "")
  public Integer getNumber() {
    return number;
  }

  public void setNumber(Integer number) {
    this.number = number;
  }

  public PageDeepSearchDocumentAnalisysResultStep sort(SortObject sort) {
    this.sort = sort;
    return this;
  }

   /**
   * Get sort
   * @return sort
  **/
  @Schema(description = "")
  public SortObject getSort() {
    return sort;
  }

  public void setSort(SortObject sort) {
    this.sort = sort;
  }

  public PageDeepSearchDocumentAnalisysResultStep numberOfElements(Integer numberOfElements) {
    this.numberOfElements = numberOfElements;
    return this;
  }

   /**
   * Get numberOfElements
   * @return numberOfElements
  **/
  @Schema(description = "")
  public Integer getNumberOfElements() {
    return numberOfElements;
  }

  public void setNumberOfElements(Integer numberOfElements) {
    this.numberOfElements = numberOfElements;
  }

  public PageDeepSearchDocumentAnalisysResultStep pageable(PageableObject pageable) {
    this.pageable = pageable;
    return this;
  }

   /**
   * Get pageable
   * @return pageable
  **/
  @Schema(description = "")
  public PageableObject getPageable() {
    return pageable;
  }

  public void setPageable(PageableObject pageable) {
    this.pageable = pageable;
  }

  public PageDeepSearchDocumentAnalisysResultStep empty(Boolean empty) {
    this.empty = empty;
    return this;
  }

   /**
   * Get empty
   * @return empty
  **/
  @Schema(description = "")
  public Boolean isEmpty() {
    return empty;
  }

  public void setEmpty(Boolean empty) {
    this.empty = empty;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PageDeepSearchDocumentAnalisysResultStep pageDeepSearchDocumentAnalisysResultStep = (PageDeepSearchDocumentAnalisysResultStep) o;
    return Objects.equals(this.totalPages, pageDeepSearchDocumentAnalisysResultStep.totalPages) &&
        Objects.equals(this.totalElements, pageDeepSearchDocumentAnalisysResultStep.totalElements) &&
        Objects.equals(this.first, pageDeepSearchDocumentAnalisysResultStep.first) &&
        Objects.equals(this.last, pageDeepSearchDocumentAnalisysResultStep.last) &&
        Objects.equals(this.size, pageDeepSearchDocumentAnalisysResultStep.size) &&
        Objects.equals(this.content, pageDeepSearchDocumentAnalisysResultStep.content) &&
        Objects.equals(this.number, pageDeepSearchDocumentAnalisysResultStep.number) &&
        Objects.equals(this.sort, pageDeepSearchDocumentAnalisysResultStep.sort) &&
        Objects.equals(this.numberOfElements, pageDeepSearchDocumentAnalisysResultStep.numberOfElements) &&
        Objects.equals(this.pageable, pageDeepSearchDocumentAnalisysResultStep.pageable) &&
        Objects.equals(this.empty, pageDeepSearchDocumentAnalisysResultStep.empty);
  }

  @Override
  public int hashCode() {
    return Objects.hash(totalPages, totalElements, first, last, size, content, number, sort, numberOfElements, pageable, empty);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PageDeepSearchDocumentAnalisysResultStep {\n");
    
    sb.append("    totalPages: ").append(toIndentedString(totalPages)).append("\n");
    sb.append("    totalElements: ").append(toIndentedString(totalElements)).append("\n");
    sb.append("    first: ").append(toIndentedString(first)).append("\n");
    sb.append("    last: ").append(toIndentedString(last)).append("\n");
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    number: ").append(toIndentedString(number)).append("\n");
    sb.append("    sort: ").append(toIndentedString(sort)).append("\n");
    sb.append("    numberOfElements: ").append(toIndentedString(numberOfElements)).append("\n");
    sb.append("    pageable: ").append(toIndentedString(pageable)).append("\n");
    sb.append("    empty: ").append(toIndentedString(empty)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
