/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ai.gebo.monolithic.api.client.model;

import java.util.Objects;
import java.util.Arrays;
import ai.gebo.monolithic.api.client.model.GObjectRefGUserspaceProjectEndpoint;
import ai.gebo.monolithic.api.client.model.UserUploadedContent;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
/**
 * UserUploadToUserSpaceParam
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-01T17:06:13.417468800+01:00[Europe/Rome]")

public class UserUploadToUserSpaceParam {
  @JsonProperty("userUploadContent")
  private List<UserUploadedContent> userUploadContent = new ArrayList<>();

  @JsonProperty("userSpaceTransferTo")
  private GObjectRefGUserspaceProjectEndpoint userSpaceTransferTo = null;

  @JsonProperty("transferToUserDefaultSpace")
  private Boolean transferToUserDefaultSpace = null;

  public UserUploadToUserSpaceParam userUploadContent(List<UserUploadedContent> userUploadContent) {
    this.userUploadContent = userUploadContent;
    return this;
  }

  public UserUploadToUserSpaceParam addUserUploadContentItem(UserUploadedContent userUploadContentItem) {
    this.userUploadContent.add(userUploadContentItem);
    return this;
  }

   /**
   * Get userUploadContent
   * @return userUploadContent
  **/
  @Schema(required = true, description = "")
  public List<UserUploadedContent> getUserUploadContent() {
    return userUploadContent;
  }

  public void setUserUploadContent(List<UserUploadedContent> userUploadContent) {
    this.userUploadContent = userUploadContent;
  }

  public UserUploadToUserSpaceParam userSpaceTransferTo(GObjectRefGUserspaceProjectEndpoint userSpaceTransferTo) {
    this.userSpaceTransferTo = userSpaceTransferTo;
    return this;
  }

   /**
   * Get userSpaceTransferTo
   * @return userSpaceTransferTo
  **/
  @Schema(description = "")
  public GObjectRefGUserspaceProjectEndpoint getUserSpaceTransferTo() {
    return userSpaceTransferTo;
  }

  public void setUserSpaceTransferTo(GObjectRefGUserspaceProjectEndpoint userSpaceTransferTo) {
    this.userSpaceTransferTo = userSpaceTransferTo;
  }

  public UserUploadToUserSpaceParam transferToUserDefaultSpace(Boolean transferToUserDefaultSpace) {
    this.transferToUserDefaultSpace = transferToUserDefaultSpace;
    return this;
  }

   /**
   * Get transferToUserDefaultSpace
   * @return transferToUserDefaultSpace
  **/
  @Schema(description = "")
  public Boolean isTransferToUserDefaultSpace() {
    return transferToUserDefaultSpace;
  }

  public void setTransferToUserDefaultSpace(Boolean transferToUserDefaultSpace) {
    this.transferToUserDefaultSpace = transferToUserDefaultSpace;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserUploadToUserSpaceParam userUploadToUserSpaceParam = (UserUploadToUserSpaceParam) o;
    return Objects.equals(this.userUploadContent, userUploadToUserSpaceParam.userUploadContent) &&
        Objects.equals(this.userSpaceTransferTo, userUploadToUserSpaceParam.userSpaceTransferTo) &&
        Objects.equals(this.transferToUserDefaultSpace, userUploadToUserSpaceParam.transferToUserDefaultSpace);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userUploadContent, userSpaceTransferTo, transferToUserDefaultSpace);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserUploadToUserSpaceParam {\n");
    
    sb.append("    userUploadContent: ").append(toIndentedString(userUploadContent)).append("\n");
    sb.append("    userSpaceTransferTo: ").append(toIndentedString(userSpaceTransferTo)).append("\n");
    sb.append("    transferToUserDefaultSpace: ").append(toIndentedString(transferToUserDefaultSpace)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
