/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package gebo.microservices.api.client.brain.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * AclOwnerParam
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-07-29T09:42:38.770164403+02:00[Europe/Rome]")

public class AclOwnerParam {
  @JsonProperty("ownerType")
  private Object ownerType = null;

  @JsonProperty("ownerCode")
  private Object ownerCode = null;

  @JsonProperty("grants")
  private Object grants = null;

  public AclOwnerParam ownerType(Object ownerType) {
    this.ownerType = ownerType;
    return this;
  }

   /**
   * Get ownerType
   * @return ownerType
  **/
  @Schema(required = true, description = "")
  public Object getOwnerType() {
    return ownerType;
  }

  public void setOwnerType(Object ownerType) {
    this.ownerType = ownerType;
  }

  public AclOwnerParam ownerCode(Object ownerCode) {
    this.ownerCode = ownerCode;
    return this;
  }

   /**
   * Get ownerCode
   * @return ownerCode
  **/
  @Schema(required = true, description = "")
  public Object getOwnerCode() {
    return ownerCode;
  }

  public void setOwnerCode(Object ownerCode) {
    this.ownerCode = ownerCode;
  }

  public AclOwnerParam grants(Object grants) {
    this.grants = grants;
    return this;
  }

   /**
   * Get grants
   * @return grants
  **/
  @Schema(required = true, description = "")
  public Object getGrants() {
    return grants;
  }

  public void setGrants(Object grants) {
    this.grants = grants;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AclOwnerParam aclOwnerParam = (AclOwnerParam) o;
    return Objects.equals(this.ownerType, aclOwnerParam.ownerType) &&
        Objects.equals(this.ownerCode, aclOwnerParam.ownerCode) &&
        Objects.equals(this.grants, aclOwnerParam.grants);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ownerType, ownerCode, grants);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AclOwnerParam {\n");
    
    sb.append("    ownerType: ").append(toIndentedString(ownerType)).append("\n");
    sb.append("    ownerCode: ").append(toIndentedString(ownerCode)).append("\n");
    sb.append("    grants: ").append(toIndentedString(grants)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
