/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package gebo.microservices.api.client.brain.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * CalledFunction
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-07-13T14:53:41.461407700+02:00[Europe/Rome]")

public class CalledFunction {
  @JsonProperty("functionName")
  private Object functionName = null;

  @JsonProperty("functionDescription")
  private Object functionDescription = null;

  @JsonProperty("paramsDescription")
  private Object paramsDescription = null;

  public CalledFunction functionName(Object functionName) {
    this.functionName = functionName;
    return this;
  }

   /**
   * Get functionName
   * @return functionName
  **/
  @Schema(description = "")
  public Object getFunctionName() {
    return functionName;
  }

  public void setFunctionName(Object functionName) {
    this.functionName = functionName;
  }

  public CalledFunction functionDescription(Object functionDescription) {
    this.functionDescription = functionDescription;
    return this;
  }

   /**
   * Get functionDescription
   * @return functionDescription
  **/
  @Schema(description = "")
  public Object getFunctionDescription() {
    return functionDescription;
  }

  public void setFunctionDescription(Object functionDescription) {
    this.functionDescription = functionDescription;
  }

  public CalledFunction paramsDescription(Object paramsDescription) {
    this.paramsDescription = paramsDescription;
    return this;
  }

   /**
   * Get paramsDescription
   * @return paramsDescription
  **/
  @Schema(description = "")
  public Object getParamsDescription() {
    return paramsDescription;
  }

  public void setParamsDescription(Object paramsDescription) {
    this.paramsDescription = paramsDescription;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CalledFunction calledFunction = (CalledFunction) o;
    return Objects.equals(this.functionName, calledFunction.functionName) &&
        Objects.equals(this.functionDescription, calledFunction.functionDescription) &&
        Objects.equals(this.paramsDescription, calledFunction.paramsDescription);
  }

  @Override
  public int hashCode() {
    return Objects.hash(functionName, functionDescription, paramsDescription);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CalledFunction {\n");
    
    sb.append("    functionName: ").append(toIndentedString(functionName)).append("\n");
    sb.append("    functionDescription: ").append(toIndentedString(functionDescription)).append("\n");
    sb.append("    paramsDescription: ").append(toIndentedString(paramsDescription)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
