/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package gebo.microservices.api.client.brain.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import gebo.microservices.api.client.brain.model.GenericOpenAIAPIChatModelChoice;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * GenericOpenAIAPIChatModelConfig
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-07-21T14:57:36.399842475+02:00[Europe/Rome]")

public class GenericOpenAIAPIChatModelConfig {
  @JsonProperty("code")
  private Object code = null;

  @JsonProperty("description")
  private Object description = null;

  @JsonProperty("userModified")
  private Object userModified = null;

  @JsonProperty("userCreated")
  private Object userCreated = null;

  @JsonProperty("dateModified")
  private Object dateModified = null;

  @JsonProperty("dateCreated")
  private Object dateCreated = null;

  @JsonProperty("modelTypeCode")
  private Object modelTypeCode = null;

  @JsonProperty("defaultModel")
  private Object defaultModel = null;

  @JsonProperty("apiSecretCode")
  private Object apiSecretCode = null;

  @JsonProperty("choosedModel")
  private GenericOpenAIAPIChatModelChoice choosedModel = null;

  @JsonProperty("baseUrl")
  private Object baseUrl = null;

  @JsonProperty("contextLength")
  private Object contextLength = null;

  @JsonProperty("topP")
  private Object topP = null;

  @JsonProperty("accessibleGroups")
  private Object accessibleGroups = null;

  @JsonProperty("accessibleUsers")
  private Object accessibleUsers = null;

  @JsonProperty("accessibleToAll")
  private Object accessibleToAll = null;

  @JsonProperty("enabledFunctions")
  private Object enabledFunctions = null;

  @JsonProperty("temperature")
  private Object temperature = null;

  @JsonProperty("forUses")
  private Object forUses = null;

  @JsonProperty("features")
  private Object features = null;

  @JsonProperty("thinking")
  private Object thinking = null;

  @JsonProperty("maxGeneratedTokens")
  private Object maxGeneratedTokens = null;

  public GenericOpenAIAPIChatModelConfig code(Object code) {
    this.code = code;
    return this;
  }

   /**
   * Get code
   * @return code
  **/
  @Schema(description = "")
  public Object getCode() {
    return code;
  }

  public void setCode(Object code) {
    this.code = code;
  }

  public GenericOpenAIAPIChatModelConfig description(Object description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @Schema(description = "")
  public Object getDescription() {
    return description;
  }

  public void setDescription(Object description) {
    this.description = description;
  }

  public GenericOpenAIAPIChatModelConfig userModified(Object userModified) {
    this.userModified = userModified;
    return this;
  }

   /**
   * Get userModified
   * @return userModified
  **/
  @Schema(description = "")
  public Object getUserModified() {
    return userModified;
  }

  public void setUserModified(Object userModified) {
    this.userModified = userModified;
  }

  public GenericOpenAIAPIChatModelConfig userCreated(Object userCreated) {
    this.userCreated = userCreated;
    return this;
  }

   /**
   * Get userCreated
   * @return userCreated
  **/
  @Schema(description = "")
  public Object getUserCreated() {
    return userCreated;
  }

  public void setUserCreated(Object userCreated) {
    this.userCreated = userCreated;
  }

  public GenericOpenAIAPIChatModelConfig dateModified(Object dateModified) {
    this.dateModified = dateModified;
    return this;
  }

   /**
   * Get dateModified
   * @return dateModified
  **/
  @Schema(description = "")
  public Object getDateModified() {
    return dateModified;
  }

  public void setDateModified(Object dateModified) {
    this.dateModified = dateModified;
  }

  public GenericOpenAIAPIChatModelConfig dateCreated(Object dateCreated) {
    this.dateCreated = dateCreated;
    return this;
  }

   /**
   * Get dateCreated
   * @return dateCreated
  **/
  @Schema(description = "")
  public Object getDateCreated() {
    return dateCreated;
  }

  public void setDateCreated(Object dateCreated) {
    this.dateCreated = dateCreated;
  }

  public GenericOpenAIAPIChatModelConfig modelTypeCode(Object modelTypeCode) {
    this.modelTypeCode = modelTypeCode;
    return this;
  }

   /**
   * Get modelTypeCode
   * @return modelTypeCode
  **/
  @Schema(description = "")
  public Object getModelTypeCode() {
    return modelTypeCode;
  }

  public void setModelTypeCode(Object modelTypeCode) {
    this.modelTypeCode = modelTypeCode;
  }

  public GenericOpenAIAPIChatModelConfig defaultModel(Object defaultModel) {
    this.defaultModel = defaultModel;
    return this;
  }

   /**
   * Get defaultModel
   * @return defaultModel
  **/
  @Schema(description = "")
  public Object getDefaultModel() {
    return defaultModel;
  }

  public void setDefaultModel(Object defaultModel) {
    this.defaultModel = defaultModel;
  }

  public GenericOpenAIAPIChatModelConfig apiSecretCode(Object apiSecretCode) {
    this.apiSecretCode = apiSecretCode;
    return this;
  }

   /**
   * Get apiSecretCode
   * @return apiSecretCode
  **/
  @Schema(description = "")
  public Object getApiSecretCode() {
    return apiSecretCode;
  }

  public void setApiSecretCode(Object apiSecretCode) {
    this.apiSecretCode = apiSecretCode;
  }

  public GenericOpenAIAPIChatModelConfig choosedModel(GenericOpenAIAPIChatModelChoice choosedModel) {
    this.choosedModel = choosedModel;
    return this;
  }

   /**
   * Get choosedModel
   * @return choosedModel
  **/
  @Schema(description = "")
  public GenericOpenAIAPIChatModelChoice getChoosedModel() {
    return choosedModel;
  }

  public void setChoosedModel(GenericOpenAIAPIChatModelChoice choosedModel) {
    this.choosedModel = choosedModel;
  }

  public GenericOpenAIAPIChatModelConfig baseUrl(Object baseUrl) {
    this.baseUrl = baseUrl;
    return this;
  }

   /**
   * Get baseUrl
   * @return baseUrl
  **/
  @Schema(description = "")
  public Object getBaseUrl() {
    return baseUrl;
  }

  public void setBaseUrl(Object baseUrl) {
    this.baseUrl = baseUrl;
  }

  public GenericOpenAIAPIChatModelConfig contextLength(Object contextLength) {
    this.contextLength = contextLength;
    return this;
  }

   /**
   * Get contextLength
   * @return contextLength
  **/
  @Schema(description = "")
  public Object getContextLength() {
    return contextLength;
  }

  public void setContextLength(Object contextLength) {
    this.contextLength = contextLength;
  }

  public GenericOpenAIAPIChatModelConfig topP(Object topP) {
    this.topP = topP;
    return this;
  }

   /**
   * Get topP
   * @return topP
  **/
  @Schema(description = "")
  public Object getTopP() {
    return topP;
  }

  public void setTopP(Object topP) {
    this.topP = topP;
  }

  public GenericOpenAIAPIChatModelConfig accessibleGroups(Object accessibleGroups) {
    this.accessibleGroups = accessibleGroups;
    return this;
  }

   /**
   * Get accessibleGroups
   * @return accessibleGroups
  **/
  @Schema(description = "")
  public Object getAccessibleGroups() {
    return accessibleGroups;
  }

  public void setAccessibleGroups(Object accessibleGroups) {
    this.accessibleGroups = accessibleGroups;
  }

  public GenericOpenAIAPIChatModelConfig accessibleUsers(Object accessibleUsers) {
    this.accessibleUsers = accessibleUsers;
    return this;
  }

   /**
   * Get accessibleUsers
   * @return accessibleUsers
  **/
  @Schema(description = "")
  public Object getAccessibleUsers() {
    return accessibleUsers;
  }

  public void setAccessibleUsers(Object accessibleUsers) {
    this.accessibleUsers = accessibleUsers;
  }

  public GenericOpenAIAPIChatModelConfig accessibleToAll(Object accessibleToAll) {
    this.accessibleToAll = accessibleToAll;
    return this;
  }

   /**
   * Get accessibleToAll
   * @return accessibleToAll
  **/
  @Schema(description = "")
  public Object getAccessibleToAll() {
    return accessibleToAll;
  }

  public void setAccessibleToAll(Object accessibleToAll) {
    this.accessibleToAll = accessibleToAll;
  }

  public GenericOpenAIAPIChatModelConfig enabledFunctions(Object enabledFunctions) {
    this.enabledFunctions = enabledFunctions;
    return this;
  }

   /**
   * Get enabledFunctions
   * @return enabledFunctions
  **/
  @Schema(description = "")
  public Object getEnabledFunctions() {
    return enabledFunctions;
  }

  public void setEnabledFunctions(Object enabledFunctions) {
    this.enabledFunctions = enabledFunctions;
  }

  public GenericOpenAIAPIChatModelConfig temperature(Object temperature) {
    this.temperature = temperature;
    return this;
  }

   /**
   * Get temperature
   * @return temperature
  **/
  @Schema(description = "")
  public Object getTemperature() {
    return temperature;
  }

  public void setTemperature(Object temperature) {
    this.temperature = temperature;
  }

  public GenericOpenAIAPIChatModelConfig forUses(Object forUses) {
    this.forUses = forUses;
    return this;
  }

   /**
   * Get forUses
   * @return forUses
  **/
  @Schema(description = "")
  public Object getForUses() {
    return forUses;
  }

  public void setForUses(Object forUses) {
    this.forUses = forUses;
  }

  public GenericOpenAIAPIChatModelConfig features(Object features) {
    this.features = features;
    return this;
  }

   /**
   * Get features
   * @return features
  **/
  @Schema(description = "")
  public Object getFeatures() {
    return features;
  }

  public void setFeatures(Object features) {
    this.features = features;
  }

  public GenericOpenAIAPIChatModelConfig thinking(Object thinking) {
    this.thinking = thinking;
    return this;
  }

   /**
   * Get thinking
   * @return thinking
  **/
  @Schema(description = "")
  public Object getThinking() {
    return thinking;
  }

  public void setThinking(Object thinking) {
    this.thinking = thinking;
  }

  public GenericOpenAIAPIChatModelConfig maxGeneratedTokens(Object maxGeneratedTokens) {
    this.maxGeneratedTokens = maxGeneratedTokens;
    return this;
  }

   /**
   * Get maxGeneratedTokens
   * @return maxGeneratedTokens
  **/
  @Schema(description = "")
  public Object getMaxGeneratedTokens() {
    return maxGeneratedTokens;
  }

  public void setMaxGeneratedTokens(Object maxGeneratedTokens) {
    this.maxGeneratedTokens = maxGeneratedTokens;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GenericOpenAIAPIChatModelConfig genericOpenAIAPIChatModelConfig = (GenericOpenAIAPIChatModelConfig) o;
    return Objects.equals(this.code, genericOpenAIAPIChatModelConfig.code) &&
        Objects.equals(this.description, genericOpenAIAPIChatModelConfig.description) &&
        Objects.equals(this.userModified, genericOpenAIAPIChatModelConfig.userModified) &&
        Objects.equals(this.userCreated, genericOpenAIAPIChatModelConfig.userCreated) &&
        Objects.equals(this.dateModified, genericOpenAIAPIChatModelConfig.dateModified) &&
        Objects.equals(this.dateCreated, genericOpenAIAPIChatModelConfig.dateCreated) &&
        Objects.equals(this.modelTypeCode, genericOpenAIAPIChatModelConfig.modelTypeCode) &&
        Objects.equals(this.defaultModel, genericOpenAIAPIChatModelConfig.defaultModel) &&
        Objects.equals(this.apiSecretCode, genericOpenAIAPIChatModelConfig.apiSecretCode) &&
        Objects.equals(this.choosedModel, genericOpenAIAPIChatModelConfig.choosedModel) &&
        Objects.equals(this.baseUrl, genericOpenAIAPIChatModelConfig.baseUrl) &&
        Objects.equals(this.contextLength, genericOpenAIAPIChatModelConfig.contextLength) &&
        Objects.equals(this.topP, genericOpenAIAPIChatModelConfig.topP) &&
        Objects.equals(this.accessibleGroups, genericOpenAIAPIChatModelConfig.accessibleGroups) &&
        Objects.equals(this.accessibleUsers, genericOpenAIAPIChatModelConfig.accessibleUsers) &&
        Objects.equals(this.accessibleToAll, genericOpenAIAPIChatModelConfig.accessibleToAll) &&
        Objects.equals(this.enabledFunctions, genericOpenAIAPIChatModelConfig.enabledFunctions) &&
        Objects.equals(this.temperature, genericOpenAIAPIChatModelConfig.temperature) &&
        Objects.equals(this.forUses, genericOpenAIAPIChatModelConfig.forUses) &&
        Objects.equals(this.features, genericOpenAIAPIChatModelConfig.features) &&
        Objects.equals(this.thinking, genericOpenAIAPIChatModelConfig.thinking) &&
        Objects.equals(this.maxGeneratedTokens, genericOpenAIAPIChatModelConfig.maxGeneratedTokens);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, description, userModified, userCreated, dateModified, dateCreated, modelTypeCode, defaultModel, apiSecretCode, choosedModel, baseUrl, contextLength, topP, accessibleGroups, accessibleUsers, accessibleToAll, enabledFunctions, temperature, forUses, features, thinking, maxGeneratedTokens);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GenericOpenAIAPIChatModelConfig {\n");
    
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    userModified: ").append(toIndentedString(userModified)).append("\n");
    sb.append("    userCreated: ").append(toIndentedString(userCreated)).append("\n");
    sb.append("    dateModified: ").append(toIndentedString(dateModified)).append("\n");
    sb.append("    dateCreated: ").append(toIndentedString(dateCreated)).append("\n");
    sb.append("    modelTypeCode: ").append(toIndentedString(modelTypeCode)).append("\n");
    sb.append("    defaultModel: ").append(toIndentedString(defaultModel)).append("\n");
    sb.append("    apiSecretCode: ").append(toIndentedString(apiSecretCode)).append("\n");
    sb.append("    choosedModel: ").append(toIndentedString(choosedModel)).append("\n");
    sb.append("    baseUrl: ").append(toIndentedString(baseUrl)).append("\n");
    sb.append("    contextLength: ").append(toIndentedString(contextLength)).append("\n");
    sb.append("    topP: ").append(toIndentedString(topP)).append("\n");
    sb.append("    accessibleGroups: ").append(toIndentedString(accessibleGroups)).append("\n");
    sb.append("    accessibleUsers: ").append(toIndentedString(accessibleUsers)).append("\n");
    sb.append("    accessibleToAll: ").append(toIndentedString(accessibleToAll)).append("\n");
    sb.append("    enabledFunctions: ").append(toIndentedString(enabledFunctions)).append("\n");
    sb.append("    temperature: ").append(toIndentedString(temperature)).append("\n");
    sb.append("    forUses: ").append(toIndentedString(forUses)).append("\n");
    sb.append("    features: ").append(toIndentedString(features)).append("\n");
    sb.append("    thinking: ").append(toIndentedString(thinking)).append("\n");
    sb.append("    maxGeneratedTokens: ").append(toIndentedString(maxGeneratedTokens)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
