/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package gebo.microservices.api.client.brain.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import gebo.microservices.api.client.brain.model.GOllamaEmbeddingModelChoice;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * GOllamaEmbeddingModelConfig
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-07-21T14:57:36.399842475+02:00[Europe/Rome]")

public class GOllamaEmbeddingModelConfig {
  @JsonProperty("code")
  private Object code = null;

  @JsonProperty("description")
  private Object description = null;

  @JsonProperty("userModified")
  private Object userModified = null;

  @JsonProperty("userCreated")
  private Object userCreated = null;

  @JsonProperty("dateModified")
  private Object dateModified = null;

  @JsonProperty("dateCreated")
  private Object dateCreated = null;

  @JsonProperty("modelTypeCode")
  private Object modelTypeCode = null;

  @JsonProperty("defaultModel")
  private Object defaultModel = null;

  @JsonProperty("apiSecretCode")
  private Object apiSecretCode = null;

  @JsonProperty("choosedModel")
  private GOllamaEmbeddingModelChoice choosedModel = null;

  @JsonProperty("baseUrl")
  private Object baseUrl = null;

  @JsonProperty("contextLength")
  private Object contextLength = null;

  @JsonProperty("tokenizationThreshold")
  private Object tokenizationThreshold = null;

  public GOllamaEmbeddingModelConfig code(Object code) {
    this.code = code;
    return this;
  }

   /**
   * Get code
   * @return code
  **/
  @Schema(description = "")
  public Object getCode() {
    return code;
  }

  public void setCode(Object code) {
    this.code = code;
  }

  public GOllamaEmbeddingModelConfig description(Object description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @Schema(description = "")
  public Object getDescription() {
    return description;
  }

  public void setDescription(Object description) {
    this.description = description;
  }

  public GOllamaEmbeddingModelConfig userModified(Object userModified) {
    this.userModified = userModified;
    return this;
  }

   /**
   * Get userModified
   * @return userModified
  **/
  @Schema(description = "")
  public Object getUserModified() {
    return userModified;
  }

  public void setUserModified(Object userModified) {
    this.userModified = userModified;
  }

  public GOllamaEmbeddingModelConfig userCreated(Object userCreated) {
    this.userCreated = userCreated;
    return this;
  }

   /**
   * Get userCreated
   * @return userCreated
  **/
  @Schema(description = "")
  public Object getUserCreated() {
    return userCreated;
  }

  public void setUserCreated(Object userCreated) {
    this.userCreated = userCreated;
  }

  public GOllamaEmbeddingModelConfig dateModified(Object dateModified) {
    this.dateModified = dateModified;
    return this;
  }

   /**
   * Get dateModified
   * @return dateModified
  **/
  @Schema(description = "")
  public Object getDateModified() {
    return dateModified;
  }

  public void setDateModified(Object dateModified) {
    this.dateModified = dateModified;
  }

  public GOllamaEmbeddingModelConfig dateCreated(Object dateCreated) {
    this.dateCreated = dateCreated;
    return this;
  }

   /**
   * Get dateCreated
   * @return dateCreated
  **/
  @Schema(description = "")
  public Object getDateCreated() {
    return dateCreated;
  }

  public void setDateCreated(Object dateCreated) {
    this.dateCreated = dateCreated;
  }

  public GOllamaEmbeddingModelConfig modelTypeCode(Object modelTypeCode) {
    this.modelTypeCode = modelTypeCode;
    return this;
  }

   /**
   * Get modelTypeCode
   * @return modelTypeCode
  **/
  @Schema(description = "")
  public Object getModelTypeCode() {
    return modelTypeCode;
  }

  public void setModelTypeCode(Object modelTypeCode) {
    this.modelTypeCode = modelTypeCode;
  }

  public GOllamaEmbeddingModelConfig defaultModel(Object defaultModel) {
    this.defaultModel = defaultModel;
    return this;
  }

   /**
   * Get defaultModel
   * @return defaultModel
  **/
  @Schema(description = "")
  public Object getDefaultModel() {
    return defaultModel;
  }

  public void setDefaultModel(Object defaultModel) {
    this.defaultModel = defaultModel;
  }

  public GOllamaEmbeddingModelConfig apiSecretCode(Object apiSecretCode) {
    this.apiSecretCode = apiSecretCode;
    return this;
  }

   /**
   * Get apiSecretCode
   * @return apiSecretCode
  **/
  @Schema(description = "")
  public Object getApiSecretCode() {
    return apiSecretCode;
  }

  public void setApiSecretCode(Object apiSecretCode) {
    this.apiSecretCode = apiSecretCode;
  }

  public GOllamaEmbeddingModelConfig choosedModel(GOllamaEmbeddingModelChoice choosedModel) {
    this.choosedModel = choosedModel;
    return this;
  }

   /**
   * Get choosedModel
   * @return choosedModel
  **/
  @Schema(description = "")
  public GOllamaEmbeddingModelChoice getChoosedModel() {
    return choosedModel;
  }

  public void setChoosedModel(GOllamaEmbeddingModelChoice choosedModel) {
    this.choosedModel = choosedModel;
  }

  public GOllamaEmbeddingModelConfig baseUrl(Object baseUrl) {
    this.baseUrl = baseUrl;
    return this;
  }

   /**
   * Get baseUrl
   * @return baseUrl
  **/
  @Schema(description = "")
  public Object getBaseUrl() {
    return baseUrl;
  }

  public void setBaseUrl(Object baseUrl) {
    this.baseUrl = baseUrl;
  }

  public GOllamaEmbeddingModelConfig contextLength(Object contextLength) {
    this.contextLength = contextLength;
    return this;
  }

   /**
   * Get contextLength
   * @return contextLength
  **/
  @Schema(description = "")
  public Object getContextLength() {
    return contextLength;
  }

  public void setContextLength(Object contextLength) {
    this.contextLength = contextLength;
  }

  public GOllamaEmbeddingModelConfig tokenizationThreshold(Object tokenizationThreshold) {
    this.tokenizationThreshold = tokenizationThreshold;
    return this;
  }

   /**
   * Get tokenizationThreshold
   * @return tokenizationThreshold
  **/
  @Schema(description = "")
  public Object getTokenizationThreshold() {
    return tokenizationThreshold;
  }

  public void setTokenizationThreshold(Object tokenizationThreshold) {
    this.tokenizationThreshold = tokenizationThreshold;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GOllamaEmbeddingModelConfig gollamaEmbeddingModelConfig = (GOllamaEmbeddingModelConfig) o;
    return Objects.equals(this.code, gollamaEmbeddingModelConfig.code) &&
        Objects.equals(this.description, gollamaEmbeddingModelConfig.description) &&
        Objects.equals(this.userModified, gollamaEmbeddingModelConfig.userModified) &&
        Objects.equals(this.userCreated, gollamaEmbeddingModelConfig.userCreated) &&
        Objects.equals(this.dateModified, gollamaEmbeddingModelConfig.dateModified) &&
        Objects.equals(this.dateCreated, gollamaEmbeddingModelConfig.dateCreated) &&
        Objects.equals(this.modelTypeCode, gollamaEmbeddingModelConfig.modelTypeCode) &&
        Objects.equals(this.defaultModel, gollamaEmbeddingModelConfig.defaultModel) &&
        Objects.equals(this.apiSecretCode, gollamaEmbeddingModelConfig.apiSecretCode) &&
        Objects.equals(this.choosedModel, gollamaEmbeddingModelConfig.choosedModel) &&
        Objects.equals(this.baseUrl, gollamaEmbeddingModelConfig.baseUrl) &&
        Objects.equals(this.contextLength, gollamaEmbeddingModelConfig.contextLength) &&
        Objects.equals(this.tokenizationThreshold, gollamaEmbeddingModelConfig.tokenizationThreshold);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, description, userModified, userCreated, dateModified, dateCreated, modelTypeCode, defaultModel, apiSecretCode, choosedModel, baseUrl, contextLength, tokenizationThreshold);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GOllamaEmbeddingModelConfig {\n");
    
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    userModified: ").append(toIndentedString(userModified)).append("\n");
    sb.append("    userCreated: ").append(toIndentedString(userCreated)).append("\n");
    sb.append("    dateModified: ").append(toIndentedString(dateModified)).append("\n");
    sb.append("    dateCreated: ").append(toIndentedString(dateCreated)).append("\n");
    sb.append("    modelTypeCode: ").append(toIndentedString(modelTypeCode)).append("\n");
    sb.append("    defaultModel: ").append(toIndentedString(defaultModel)).append("\n");
    sb.append("    apiSecretCode: ").append(toIndentedString(apiSecretCode)).append("\n");
    sb.append("    choosedModel: ").append(toIndentedString(choosedModel)).append("\n");
    sb.append("    baseUrl: ").append(toIndentedString(baseUrl)).append("\n");
    sb.append("    contextLength: ").append(toIndentedString(contextLength)).append("\n");
    sb.append("    tokenizationThreshold: ").append(toIndentedString(tokenizationThreshold)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
