/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package gebo.microservices.api.client.brain.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * LLMSModelsPresets
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-07-21T14:57:36.399842475+02:00[Europe/Rome]")

public class LLMSModelsPresets {
  @JsonProperty("doModelsLookup")
  private Object doModelsLookup = null;

  @JsonProperty("type")
  private Object type = null;

  @JsonProperty("serviceHandler")
  private Object serviceHandler = null;

  @JsonProperty("choices")
  private Object choices = null;

  public LLMSModelsPresets doModelsLookup(Object doModelsLookup) {
    this.doModelsLookup = doModelsLookup;
    return this;
  }

   /**
   * Get doModelsLookup
   * @return doModelsLookup
  **/
  @Schema(description = "")
  public Object getDoModelsLookup() {
    return doModelsLookup;
  }

  public void setDoModelsLookup(Object doModelsLookup) {
    this.doModelsLookup = doModelsLookup;
  }

  public LLMSModelsPresets type(Object type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @Schema(required = true, description = "")
  public Object getType() {
    return type;
  }

  public void setType(Object type) {
    this.type = type;
  }

  public LLMSModelsPresets serviceHandler(Object serviceHandler) {
    this.serviceHandler = serviceHandler;
    return this;
  }

   /**
   * Get serviceHandler
   * @return serviceHandler
  **/
  @Schema(required = true, description = "")
  public Object getServiceHandler() {
    return serviceHandler;
  }

  public void setServiceHandler(Object serviceHandler) {
    this.serviceHandler = serviceHandler;
  }

  public LLMSModelsPresets choices(Object choices) {
    this.choices = choices;
    return this;
  }

   /**
   * Get choices
   * @return choices
  **/
  @Schema(description = "")
  public Object getChoices() {
    return choices;
  }

  public void setChoices(Object choices) {
    this.choices = choices;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LLMSModelsPresets llMSModelsPresets = (LLMSModelsPresets) o;
    return Objects.equals(this.doModelsLookup, llMSModelsPresets.doModelsLookup) &&
        Objects.equals(this.type, llMSModelsPresets.type) &&
        Objects.equals(this.serviceHandler, llMSModelsPresets.serviceHandler) &&
        Objects.equals(this.choices, llMSModelsPresets.choices);
  }

  @Override
  public int hashCode() {
    return Objects.hash(doModelsLookup, type, serviceHandler, choices);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LLMSModelsPresets {\n");
    
    sb.append("    doModelsLookup: ").append(toIndentedString(doModelsLookup)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    serviceHandler: ").append(toIndentedString(serviceHandler)).append("\n");
    sb.append("    choices: ").append(toIndentedString(choices)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
