/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package gebo.microservices.api.client.brain.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import gebo.microservices.api.client.brain.model.PageableObject;
import gebo.microservices.api.client.brain.model.SortObject;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * PageA2ARemoteAgentConfig
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-09-10T12:40:50.755430820+02:00[Europe/Rome]")

public class PageA2ARemoteAgentConfig {
  @JsonProperty("totalPages")
  private Object totalPages = null;

  @JsonProperty("totalElements")
  private Object totalElements = null;

  @JsonProperty("pageable")
  private PageableObject pageable = null;

  @JsonProperty("size")
  private Object size = null;

  @JsonProperty("content")
  private Object content = null;

  @JsonProperty("number")
  private Object number = null;

  @JsonProperty("sort")
  private SortObject sort = null;

  @JsonProperty("first")
  private Object first = null;

  @JsonProperty("last")
  private Object last = null;

  @JsonProperty("numberOfElements")
  private Object numberOfElements = null;

  @JsonProperty("empty")
  private Object empty = null;

  public PageA2ARemoteAgentConfig totalPages(Object totalPages) {
    this.totalPages = totalPages;
    return this;
  }

   /**
   * Get totalPages
   * @return totalPages
  **/
  @Schema(description = "")
  public Object getTotalPages() {
    return totalPages;
  }

  public void setTotalPages(Object totalPages) {
    this.totalPages = totalPages;
  }

  public PageA2ARemoteAgentConfig totalElements(Object totalElements) {
    this.totalElements = totalElements;
    return this;
  }

   /**
   * Get totalElements
   * @return totalElements
  **/
  @Schema(description = "")
  public Object getTotalElements() {
    return totalElements;
  }

  public void setTotalElements(Object totalElements) {
    this.totalElements = totalElements;
  }

  public PageA2ARemoteAgentConfig pageable(PageableObject pageable) {
    this.pageable = pageable;
    return this;
  }

   /**
   * Get pageable
   * @return pageable
  **/
  @Schema(description = "")
  public PageableObject getPageable() {
    return pageable;
  }

  public void setPageable(PageableObject pageable) {
    this.pageable = pageable;
  }

  public PageA2ARemoteAgentConfig size(Object size) {
    this.size = size;
    return this;
  }

   /**
   * Get size
   * @return size
  **/
  @Schema(description = "")
  public Object getSize() {
    return size;
  }

  public void setSize(Object size) {
    this.size = size;
  }

  public PageA2ARemoteAgentConfig content(Object content) {
    this.content = content;
    return this;
  }

   /**
   * Get content
   * @return content
  **/
  @Schema(description = "")
  public Object getContent() {
    return content;
  }

  public void setContent(Object content) {
    this.content = content;
  }

  public PageA2ARemoteAgentConfig number(Object number) {
    this.number = number;
    return this;
  }

   /**
   * Get number
   * @return number
  **/
  @Schema(description = "")
  public Object getNumber() {
    return number;
  }

  public void setNumber(Object number) {
    this.number = number;
  }

  public PageA2ARemoteAgentConfig sort(SortObject sort) {
    this.sort = sort;
    return this;
  }

   /**
   * Get sort
   * @return sort
  **/
  @Schema(description = "")
  public SortObject getSort() {
    return sort;
  }

  public void setSort(SortObject sort) {
    this.sort = sort;
  }

  public PageA2ARemoteAgentConfig first(Object first) {
    this.first = first;
    return this;
  }

   /**
   * Get first
   * @return first
  **/
  @Schema(description = "")
  public Object getFirst() {
    return first;
  }

  public void setFirst(Object first) {
    this.first = first;
  }

  public PageA2ARemoteAgentConfig last(Object last) {
    this.last = last;
    return this;
  }

   /**
   * Get last
   * @return last
  **/
  @Schema(description = "")
  public Object getLast() {
    return last;
  }

  public void setLast(Object last) {
    this.last = last;
  }

  public PageA2ARemoteAgentConfig numberOfElements(Object numberOfElements) {
    this.numberOfElements = numberOfElements;
    return this;
  }

   /**
   * Get numberOfElements
   * @return numberOfElements
  **/
  @Schema(description = "")
  public Object getNumberOfElements() {
    return numberOfElements;
  }

  public void setNumberOfElements(Object numberOfElements) {
    this.numberOfElements = numberOfElements;
  }

  public PageA2ARemoteAgentConfig empty(Object empty) {
    this.empty = empty;
    return this;
  }

   /**
   * Get empty
   * @return empty
  **/
  @Schema(description = "")
  public Object getEmpty() {
    return empty;
  }

  public void setEmpty(Object empty) {
    this.empty = empty;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PageA2ARemoteAgentConfig pageA2ARemoteAgentConfig = (PageA2ARemoteAgentConfig) o;
    return Objects.equals(this.totalPages, pageA2ARemoteAgentConfig.totalPages) &&
        Objects.equals(this.totalElements, pageA2ARemoteAgentConfig.totalElements) &&
        Objects.equals(this.pageable, pageA2ARemoteAgentConfig.pageable) &&
        Objects.equals(this.size, pageA2ARemoteAgentConfig.size) &&
        Objects.equals(this.content, pageA2ARemoteAgentConfig.content) &&
        Objects.equals(this.number, pageA2ARemoteAgentConfig.number) &&
        Objects.equals(this.sort, pageA2ARemoteAgentConfig.sort) &&
        Objects.equals(this.first, pageA2ARemoteAgentConfig.first) &&
        Objects.equals(this.last, pageA2ARemoteAgentConfig.last) &&
        Objects.equals(this.numberOfElements, pageA2ARemoteAgentConfig.numberOfElements) &&
        Objects.equals(this.empty, pageA2ARemoteAgentConfig.empty);
  }

  @Override
  public int hashCode() {
    return Objects.hash(totalPages, totalElements, pageable, size, content, number, sort, first, last, numberOfElements, empty);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PageA2ARemoteAgentConfig {\n");
    
    sb.append("    totalPages: ").append(toIndentedString(totalPages)).append("\n");
    sb.append("    totalElements: ").append(toIndentedString(totalElements)).append("\n");
    sb.append("    pageable: ").append(toIndentedString(pageable)).append("\n");
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    number: ").append(toIndentedString(number)).append("\n");
    sb.append("    sort: ").append(toIndentedString(sort)).append("\n");
    sb.append("    first: ").append(toIndentedString(first)).append("\n");
    sb.append("    last: ").append(toIndentedString(last)).append("\n");
    sb.append("    numberOfElements: ").append(toIndentedString(numberOfElements)).append("\n");
    sb.append("    empty: ").append(toIndentedString(empty)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
