/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { ChildVirtualFSParam } from '../model/childVirtualFSParam';
import { GObjectRefGProjectEndpoint } from '../model/gObjectRefGProjectEndpoint';
import { GProject } from '../model/gProject';
import { ProjectsResearchFilter } from '../model/projectsResearchFilter';
import { VDocumentInfo } from '../model/vDocumentInfo';
import { VFolderInfo } from '../model/vFolderInfo';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class ProjectsControllerService {

    protected basePath = 'http://localhost:12999';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * 
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteProject(body: GProject, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public deleteProject(body: GProject, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public deleteProject(body: GProject, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public deleteProject(body: GProject, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling deleteProject.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<any>('post',`${this.basePath}/api/admin/ProjectsController/deleteProject`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param knowledgeBaseCode 
     * @param parentProjectCode 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public findChildProjects(knowledgeBaseCode: string, parentProjectCode: string, observe?: 'body', reportProgress?: boolean): Observable<Array<GProject>>;
    public findChildProjects(knowledgeBaseCode: string, parentProjectCode: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<GProject>>>;
    public findChildProjects(knowledgeBaseCode: string, parentProjectCode: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<GProject>>>;
    public findChildProjects(knowledgeBaseCode: string, parentProjectCode: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (knowledgeBaseCode === null || knowledgeBaseCode === undefined) {
            throw new Error('Required parameter knowledgeBaseCode was null or undefined when calling findChildProjects.');
        }

        if (parentProjectCode === null || parentProjectCode === undefined) {
            throw new Error('Required parameter parentProjectCode was null or undefined when calling findChildProjects.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (knowledgeBaseCode !== undefined && knowledgeBaseCode !== null) {
            queryParameters = queryParameters.set('knowledgeBaseCode', <any>knowledgeBaseCode);
        }
        if (parentProjectCode !== undefined && parentProjectCode !== null) {
            queryParameters = queryParameters.set('parentProjectCode', <any>parentProjectCode);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<GProject>>('get',`${this.basePath}/api/admin/ProjectsController/findChildProjects`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param knowledgeBaseCode 
     * @param actualSelectedProjects 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public findOtherKnowledgeBaseIncludableProjects(knowledgeBaseCode: string, actualSelectedProjects: Array<string>, observe?: 'body', reportProgress?: boolean): Observable<Array<GProject>>;
    public findOtherKnowledgeBaseIncludableProjects(knowledgeBaseCode: string, actualSelectedProjects: Array<string>, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<GProject>>>;
    public findOtherKnowledgeBaseIncludableProjects(knowledgeBaseCode: string, actualSelectedProjects: Array<string>, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<GProject>>>;
    public findOtherKnowledgeBaseIncludableProjects(knowledgeBaseCode: string, actualSelectedProjects: Array<string>, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (knowledgeBaseCode === null || knowledgeBaseCode === undefined) {
            throw new Error('Required parameter knowledgeBaseCode was null or undefined when calling findOtherKnowledgeBaseIncludableProjects.');
        }

        if (actualSelectedProjects === null || actualSelectedProjects === undefined) {
            throw new Error('Required parameter actualSelectedProjects was null or undefined when calling findOtherKnowledgeBaseIncludableProjects.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (knowledgeBaseCode !== undefined && knowledgeBaseCode !== null) {
            queryParameters = queryParameters.set('knowledgeBaseCode', <any>knowledgeBaseCode);
        }
        if (actualSelectedProjects) {
            actualSelectedProjects.forEach((element) => {
                queryParameters = queryParameters.append('actualSelectedProjects', <any>element);
            })
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<GProject>>('get',`${this.basePath}/api/admin/ProjectsController/findOtherKnowledgeBaseIncludableProjects`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param code 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public findProjectByCode(code: string, observe?: 'body', reportProgress?: boolean): Observable<GProject>;
    public findProjectByCode(code: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<GProject>>;
    public findProjectByCode(code: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<GProject>>;
    public findProjectByCode(code: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (code === null || code === undefined) {
            throw new Error('Required parameter code was null or undefined when calling findProjectByCode.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (code !== undefined && code !== null) {
            queryParameters = queryParameters.set('code', <any>code);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<GProject>('get',`${this.basePath}/api/admin/ProjectsController/findProjectByCode`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param knowledgeBaseCode 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public findRootProjects(knowledgeBaseCode: string, observe?: 'body', reportProgress?: boolean): Observable<Array<GProject>>;
    public findRootProjects(knowledgeBaseCode: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<GProject>>>;
    public findRootProjects(knowledgeBaseCode: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<GProject>>>;
    public findRootProjects(knowledgeBaseCode: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (knowledgeBaseCode === null || knowledgeBaseCode === undefined) {
            throw new Error('Required parameter knowledgeBaseCode was null or undefined when calling findRootProjects.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (knowledgeBaseCode !== undefined && knowledgeBaseCode !== null) {
            queryParameters = queryParameters.set('knowledgeBaseCode', <any>knowledgeBaseCode);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<GProject>>('get',`${this.basePath}/api/admin/ProjectsController/findRootProjects`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getChildDocuments(body: ChildVirtualFSParam, observe?: 'body', reportProgress?: boolean): Observable<Array<VDocumentInfo>>;
    public getChildDocuments(body: ChildVirtualFSParam, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<VDocumentInfo>>>;
    public getChildDocuments(body: ChildVirtualFSParam, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<VDocumentInfo>>>;
    public getChildDocuments(body: ChildVirtualFSParam, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling getChildDocuments.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<Array<VDocumentInfo>>('post',`${this.basePath}/api/admin/ProjectsController/getChildDocuments`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getChildFolders(body: ChildVirtualFSParam, observe?: 'body', reportProgress?: boolean): Observable<Array<VFolderInfo>>;
    public getChildFolders(body: ChildVirtualFSParam, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<VFolderInfo>>>;
    public getChildFolders(body: ChildVirtualFSParam, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<VFolderInfo>>>;
    public getChildFolders(body: ChildVirtualFSParam, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling getChildFolders.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<Array<VFolderInfo>>('post',`${this.basePath}/api/admin/ProjectsController/getChildFolders`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getProjects(observe?: 'body', reportProgress?: boolean): Observable<Array<GProject>>;
    public getProjects(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<GProject>>>;
    public getProjects(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<GProject>>>;
    public getProjects(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<GProject>>('get',`${this.basePath}/api/admin/ProjectsController/getProjects`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getRootDocuments(body: GObjectRefGProjectEndpoint, observe?: 'body', reportProgress?: boolean): Observable<Array<VDocumentInfo>>;
    public getRootDocuments(body: GObjectRefGProjectEndpoint, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<VDocumentInfo>>>;
    public getRootDocuments(body: GObjectRefGProjectEndpoint, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<VDocumentInfo>>>;
    public getRootDocuments(body: GObjectRefGProjectEndpoint, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling getRootDocuments.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<Array<VDocumentInfo>>('post',`${this.basePath}/api/admin/ProjectsController/getRootDocuments`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getRootFolders(body: GObjectRefGProjectEndpoint, observe?: 'body', reportProgress?: boolean): Observable<Array<VFolderInfo>>;
    public getRootFolders(body: GObjectRefGProjectEndpoint, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<VFolderInfo>>>;
    public getRootFolders(body: GObjectRefGProjectEndpoint, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<VFolderInfo>>>;
    public getRootFolders(body: GObjectRefGProjectEndpoint, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling getRootFolders.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<Array<VFolderInfo>>('post',`${this.basePath}/api/admin/ProjectsController/getRootFolders`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public insertProject(body: GProject, observe?: 'body', reportProgress?: boolean): Observable<GProject>;
    public insertProject(body: GProject, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<GProject>>;
    public insertProject(body: GProject, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<GProject>>;
    public insertProject(body: GProject, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling insertProject.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<GProject>('post',`${this.basePath}/api/admin/ProjectsController/insertProject`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public searchProjects(body: ProjectsResearchFilter, observe?: 'body', reportProgress?: boolean): Observable<Array<GProject>>;
    public searchProjects(body: ProjectsResearchFilter, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<GProject>>>;
    public searchProjects(body: ProjectsResearchFilter, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<GProject>>>;
    public searchProjects(body: ProjectsResearchFilter, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling searchProjects.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<Array<GProject>>('post',`${this.basePath}/api/admin/ProjectsController/searchProjects`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public searchProjectsByQbe(body: GProject, observe?: 'body', reportProgress?: boolean): Observable<Array<GProject>>;
    public searchProjectsByQbe(body: GProject, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<GProject>>>;
    public searchProjectsByQbe(body: GProject, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<GProject>>>;
    public searchProjectsByQbe(body: GProject, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling searchProjectsByQbe.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<Array<GProject>>('post',`${this.basePath}/api/admin/ProjectsController/searchProjectsByQbe`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateProject(body: GProject, observe?: 'body', reportProgress?: boolean): Observable<GProject>;
    public updateProject(body: GProject, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<GProject>>;
    public updateProject(body: GProject, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<GProject>>;
    public updateProject(body: GProject, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling updateProject.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<GProject>('post',`${this.basePath}/api/admin/ProjectsController/updateProject`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
